plugins/che-dummy-plugin/0.0.1/meta.yaml, plugins/che-editor-theia/0.0.1/meta.yaml, plugins/che-editor-theia/1.0.0/meta.yaml, plugins/che-service-plugin/0.0.1/meta.yaml
Update meta to match https://github.com/ws-skeleton releases
https://github.com/eclipse/che/issues/10615
=> Update meta to match https://github.com/ws-skeleton releases

openshift/che-plugin-registry.yml
Remove route + fixes for @sleshchenko  comments in https://github.com/eclipse/che-plugin-registry/pull/3
=> Remove route 

Dockerfile, Dockerfile.rhel, index.sh
Generate index.json on docker image build stage
Reference to https://github.com/eclipse/che/issues/10745
=> Generate index.json on docker image build stage

plugins/che-dummy-plugin/0.0.1/meta.yaml, plugins/che-editor-theia/1.0.0/meta.yaml, plugins/che-service-plugin/0.0.1/meta.yaml
Update meta.yaml to match new plugin release URLs
=> Update URLs to match new release

index.sh
=> Add links to meta.yaml

plugins/che-service-plugin/0.0.1/meta.yaml
@benoitf fixed a bug and released a new version in the service plugin.
This commit updates meta.yaml of the service plugin.
=> Update service plugin binaries URL to the latest

index.sh
Add plugin's description to plugins list response
Reference https://github.com/eclipse/che/issues/11055
=> Add plugin's description to plugins list response

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
=> Use of Theia 0.3.14

README.md
Add a description of how to get a list of plugins, get meta of a plugin.
Reference @garagatyi comment https://github.com/eclipse/che/issues/10834#issuecomment-414249814
=> Add a description of how to get a list of plugins, get meta of a plugin

plugins/che-machine-exec-plugin/0.0.1/meta.yaml
Add che-machine-exec plugin.
https://github.com/eclipse/che/issues/11235
=> Add che-machine-exec plugin.

check_plugins_location.sh
Add an ability to have multiple versions of the same plugin.
Fixes #31
=> #31: Add an ability to have multiple versions of the same plugin

.htaccess
Allow authorization header in requests from UD.
We need this because now in multi-user Che UD can't fetch plugins list and shows error.
=> Allow authorization header in requests from UD

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Updated to the latest version of the plugin (exposes port for self hosting)
=> Update org.eclipse.che.editor.theia/1.0.0 URL

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Update Theia Plugin URL to be able to run in hosted mode
=> Update Theia URL to get HOSTED_PLUGIN_HOSTNAME env variable fix

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Use today Theia editor release that increase memory to 2G
=> Update Theia URL

Dockerfile
Add write permission for group users into plugins folder
=> Add write permission for group users into plugins folder 

plugins/che-dummy-plugin/0.0.1/meta.yaml
Change the name to be Che Samples : Hello World (instead of dummy)
=> Change the name to be Che Samples : Hello World (instead of dummy)

plugins/che-service-plugin/0.0.1/meta.yaml
Update name to be Che Samples: REST API Sidecar Plugin
=> Update name to be Che Samples: REST API Sidecar Plugin

plugins/che-dummy-plugin/0.0.1/meta.yaml, plugins/che-service-plugin/0.0.1/meta.yaml
=> Fixed not valid yaml files

plugins/org.eclipse.che.samples.container-fortune/0.0.1/meta.yaml
Provide Che fortune plug-in (that run in its own container)
Change-Id: Idaad8e0a62fd179ba13dd6782f8d06176c7bfd2d
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>
=> Provide Che fortune plug-in (that run in its own container)

plugins/org.eclipse.che.samples.container-fortune/0.0.1/meta.yaml
Change-Id: I0deb2f992a4899abf301e1b798294f209bb08d3b
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>
Update name to avoid spaces
=> Update name to avoid spaces

plugins/org.eclipse.che.editor.dirigible/1.0.0/meta.yaml
Change type of Eclipse Dirigible for Eclipse Che to Che Editor
=> Change type of Eclipse Dirigible for Eclipse Che to Che Editor

plugins/org.eclipse.che.editor.eclipseide/0.0.1/meta.yaml
Signed-off-by: Mickael Istria <mistria@redhat.com>
=> Plugin for Eclipse IDE (over Broadway) as editor in Che

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
=> Update Theia to 0.3.16

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Update theia to 0.3.17
Change-Id: I6abf6b2c149ae48174578a473d74a3ea76816d4c
=> Use of Theia 0.3.17

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Updates Theia editor plugin to newer version in which Theia is moved from 3000 to 3100 port.
Related issue: https://github.com/eclipse/che/issues/12074
=> Move Theia from 3000 to 3100 port

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Change-Id: I4f376df4a0c91927a6bdf7db84e017408af320ff
Update to theia 0.3.18
=> Update to theia 0.3.18

plugins/che-machine-exec-plugin/0.0.1/meta.yaml
Use che-machine-exec from original eclipse repository.
https://github.com/eclipse/che/issues/12423
=> Use che-machine-exec from original eclipse repo.

plugins/org.eclipse.che.editor.eclipseide/0.0.1/meta.yaml, plugins/org.eclipse.che.editor.gwt/1.0.0/meta.yaml, plugins/org.eclipse.che.editor.jupyter/1.0.0/meta.yaml, plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml, plugins/org.eclipse.che.theia.dev/0.0.1/meta.yaml
Update versions of editors/plugin
=> Update versions of editors/plugin

plugins/org.eclipse.che.vscode-sonarlint/0.0.1/meta.yaml
Add Sonarlint VS Code extension. It can showcase how to contribute VS Code extension to our registry.
=> Add Sonarlint VS Code extension

plugins/che-machine-exec-plugin/0.0.1/meta.yaml, plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Use direct links to che-plugin.yaml instead of tar.gz archives
to simplify release of new version.
=> Update Theia editor and Exec plugin

plugins/org.eclipse.che.vscode-sonarlint/0.0.1/meta.yaml
Add renamed field to SonarLint meta.yaml
Old property should be removed after several Che releases.
=> Add renamed field to SonarLint meta.yaml

plugins/org.eclipse.che.editor.dirigible/1.0.0/meta.yaml
Update Eclipse Dirigible meta.yaml
=> Update Eclipse Dirigible meta.yaml

plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Update Theia editor plugin with 0.3.19 version
=> Use Theia 0.3.19

plugins/org.eclipse.che.editor.theia/master/meta.yaml
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>
Add Che Theia plugin version `master` builded from Theia master and all Che extensions branch
=> Add Che Theia plugin version builded from master

kubernetes/che-plugin-registry/templates/service.yaml
Fixes a connection issue on Helm deployed environment.
=> Fix `spec.ports.port` in the service.

README.md
Fixes eclipse/che-plugin-registry#89.
=> Fix the URL.

plugins/redhat.vscode-yaml/0.3.0/meta.yaml
https://github.com/eclipse/che/issues/12438
This PR introduces Red Hat YAML plugin [1]
[1]  https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
=> Add Red Hat yaml plugin

README.md
Add info in README about all fields in plugin meta YAMLs
=> Add overview of fields in plugin meta YAML in README

plugins/org.eclipse.che.theia.dev/0.0.1/meta.yaml
che-theia-dev v0.0.3: Increase memory to build che-theia in che-theia-dev container
=> Update che-theia-dev version

plugins/redhat.vscode-openshift-connector/0.0.17/meta.yaml
The PR introduces OpenShift Connector Plugin.
The PR for a related Dockerfile https://github.com/eclipse/che-theia/pull/106
The related issue https://github.com/eclipse/che/issues/11488
=> Add OpenShift Connector Plugin

plugins/ms-kubernetes-tools.vscode-kubernetes-tools/0.1.16/meta.yaml, plugins/ms-kubernetes-tools.vscode-kubernetes-tools/0.1.17/meta.yaml
The PR introduces Kubernetes Tooling Plugin.
The PR for a related Dockerfile https://github.com/eclipse/che-theia/pull/105
The related issue https://github.com/eclipse/che/issues/10574
=> Add Kubernetes Tooling Plugin

plugins/ms-kubernetes-tools.vscode-kubernetes-tools/0.1.17/meta.yaml, plugins/ms-vscode.go/0.9.2/meta.yaml, plugins/ms-vscode.node-debug/1.32.1/meta.yaml, plugins/ms-vscode.node-debug2/1.31.6/meta.yaml, plugins/ms-vscode.typescript/1.30.2/meta.yaml, plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml, plugins/redhat.vscode-openshift-connector/0.0.17/meta.yaml, plugins/redhat.vscode-xml/0.3.0/meta.yaml, plugins/redhat.vscode-yaml/0.3.0/meta.yaml
Use ':next' tag instead of ':nightly'
eclipse/che-theia#63
Related pull: https://github.com/eclipse/che-theia/pull/114
=> Use ':next' tag instead of ':nightly'

plugins/che-omnisharp-plugin/0.0.1/meta.yaml, plugins/che-omnisharp-plugin/1.0.0/meta.yaml
The PR introduces C# language support plugin which is based on omnisharp.
The related issue https://github.com/eclipse/che/issues/12792
=> Introduce Che Omnisharp Plugin

.circleci/config.yml
Add shellcheck to CircleCI config
=> Add shellcheck to CircleCI config

.travis.yml
Remove config of TravisCI since now we have CircleCI in place
and it is way more robust
=> Remove config of TravisCI

Dockerfile
Fixes permissions for v2 folder
=> Fixed permissions for v2 folder

check_plugins_images.sh, check_plugins_location_v1.sh, check_plugins_location_v2.sh, check_plugins_viewer_mandatory_fields_v1.sh, check_plugins_viewer_mandatory_fields_v2.sh, check_plugins_viewer_mandatory_fields_v3.sh, cico_build.sh, index.sh, index_v2.sh, set_plugin_dates.sh
Fix critical shell mistakes from shellcheck linter POV
Fixes #140
=> Fix bash usage by scripts

v3/plugins/ws-skeleton/eclipseide/4.9.0/meta.yaml
Set to 4.9.0 version of Eclipse IDE
=> Set to 4.9.0 version of Eclipse IDE

v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml
Add Camel VS Code Extension with v3 metamodel
=> Add Camel VS Code Extension with v3 metamodel #109

v2/plugins/redhat/project-initializer/0.0.9/meta.yaml, v3/plugins/redhat/project-initializer/0.0.9/meta.yaml
Provide Red Hat Project Initializer VS Code extension for v2 and v3
metamodel #139
=> Provide Red Hat Project Initializer VS Code extension for v2 and v3

v3/plugins/ws-skeleton/jupyter/5.7.0/meta.yaml
Set Jupyter notebook version to 5.7.0
=> Set Jupyter notebook version to 5.7.0

v3/plugins/redhat/java/latest/meta.yaml
Updates java-debug to latest version
https://github.com/eclipse/che/issues/13216
=> Update java-debug to latest version

v2/plugins/redhat/java/0.38.0/meta.yaml, v2/plugins/redhat/java/0.43.0/meta.yaml, v3/plugins/redhat/java/0.38.0/meta.yaml, v3/plugins/redhat/java/0.43.0/meta.yaml
This PR updates the description of the java plugin now that it includes the debugger.
Issue: https://github.com/eclipse/che/issues/13237
=> Adds in java debugger info into the description

v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.2/meta.yaml, v3/plugins/redhat-developer/che-omnisharp-plugin/latest/meta.yaml
-  Updates omnisharp-theia-plugin to 0.0.2 version
-  Updates latest version of omnisharp-theia-plugin to use 0.0.2 version
=> Update omnisharp-theia-plugin to 0.0.2

v3/plugins/che-incubator/typescript/1.35.1/meta.yaml, v3/plugins/ms-python/python/2019.5.18875/meta.yaml, v3/plugins/ms-vscode/go/0.11.0/meta.yaml, v3/plugins/ms-vscode/node-debug/1.35.2/meta.yaml, v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
https://github.com/eclipse/che/issues/13521
Updates plugins to theirs latest versions
=> Update plugin to latest versions: Node, TS, Python, Go

v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.1/meta.yaml, v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.2/meta.yaml, v3/plugins/redhat-developer/che-omnisharp-plugin/latest/meta.yaml, v3/plugins/redhat-developer/netcoredbg-theia-plugin/0.0.1/meta.yaml, v3/plugins/redhat-developer/netcoredbg-theia-plugin/latest/meta.yaml, v3/plugins/redhat/java/0.38.0/meta.yaml, v3/plugins/redhat/java/0.43.0/meta.yaml, v3/plugins/redhat/java/0.46.0/meta.yaml
https://github.com/eclipse/che/issues/13521
Adds name of the container
Adds memory limit for old plugins
=> Update java, omnisharp, netcoredbg plugins

v3/plugins/redhat/vscode-openshift-connector/0.0.17/meta.yaml, v3/plugins/redhat/vscode-openshift-connector/0.0.19/meta.yaml, v3/plugins/redhat/vscode-openshift-connector/0.0.21/meta.yaml, v3/plugins/redhat/vscode-openshift-connector/latest/meta.yaml
https://github.com/eclipse/che/issues/13609
=> Fix OOM error for OpenShift Connector plugin

kubernetes/che-plugin-registry/templates/deployment.yaml, kubernetes/che-plugin-registry/values.yaml
- fix helm chart deployment config
- fix image to `quay.io` one
=> Helm chart deployment

README.md
Minor update in README.MD to trigger the master ci build - https://ci.centos.org/job/devtools-che-plugin-registry-build-master/
=> Minor update in README.MD to trigger the master ci build

v3/plugins/che-incubator/cpptools/0.1/meta.yaml, v3/plugins/che-incubator/cpptools/1.0/meta.yaml, v3/plugins/che-incubator/cpptools/latest/meta.yaml
It adds C/C++ plugin
https://github.com/eclipse/che/issues/13698
=> Add C/C++ plugin

v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17/meta.yaml, v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/latest/meta.yaml
Fixes https://github.com/eclipse/che/issues/14210 by increasing memory limit for K8s plugin sidecar.
=> Add more memory for K8s plugin sidecar to avoid OOM

.github/CODEOWNERS
Add myself as a codeowner for this repo now that we're not in code freeze.
=> Add amisevsk to code owners

.github/CODEOWNERS
Change-Id:...
add nickboldt to CODEOWNERS
Change-Id: Ib64b96b2bcff25809306485c90512d651cbf48c6
=> add nickboldt to CODEOWNERS

v3/plugins/redhat/rhamt/0.0.8/meta.yaml, v3/plugins/redhat/rhamt/latest/meta.yaml
Add RHAMT to the plugin registry.
=> WINDUP-2448 - Add rhamt to che plugin registry

v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.5/meta.yaml
Provides new version of Theia Omnisharp plug-in and updates latest version.
Related issue: https://github.com/eclipse/che/issues/14613
=> Add new version of Omnisharp plugin

v3/plugins/pizzafactory/xtend-lang/0.1.0/meta.yaml, v3/plugins/pizzafactory/xtend-lang/latest/meta.yaml, v3/plugins/pizzafactory/xtext-lang/0.4.0/meta.yaml, v3/plugins/pizzafactory/xtext-lang/latest/meta.yaml
Adds language supports for Xtext/Xtend.
=> Add language supports for Xtext/Xtend.

v3/plugins/pizzafactory/vscode-libra-move/0.0.10/meta.yaml, v3/plugins/pizzafactory/vscode-libra-move/latest/meta.yaml
Adds meta-files for Move smart contract language.
=> Add the LS plugin for Move by Libra

deploy/openshift/che-plugin-registry.yml
Adding cpu & memory requests / limits to the openshift template
https://github.com/redhat-developer/rh-che/issues/1664
NOTE: must be also backported to 7.3.x branch - https://github.com/eclipse/che-plugin-registry/pull/293
=> rh-che #1664 Adding cpu & memory requests / limits to the openshift template

deploy/openshift/che-plugin-registry.yml, openshift/che-plugin-registry.yml
Adding cpu / memory requests & limits to the openshift template
cherry-picking - https://github.com/eclipse/che-plugin-registry/pull/292
issue - https://github.com/redhat-developer/rh-che/issues/1664
=> rh-che #1664 Adding cpu / memory requests & limits to the openshift template

build/scripts/list_referenced_images.sh, v3/plugins/eclipse/che-theia/next/meta.yaml, v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.4/meta.yaml
Cherry pick fixes for 7.3.2
Pulls in:
- https://github.com/eclipse/che-plugin-registry/pull/282
https://github.com/eclipse/che/issues/15107
=> Cherry-pick airgap fixes for 7.3.x

deploy/kubernetes/che-plugin-registry/templates/configmap.yaml
Fix a typo in the helm chart that stops it from being parsed.
https://github.com/eclipse/che/issues/14994
=> Fix a typo in the helm chart

build/dockerfiles/rhel.Dockerfile
Change-Id:...
latest base images
Change-Id: Ic8289d1433dd945aa7c7843ebeca7b92b0f03511
=> latest base images

v3/plugins/ms-vscode/node-debug/1.32.1/meta.yaml, v3/plugins/ms-vscode/node-debug/1.35.2/meta.yaml, v3/plugins/ms-vscode/node-debug2/1.31.6/meta.yaml, v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml, v3/plugins/pizzafactory/vscode-libra-move/0.0.10/meta.yaml, v3/plugins/pizzafactory/xtend-lang/0.1.0/meta.yaml, v3/plugins/pizzafactory/xtext-lang/0.4.0/meta.yaml, v3/plugins/redhat/vscode-wsdl2rest/0.0.9/meta.yaml, v3/plugins/redhat/vscode-yaml/0.3.0/meta.yaml, v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml, v3/plugins/sonarsource/sonarlint-vscode/0.0.1/meta.yaml
Update registry to use newer images from che-dockerfiles
https://github.com/eclipse/che/issues/15402
=> Update registry to use newer images from che-dockerfiles

v3/plugins/redhat/vscode-camelk/0.0.10/meta.yaml, v3/plugins/redhat/vscode-camelk/0.0.9/meta.yaml
entrypoint was not executable
Fixes https://github.com/eclipse/che/issues/15455
Change-Id: Id00a2a710b626cd03158d24e66bac31b7c02e9bd
=> fix(camel-k): Update images to the latest one

build/scripts/meta.yaml.schema, v3/plugins/eclipse/che-theia/7.3.0/meta.yaml
Applies more strict rules to the schema file for meta.yaml
=> Update the schema of meta.yaml

v3/plugins/che-incubator/theia-dev/0.0.1/meta.yaml, v3/plugins/eclipse/che-theia/next/meta.yaml
Uses che-theia images from quay. 
Fixes: https://github.com/eclipse/che/issues/14849
=> Use che-theia images from quay

v3/plugins/che-incubator/cpptools/0.1/meta.yaml, v3/plugins/che-incubator/typescript/1.35.1/meta.yaml, v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml, v3/plugins/ms-python/python/2019.5.18875/meta.yaml, v3/plugins/ms-vscode/go/0.11.4/meta.yaml, v3/plugins/redhat/java/0.50.0/meta.yaml, v3/plugins/redhat/java8/0.50.0/meta.yaml, v3/plugins/redhat/php-debugger/1.13.0/meta.yaml, v3/plugins/redhat/php/1.0.13/meta.yaml
Update plugin extension locations
=> Update vsix plugin extensions location

v3/plugins/redhat/vscode-camelk/Contributing.md
=> Provide information when contributing for Camel K extension

.circleci/config.yml, cico_functions.sh
Attempts to remove unnecessary logs from CI builds (progress bars, etc).
=> Reduce verbosity in CI builds

v3/plugins/redhat/vscode-camelk/0.0.10-4/meta.yaml
=> Have sidecar corresponding to the Kubernetes extension used

v3/plugins/ms-vscode/go/0.11.4/meta.yaml
Update go sidecar to include changes from https://github.com/che-dockerfiles/che-sidecar-go/pull/4
=> Update go sidecar image to latest build

README.md
Add notion about building vsix extensions for plugin registry
=> Add notion about building vsix extensions for plugin registry

v3/plugins/redhat/php/1.0.14/meta.yaml
Update plugin PHP intelephense 1.0.14 VSIX location
=> Update vscode-intelephense 1.0.14 plugin location

v3/plugins/redhat/java11/0.57.0/meta.yaml, v3/plugins/redhat/java8/0.57.0/meta.yaml
Fixes the name of java plugins
=> fix java name

build/dockerfiles/Dockerfile, build/dockerfiles/rhel.Dockerfile
Fix check scripts execution flow
=> Fix execution of image build checks

build/dockerfiles/rhel.Dockerfile, build/dockerfiles/rhel.install.sh
=> minor tweaks from downstream

v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml, v3/plugins/eclipse/che-theia/next/meta.yaml, v3/plugins/eclipse/cloud-shell/nightly/meta.yaml
This re-introduces the changes done in #378 
This PR depends on eclipse/che#16227 be merged to Che server master.
=> Modify the che-machine-exec and che-theia plugins to only bind to127.0.0.1.

v3/plugins/cdr/code-server/next/meta.yaml
Corrects an article in the description of code-server plugin
=> fix: corrects article in desc of code-server

build/dockerfiles/Dockerfile
It replaces centos/httpd with alpine/httpd allowing to be smaller/updated and also multi-arch
Change-Id: I7a3050fcfdea30fe08e4127cf581713a9cc91b85
=> feat(alpine): Change parent image to be alpine based as well

build/dockerfiles/Dockerfile
This reverts commit f17c7593d07968a34b31fdceca0a4cf972dea1ea.
https://github.com/eclipse/che-plugin-registry/pull/444
=> Revert "feat(alpine): Change parent image to be alpine based

v3/plugins/eclipse/che-machine-exec-plugin/7.12.1/meta.yaml, v3/plugins/eclipse/che-theia/7.12.1/meta.yaml
Change-Id: I2b1a6fae7b375df842d12d873423411f9032555e
[release] Add 7.12.1 plugins in master
Change-Id: I2b1a6fae7b375df842d12d873423411f9032555e
=> [release] Add 7.12.1 plugins in master

v3/plugins/eclipse/che-machine-exec-plugin/7.12.2/meta.yaml, v3/plugins/eclipse/che-theia/7.12.2/meta.yaml
=> [release] Add 7.12.2 plugins in master

build/dockerfiles/fedora.repo, build/dockerfiles/rhel.Dockerfile, build/dockerfiles/rhel.install.sh
=> Added support for s390x

.ci/che-cert_generation.sh, .ci/cico-happy-path-pr-test.sh, .ci/cico_common.sh
Signed-off-by: Radim Hopp <rhopp@redhat.com>
Frist tries to run Happy Path in this repo.
issue
https://github.com/eclipse/che/issues/13327
=> Adding Happy Path test as PR check

v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17/meta.yaml, v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.1/meta.yaml, v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.2/meta.yaml, v3/plugins/redhat/java/0.38.0/meta.yaml, v3/plugins/redhat/java/0.43.0/meta.yaml, v3/plugins/redhat/java/0.45.0/meta.yaml, v3/plugins/redhat/java/0.46.0/meta.yaml, v3/plugins/redhat/java11/0.46.0/meta.yaml, v3/plugins/redhat/java8/0.46.0/meta.yaml, v3/plugins/redhat/vscode-openshift-connector/0.0.17/meta.yaml, v3/plugins/redhat/vscode-openshift-connector/0.0.19/meta.yaml, v3/plugins/redhat/vscode-openshift-connector/0.0.21/meta.yaml, v3/plugins/redhat/vscode-xml/0.3.0/meta.yaml, v3/plugins/redhat/vscode-xml/0.5.1/meta.yaml, v3/plugins/redhat/vscode-xml/0.7.0/meta.yaml
=> Mark out of date plugins as deprecated

v3/plugins/redhat/vscode-openshift-connector/0.1.5/meta.yaml
=> Update vscode-openshift-connector with alpine 3.12 image

v3/plugins/eclipse/che-theia/7.3.2/meta.yaml, v3/plugins/eclipse/che-theia/7.3.3/meta.yaml, v3/plugins/redhat/php/1.0.14/meta.yaml
Add missed registry name for some images. Use quay.io for php 1.0.14
=> Add missed registry name for some images.

build/dockerfiles/Dockerfile, build/dockerfiles/rhel.Dockerfile, build/scripts/check_sorted_json.sh, vscode-extensions.json
Keep the file ordered by github repository name
also attributes are listed in this order: 
- repository
- revision
- directory?
Add a check in the build script to ensure that.
Change-Id: I0b3986f479b5ec401d900f68e3993c1d707669b3
=> feat(vscode-extensions): ensure the json file is sorted

vscode-extensions.json
Add vscode-didact, fixup golang/vscode-go revision field.
=> Fix vscode-extensions.json

.vscode/launch.json, build/dockerfiles/Dockerfile, build/dockerfiles/entrypoint.sh
https://github.com/eclipse/che/issues/16815
Extract and use plugin images digest from env.
https://github.com/eclipse/che-operator/pull/274
=> Extract and use plugin images digest from env.

.github/workflows/publish-plugin-report.yaml, tools/automation/.ci/publish-report.sh, tools/automation/report/.vuepress/config.js, tools/automation/src/check-plugin-updates.ts
* Added report publish script and GH workflow
* Moved report index.md file to ./report folder
=> Publish report daily at 01:00 UTC

tools/automation/.ci/publish-report.sh
- move shebang on the first line
- add executable flag
- fix shellcheck
Change-Id: I6fc443180841af185677e17e71c0221ddec21915
=> fix(script): bunch of update on publish script

v3/plugins/golang/go/0.14.4/meta.yaml
Uses `che-sidecar-go:1.14.4` image in `golang/go` plugin.
Devfile to test
```
metadata:
generateName: golang-
projects:
-
name: example
source:
type: git
location: https://github.com/golang/example.git
clonePath: src/github.com/golang/example/
components:
-
reference: >-
https://raw.githubusercontent.com/vitaliy-guliy/che-plugin-registry/update-go-0.14.4/v3/plugins/golang/go/0.14.4/meta.yaml
alias: go-plugin
-
image: quay.io/eclipse/che-golang-1.12:nightly
alias: go-cli
env:
- name: GOPATH
value: /go:$(CHE_PROJECTS_ROOT)
- name: GOCACHE
value: /tmp/.cache
endpoints:
- name: '8080/tcp'
port: 8080
memoryLimit: 512Mi
mountSources: true
commands:
-
name: run outyet
actions:
- type: exec …
```
=> Use new version of che-sidecar-go image

.github/CODEOWNERS
=> Add former languages team members to CODEOWNERS

v3/plugins/redhat/rhamt/0.0.11/meta.yaml, v3/plugins/redhat/rhamt/0.0.23/meta.yaml, v3/plugins/redhat/rhamt/0.0.8/meta.yaml
=> Windup 2691

v3/plugins/ms-vscode/node-debug2/1.42.3/meta.yaml, v3/plugins/redhat/vscode-yaml/0.8.0/meta.yaml, v3/plugins/zowe/vscode-extension-for-zowe/1.5.1/meta.yaml, vscode-extensions.json
=> Use latest node image in plugins and vscode-extensions.json

v3/plugins/broadcommfd/cobol-language-support/0.12.0/meta.yaml, v3/plugins/redhat/java11/0.63.0/meta.yaml, v3/plugins/redhat/quarkus-java11/1.5.0/meta.yaml, v3/plugins/redhat/vscode-apache-camel/0.0.26/meta.yaml, v3/plugins/redhat/vscode-xml/0.13.0/meta.yaml, vscode-extensions.json
=> Update java sidecar references to use new image

v3/plugins/redhat/php-debugger/1.13.0/meta.yaml, v3/plugins/redhat/php/1.3.11/meta.yaml, vscode-extensions.json
=> Update php sidecar references to new image

v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.6a/meta.yaml, v3/plugins/redhat-developer/netcoredbg-theia-plugin/0.0.3a/meta.yaml, vscode-extensions.json
=> Update references to any dotnet 3.1 sidecar with new image

v3/plugins/scalameta/metals/1.9.1/meta.yaml, vscode-extensions.json
=> Update scala sidecar references to new image

v3/plugins/redhat/dependency-analytics/0.1.0/meta.yaml, vscode-extensions.json
=> Update references to use new sidecar image

v3/plugins/broadcommfd/cobol-language-support/0.12.0/meta.yaml, v3/plugins/redhat/java11/0.63.0/meta.yaml, v3/plugins/redhat/quarkus-java11/1.5.0/meta.yaml, v3/plugins/redhat/vscode-xml/0.13.0/meta.yaml, vscode-extensions.json
=> Update java11 plugins with new alpine 3.12 based sidecar

v3/plugins/redhat/php-debugger/1.13.0/meta.yaml, v3/plugins/redhat/php/1.3.11/meta.yaml, vscode-extensions.json
=> Update php plugins to use an alpine based image

vscode-extensions.json
=> Fix revision field for vetur extension

build/dockerfiles/Dockerfile
This fixes the CircleCI failure.
=> Update build script to use python 3

.ci/pr-check/src/pr-check.ts, v3/plugins/redhat/java/0.63.0/meta.yaml
Also included a dummy meta.yaml update to trigger the check
=> Fix icons/extensions PR check

tools/automation/.ci/publish-report.sh
=> Fix report publishing script after node_modules moved

.github/PULL_REQUEST_TEMPLATE.md
Add the new PR Template
https://github.com/eclipse/che/issues/17486
Change-Id: Iad511d9b1c473cff3a61a14847f80bd7553c6ac9
=> chore(github): Update the pull request template to match new definition of done on PR

tools/pr-check/src/pr-check.ts
* Check for explicit 404 codes
* Do not fail on rate limiting errors (response code 429)
=> Adjust vscode-extensions.json validation check

package.json, yarn.lock
Bum node-forge
https://github.com/advisories/GHSA-92xj-mqp7-vmcj
run yarn why node-forge after cloning the repo
it should list 0.10.0 (instead of 0.9.0 for now)
Change-Id: I3fa80bd34a0ae86ee1f540b7a24cfe466739b7f0
=> fix(cve): bump node-forge library

.github/workflows/build-jobs.yml, .github/workflows/pr-checks.yml
Adds a GitHub action job that builds + pushes the nightly image on every commit.
eclipse/che#18072
Not immediately testable as it's CI related work.
=> Switch nightly job to GitHub action

v3/plugins/bmewburn/vscode-intelephense-client/1.5.4/meta.yaml, v3/plugins/broadcommfd/cobol-language-support/0.15.0/meta.yaml, v3/plugins/redhat/java/0.69.0/meta.yaml, v3/plugins/redhat/java11/0.69.0/meta.yaml, v3/plugins/redhat/php-debugger/1.13.0/meta.yaml, v3/plugins/redhat/quarkus-java11/1.7.0/meta.yaml, v3/plugins/redhat/vscode-apache-camel/0.0.27/meta.yaml, v3/plugins/scalameta/metals/1.9.4/meta.yaml, v3/plugins/testthedocs/vale/0.9.1a/meta.yaml, vscode-extensions.json
Updates some plugins' sidecar containers to alpine 3.12.x
N/A
Not directly testable, this is a maintenance task.
=> Update to alpine 3.12.x

v3/plugins/haskell/vscode-haskell/8.10.1/meta.yaml, v3/plugins/haskell/vscode-haskell/8.10.2/meta.yaml, v3/plugins/haskell/vscode-haskell/8.8.4/meta.yaml, vscode-extensions.json
https://github.com/che-dockerfiles/che-sidecar-haskell/pull/7  
https://github.com/che-dockerfiles/che-sidecar-haskell/pull/5
https://github.com/che-dockerfiles/che-sidecar-haskell/pull/6
=> Haskell: add debug adapters:

v3/plugins/redhat/vscode-xml/0.13.0/meta.yaml
Fixes eclipse/che#18247
Updates vsix file to a valid one without the failure.
Launch a workspace with vscode-xml installed and check whether the plugin starts or not.
=> Use openvsx version of vscode-xml 0.13.0

tools/automation/report/.vuepress/styles/index.styl, tools/automation/report/.vuepress/styles/palette.styl
Currently the automatic plugin report looks very scrunched. This change will allow the table to take up the width of the page.
None, it's a personal pet peeve. :smiley: 
Build the report file in `tools/automation` and see the difference in size.
=> Fix width of automatic plugin report

.ci/sidecar-build-pr-check.sh, .ci/sidecar-build-publish.sh, .github/workflows/sidecar-build-push.yaml, .github/workflows/sidecar-pr-checks.yaml
Prepare the plugin-registry for sidecar definition migration. Part of eclipse/che#18217
CI work, testing will be done by opening PR's.
=> Add sidecar PR check and build/push actions

.github/workflows/sidecar-build-push.yaml, .github/workflows/sidecar-pr-checks.yaml
Updates names of GH action job steps.
N/A
eclipse/che#18217
N/A
=> Add a more descriptive name to sidecar GH actions

sidecars/java/Dockerfile, sidecars/java/PLATFORMS, sidecars/java/etc/before-start.sh, sidecars/java/etc/entrypoint.sh, sidecars/java8/Dockerfile, sidecars/java8/PLATFORMS, sidecars/java8/etc/before-start.sh, sidecars/java8/etc/entrypoint.sh
Includes fixes to the `before-start.sh` script to prevent shellcheck failures.
Migrates java sidecar definitions to the plugin registry.
N/A
eclipse/che#18217
N/A
=> Migrate java and java8 sidecars

v3/plugins/che-incubator/intellij-community/2020.2.2/meta.yaml
Allows running >1 Workspaces with IntelliJ Che Editor by declaring its endpoint not discoverable.
see the details in https://github.com/eclipse/che/issues/18347
=> Make intellij endpoint not discoverable to allow running >1 Workspaces

v3/plugins/che-incubator/intellij-community/2020.2.2/meta.yaml
Updates IntelliJ plugin endpoint name
as intellij liveness probe already added https://github.com/eclipse/che/pull/17998
=> Update IntelliJ plugin endpoint name

CONTRIBUTE.md
Updates the CONTRIBUTE.md guide to explain the new sidecar definition location.
N/A
Fixes eclipse/che#18217
N/A
=> Document new sidecar defintion location in CONTRIBUTE.md

v3/plugins/haskell/vscode-haskell/8.10.2/meta.yaml
=> Haskell: use new sidecar image location

sidecars/scala/Dockerfile
Supersede https://github.com/eclipse/che-plugin-registry/pull/695
Those programs aren't necessary in a sidecar at all.
=> Scala sidecar: simplify as much as possible

v3/plugins/scalameta/metals/1.9.6/meta.yaml, vscode-extensions.json
=> Update sidecar in Scala Metals plugin

cico_functions.sh
Authenticate to docker.io to prevent failing the build on Centos CI due to pull limits
=> Add login to docker.io to avoid pull limitations

v3/plugins/cdr/code-server/3.6.2/meta.yaml, v3/plugins/dirigiblelabs/dirigible/3.4.0/meta.yaml, v3/plugins/ws-skeleton/eclipseide/4.9.0/meta.yaml, v3/plugins/ws-skeleton/jupyter/5.7.0/meta.yaml
This is a partial revert for commit 2ce2168579106f8a63d55077a22054321d5f9845.
Using docker login should allow to make releases
We can ask upstream projects to move their images on other docker registries in the meantime
All plug-ins work as before
@nickboldt needs to be backported to 7.22.x branch and included in 7.22.0 tag
=> Revert "18292 - switch to use quay copies of... (#702)"

v3/plugins/che-incubator/intellij-community/2020.2.2/meta.yaml
Update IntelliJ editor image version as it includes a bunch of fixes comparing to the currently used.
Updates IntelliJ editor image version as it includes a bunch of fixes comparing to the currently used.
It includes the fix for https://github.com/eclipse/che/issues/18270
=> Update IntelliJ editor image version

sidecars/clang/Dockerfile, sidecars/clang/PLATFORMS, sidecars/clang/etc/entrypoint.sh
Migrates the che-sidecar-clang image to the plugin registry.
N/A
eclipse/che#18217
N/A
=> Migrate the che-sidecar-clang image

v3/plugins/eclipse/che-theia/next/meta.yaml
Adds a dedicated endpoint for exposing Che Theia `/mini-browser` content.
Part of the required fix for https://github.com/eclipse/che/issues/18456
Another part is in https://github.com/eclipse/che-theia/pull/930
=> Add a dedicated endpoint for exposing Che Theia mini-browser content

che-theia-plugins.yaml
there is no `redhat/java` plug-in defined
so defines `redhat/java` as being an alias of `redhat/java11`
note: it will flag `redhat/java` as being deprecated over `redhat/java11`
Automating generation of meta.yaml from che-theia-plugins.yaml
look at v3/plugins/redhat there are both `java` and `java11`
Change-Id: I6f0479b2f58ae19261b112f9c4eea774f35a0171
=> fix(redhat/java) add alias

che-theia-plugins.yaml
Fix the yaml indenting
Sidecar was not added on the correct element
look at the indent
Change-Id: I55d5d382754546add328b2158d821f2314cfa20a
=> fix(sidecar): Indent is wrong so it does not add sidecar information

.github/workflows/build-jobs.yml
In the event of a high traffic day, we want all build jobs to run and not fail if 2 more PRs are merged in a row.
Increases fetch-depth to 10 from 1
N/A
N/A
Not easy to test, but open and merge multiple PRs in a row -- you will see build failures on the remaining PRs when merged.
=> Update fetch-depth to 10

sidecars/rust/Dockerfile, sidecars/rust/PLATFORMS, sidecars/rust/etc/entrypoint.sh
Add a side car for the rust extension
https://github.com/eclipse/che/issues/17069
Run a workspace out of this devfile.yaml:
```yaml
metadata:
generateName: rust-
projects:
- name: HelloWorld-Rust
source:
location: 'https://github.com/che-samples/helloworld-rust.git'
type: git
branch: master
components:
- mountSources: true
memoryLimit: 512Mi
alias: rust
image: quay.io/eclipse/che-rust-1.39:nightly
- type: chePlugin
reference: 'https://gist.githubusercontent.com/sunix/eb86fdf6802afbfb4de059ed19f08d37/raw/41515915211723ca3c740d28263d7b8a87e0a8b6/meta.yaml'
commands:
- name: build
actions:
- workdir: '${CHE_PROJECTS_ROOT}/HelloWorld-Rust'
type: exec
command: cargo build
component: rust
- name: run
actions:
- workdir: '${CHE_PROJECTS_ROOT}/HelloWorld-Rust' …
```
=> feat(sidecar): Add Rust sidecar

sidecars/camelk/Dockerfile
eclipse/che#18521
it updates the Camel K binary to newer release 1.2.1 which the default version used by newer VS Code Camel K extension
=> Upgrade kamel to 1.2.1 for VS Code Camel K 0.0.19 support

v3/plugins/redhat/vscode-camelk/Contributing.md
=> Update contributing guide of Camel K as sidecars now part of the same

che-theia-plugins.yaml
Some extensions had previous ids that were not the ids used by the VS Code extensions
Add aliases to add compatibility with previous ids
eclipse/che#18215
Compare current ids of the plug-ins with the one contained in package.json of vsix files
Change-Id: Ib6b7a313f452d7fec4cc9ea228ac84838435703b
=> fix(vscode-plugins): Add missing aliases

.github/workflows/typescript-pr-check.yml
I noticed that projects are no longer building due to format error, lint errors or tests errors.
This action ensures that it's correctly validated/builded on each PR
Some PRs have all green checks but it does not compile/pass the lint checks.
https://github.com/eclipse/che-plugin-registry/pull/719
you can manually run the command: `yarn workspaces build`
Change-Id: Ib10331c18dd6e54cb61b44328eb68a57981cebe9
=> chore(PR): Ensure on PR check that the typescript projects are still working

che-theia-plugins.yaml, tools/automation/package.json, tools/automation/src/check-plugin-update-template.md, tools/automation/src/check-plugin-updates.ts, yarn.lock
* Remove sidecar entries (these are part of the registry now)
* Adapt to the new YAML file format
* Deal with duplicate repos for plugins with id's
N/A
Part of eclipse/che#18215
Generate the report locally, it should work using the new file.
=> Prepare the automated plugin report for the new che-theia-plugins file

CONTRIBUTE.md
Updates the CONTRIBUTE.md file to remove outdated information about `vscode-extensions.json`.
N/A
Part of eclipse/che#18215
N/A
=> Update CONTRIBUTE.md to account for the new che-theia-plugins.yaml file

che-theia-plugins.yaml
Adding rust plugin with rust language support (autocomplete, etc ...)
https://github.com/eclipse/che/issues/17069
=> feat(vscode-plugins): add rust plugin

che-theia-plugins.yaml
Allows to use prettier with a VS Code extension
https://github.com/eclipse/che/issues/18550
Here is a meta.yaml to test: 
https://raw.githubusercontent.com/benoitf/my-plugin-registry/master/esbenp/prettier-vscode/5.8.0/meta.yaml
once node dependencies (node_modules is there), use Format Document 
In 'Output view' you should see 'prettier' console saying that it's formatting the file
Change-Id: I372c88429e1caaececa58c38cde8078036b87af0
=> feat(prettier): Add prettier plug-in in plug-in registry

.github/workflows/image-build-pr-check.yml
Clone with full git history to get all expected sha-1
CI jobs are not finding the sha1 of sidecars directory without the full git history
Look at the deployed result on surge.sh it should be correct reference
Change-Id: I27a96110b57e1ed62735cf2d8e84d535a837da14
=> chore(ci): In order to produce correct meta.yaml files, it requires to have full git history

che-editors.yaml
Contributes a `che-editors.yaml` file, similar to the `che-theia-plugins.yaml` file, but for editors.
N/A
Closes eclipse/che#18214
N/A for now
=> Introduce a che-editors file

che-theia-plugins.yaml
New version of plugin: cobol-language-support 0.16.1
=> cobol-language-support 0.16.1

che-theia-plugins.yaml
Set memory limit for typescript plugin
https://github.com/eclipse/che/issues/18605
Create a workspace that uses the typescript plugin with the meta.yaml from this workspace.
=> Add memory limit for Typescript plugin

.github/workflows/publish-content-push-main.yml
We're publishing content of each PR to surge.sh but we should do the same for the main/(HEAD) content as well to be able to browse online any new build of the plug-in registry
N/A
If build is successful, it should triggers that workflow that will push the content
=> chore(publish): Upload v3 content on each push to HEAD/main to https://che-plugin-registry-main.surge.sh

.che-didact-guide.md, devfile.yaml, tools/build/package.json
Providing a devfile for dogfooding: build and run the plugin registry in Che.
Also provide a didact guide to tell the contributor what to do.
dogfooding
The devfile won't work in che.openshift.io because of storage limitation.
For RedHatter, it could be tested with the dogfooding instance.
`https://<che-host>/factory?url=https%3A//github.com/sunix/che-plugin-registry/tree/builder-base-dockerfile`
Works in devsandbox:
https://codeready-codeready-workspaces-operator.apps.sandbox.x8i5.p1.openshiftapps.com/factory?url=https%3A//github.com/sunix/che-plugin-registry/tree/builder-base-dockerfile
Reviewers, please comment how you tested the PR …
=> chore(dogfooding): Add a devfile.yaml to build, run and test the plugin registry in Che

che-plugins.yaml
Brings che-plugins.yaml to define components that are neither VS Code Extensions/Theia plug-ins defined in che-theia-plugins.yaml or Editors components defined in che-editors.yaml
https://github.com/eclipse/che/issues/18214#issuecomment-742396403
For now the files are not used. (like current che-editors.yaml) but you may check yaml content is valid
Change-Id: I59bf1f056875a679ea9229884ad14b8fe953c7dd
=> feat(che-plugins): As part of automation, brings che-plugins.yaml file

che-plugins.yaml, v3/plugins/eclipse/che-async-pv-plugin/nightly/meta.yaml
This image didn't had a version, now it has so we can avoid to use latest
https://github.com/eclipse/che/pull/18612
docker image is just a copy so there should not have any problem (same digest
Change-Id: I01f33fa1d4be3e8c2d53b97f8f2cf07cb429a08f
=> feat(async-plugin): Replace latest by 0.0.1 version

CONTRIBUTE.md
Document che-editors.yaml and che-plugins.yaml files
https://github.com/eclipse/che-plugin-registry/pull/777
Browse rendered MD file at https://github.com/benoitf/che-plugin-registry/blob/contributing/CONTRIBUTE.md
Change-Id: Ide12da7213f5219df0d891e9b7543e1341c6d6d8
=> feat(doc): Document che-editors.yaml and che-plugins.yaml files

che-theia-plugins.yaml
New version of plugin: debugger-for-mainframe: 1.4.0
=> debugger-for-mainframe: 1.4.0

che-theia-plugins.yaml
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
Updates the versions of both Explorer for Endevor and Zowe Explorer. 
=> Update Zowe Explorer and Explorer for Endevor

che-theia-plugins.yaml
=> Upgrade VS Code Metals, the Scala language client, to version 1.9.9

.github/workflows/release.yml
Fix release job that was producing invalid data inside the image
N/A
https://github.com/eclipse/che/issues/18727
Build the image and check for java side car image tag, it should be correct
=> fix(release): Use all history when fetching repository so it can find real sha-1 for sidecars

che-theia-plugins.yaml
=> Upgrade VS Code Language Support for Camel 0.0.30 eclipse/che#18733

che-theia-plugins.yaml
=> Upgrade VS Code Metals, the Scala language client, to version 1.9.10

che-theia-plugins.yaml
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
This PR updates vscode-yaml to 0.14.0
No associated issue
You can use this devfile:
```
metadata:
name: wksp-custom-2279z
attributes:
persistVolumes: 'false'
components:
- type: chePlugin
reference: 'https://gist.githubusercontent.com/JPinkney/74f2c84879b5cf70cc9d16d2f3bb5d41/raw/cdbe38096d1f3d2f61af62e59240123f20f66daf/test.yaml'
```
then create test.yaml. Open the settings and add:
```
"yaml.schemas": {
"kubernetes": "test.yaml"
}
```
Open up test.yaml and then try to use autocompletion and you should get some results
Reviewers, please comment how you tested the PR …
=> Update vscode-yaml to 0.14.0

devfile.yaml
plugin id of the github pr plugin has changed. updating the dogfooding devfile.
=> chore(devfile): use the new plugin id for the github pr plugin

make-release.sh
Adapts to the new `che-editors.yaml` and `che-plugins.yaml` formats instead of copying `meta.yaml` files which do not exist.
N/A
Fixes eclipse/che#18834
Run the sed commands from the `createNewPlugins` function in the terminal.
=> Adapt make-release.sh to the new che-plugins and che-editors formats

make-release.sh
Remove old references in make-release.sh
=> Remove old references in make-release.sh

make-release.sh
Add all files, when creating release commit. 
=> Fix git commit in make-release.sh

che-theia-plugins.yaml
=> Update Scala syntax for VS Code

che-theia-plugins.yaml
Signed-off-by: Sun Tan <sutan@redhat.com>
Add git history plugin https://open-vsx.org/extension/donjayamanne/githistory
The tree is a bit buggy, but it works, i managed to do some basic git manipulation from the view like, git create branch, git checkout ...
While testing the extension as part of the checks done for https://github.com/eclipse/che/issues/15390
Add to any devfile:
```yaml
- id: donjayamanne/githistory/latest
registryUrl: 'https://sunix-che-plugin-registry-extension-pack-5088a.surge.sh/v3'
```
then with the running workspace, use the command (command palette) `git: view history (git log)`
Reviewers, please …
=> feat(plugins): Add git history plugin

che-theia-plugins.yaml
=> Upgrade VS Code Metals, the Scala language client, to version 1.9.13

che-theia-plugins.yaml
Upgrade VS Code Camel K to 0.0.20
eclipse/che#18912
see https://issues.redhat.com/browse/CRW-729?focusedCommentId=14002418&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14002418
=> Upgrade VS Code Camel K to 0.0.20 eclipse/che#18912

build/dockerfiles/Dockerfile, build/dockerfiles/rhel.Dockerfile
index.json and meta.yaml should be considered as default files to display if requiring folder
https://github.com/eclipse/che/issues/18930
1. build
2. run `docker run -it --rm -p 8080:8080 quay.io/eclipse/che-plugin-registry:nightly`
3. check: `curl http://localhost:8080/v3/plugins/`
Change-Id: Ic003f2c9967f8994e8796e08e15428f9dccae92d
=> fix(.htaccess): Handle index.json and meta.yaml as directory index

che-theia-plugins.yaml
Cherry pick fixes from master.
* Temporarily remove some plugins where vsix files are missing
* Update bash-debug location instead of removing
Part of eclipse/che#18933
=> Temporarily remove some plugins where vsix files are missing (#823)

che-theia-plugins.yaml
eclipse/che#18939
increase the memory by default for VS Code Language Support for Apache Camel. The latest 0.0.30 versions requires more memory
eclipse/che#18939
=> With latest VS Code language Support for Camel, minimal memory is 350Mi

tools/build/package.json, tools/build/src/build.ts, tools/build/tests/build.spec.ts, yarn.lock
Enhance traces displayed when building registry
https://user-images.githubusercontent.com/436777/106483365-bd6c2380-64ae-11eb-9399-c6cc2f0780b6.mp4
https://github.com/eclipse/che-plugin-registry/pull/815#pullrequestreview-578269305
launch ./build.sh
you should have progress items
note: it should work fine only if you've currently cached items of downloaded vsix files (else you'll hit openvsx removal extension issue)
Change-Id: I0f3400f1b996055a84168b9b1a3c87ef49c01726
=> feat(build/report): verbose mode when building

che-editors.yaml
Fix for https://github.com/eclipse/che-plugin-registry/pull/832 that reverts cpuLimit for theia container from 1000m to 1500m.
N/A
eclipse/che#18955
The same steps as provided in linked PR: https://github.com/eclipse/che-plugin-registry/pull/832
=> Revert cpuLimit to 1500m instead of 1000m

che-theia-plugins.yaml
Signed-off-by: John Steele <programjsteele@gmail.com>
=> release version 0.0.61 of the mta plugin.

.github/workflows/release.yml
`${IMAGE}` variable is not defined
failure in build github action
Trigger build release :-)
Change-Id: I4cb690c78159f9b7e2b3c03fad9bffaba9ea4539
=> chore(release): Fix invalid IMAGE name variable

che-theia-plugins.yaml
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>
Adds latest version of the vscode-didact extension, which enables multi-tutorial window functionality and revises the method of behind-the-scenes caching used between sessions to hopefully avoid falling into the hole of https://github.com/eclipse-theia/theia/issues/8883
=> Update didact to version 0.3.1

README.md, deploy/kubernetes/che-plugin-registry/templates/configmap.yaml, deploy/kubernetes/che-plugin-registry/templates/deployment.yaml, deploy/kubernetes/che-plugin-registry/templates/ingress.yaml, deploy/kubernetes/che-plugin-registry/templates/service.yaml, deploy/openshift/che-plugin-registry.yml
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
- Add default kubernetes labels
- Specify container limits
- Add securityContext:
```
securityContext:
capabilities:
drop:
- ALL
```
https://github.com/eclipse/che/issues/18357
=> Add default kubernetes labels

che-theia-plugins.yaml
New version of plugins: cobol-language-support 0.17.1, hlasm-language-support 0.12.0
[https://open-vsx.org/extension/BroadcomMFD/cobol-language-support/0.17.1](https://open-vsx.org/extension/BroadcomMFD/cobol-language-support/0.17.1)
[https://open-vsx.org/extension/BroadcomMFD/hlasm-language-support/0.12.0](https://open-vsx.org/extension/BroadcomMFD/hlasm-language-support/0.12.0)
=> Hlasm 0.12.0 cobol 0.17.1

cico_functions.sh
Follow up on https://github.com/eclipse/che-plugin-registry/pull/839
Fixup for the tag/push logic
=> Fixing the tag/push logic

che-theia-plugins.yaml
This is a temporary workaround for https://github.com/eclipse/che/issues/17492. Where openshift connector cannot be download by the plugin broker in some environment.
Download from openvsix took 5 secs versus 1m30s from download.jboss.org
workaround for https://github.com/eclipse/che/issues/17492
Environment where this is reproducible: Openshift 4.x (For Red Hatters: RHPDS)
https://github.com/sunix/scratch-kubernetes/blob/07289cc1bd5495bdc077ed1ed2dcdf96365bcb73/devfile.yaml#L75-L77
```yaml
- id: redhat/vscode-openshift-connector/latest
registryUrl: 'https://sunix-plugin-registry-openshift-con-fh0ka.surge.sh/v3'
```
The same file is dowloaded in 5secs in openvsix.org versus 1m30s in download.jboss.org …
=> fix(openshift-connector): speed up download of extension by using openvsix.org url

che-theia-plugins.yaml
Signed-off-by: John Steele <programjsteele@gmail.com>
=> release version 0.0.63 of the mta plugin.

che-theia-plugins.yaml
Update the `vscode-shellcheck` extension to the latest version, which fixes warnings about shellcheck binary locations. Implicitly installed shellcheck binaries will now be detected.
Fixes eclipse/che#18924
=> Update shellcheck plugin

.github/workflows/image-build-pr-check.yml
This reverts commit ba7cb6541e266ee81558a3ace1eb1030e80cb794.
https://github.com/eclipse/che-plugin-registry/pull/855
=> chore(build): [revert] Do not build plugin-registry image PR check when only sidecar files are modified

tools/build/src/registry/registry-helper.ts, tools/build/tests/registry/registry-helper.spec.ts
skip digest when referencing a sidecar from the current sha-1 commit 
PR are failing when modifying sidecar folder
see if build will be fine as it includes a copyright change in sidecar folder
=> feat(digest): skip digest when referencing a sidecar from the current sha-1 commit 

che-theia-plugins.yaml
Introduces
- [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)
- [Mermaid Markdown Syntax Highlighting](https://marketplace.visualstudio.com/items?itemName=bpruitt-goddard.mermaid-markdown-syntax-highlighting)
https://github.com/eclipse/che/issues/18750
Create a workspace with this devfile
```
metadata:
name: mermaid-plugin
projects:
- name: vscode-markdown-mermaid
source:
type: git
location: https://github.com/mjbvz/vscode-markdown-mermaid.git
branch: master
components:
-
reference: https://pr-check-856-alpine-che-plugin-registry.surge.sh/v3/plugins/bierner/markdown-mermaid/latest/meta.yaml
``` …
=> Mermaid markdown preview and syntax highlight

tools/build/src/registry/registry-helper.ts, tools/build/tests/registry/registry-helper.spec.ts
Do not grab digest when it's about sidecar that we're modifying
https://github.com/eclipse/che-plugin-registry/pull/859
I've applied the changes to Sun's PR about lombok and it did pass
https://github.com/eclipse/che-plugin-registry/actions/runs/598938063
=> chore(build): Do not use rev-parse HEAD as on github we may have some extra HEAD on PR

sidecars/camelk/Dockerfile
the Camel K binary used by default is newer (upgrade to 1.3.1)
=> Upgrade VS Code Camel to 0.0.21 eclipse/che#19123

sidecars/plantuml/Dockerfile, sidecars/plantuml/PLATFORMS, sidecars/plantuml/etc/entrypoint.sh
plantuml sidecar as first step for adding the plantUML extension to che.
=> add plantUML sidecar

che-plugins.yaml, che-theia-plugins.yaml
=> add plantUML to che-plugins yaml

che-theia-plugins.yaml
=> Upgrade VS Code Camel Language support to 0.0.31 eclipse/che#19180

tools/build/src/che-theia-plugin/che-theia-plugins-meta-yaml-generator.ts, tools/build/src/che-theia-plugin/che-theia-plugins-yaml.ts, tools/build/src/meta-yaml/meta-yaml-plugin-info.ts, tools/build/tests/che-theia-plugin/che-theia-plugins-meta-yaml-generator.spec.ts
Add support for args/command in sidecar image definition of che-theia-plugins.yaml file
Fixes https://github.com/eclipse/che/issues/19231
Add in che-theia-plugins.yaml file a `command` or `args` entry, it should be reflected in generated meta.yaml
note: a test covers this usecase
Change-Id: I201973f02c1646137027e1a822318af328d6a60d
=> feat(args/command): Add support for args/command for sidecar image of che-theia-plugins.yaml file

CONTRIBUTE.md
Update CONTRIBUTE.md to show the new args and command fields for `che-theia-plugins.yaml`.
N/A
Part of eclipse/che#19231
=> Document args and command fields

che-theia-plugins.yaml
Updates asciidoctor-vscode to version 2.8.7.
N/A
No issue at this time.
=> Update asciidoctor-vscode to 2.8.7

che-theia-plugins.yaml
Update the vsix links for shellcheck and vale plugins to point to the vsix files we built ourselves in https://github.com/redhat-developer/codeready-workspaces-vscode-extensions
N/A
N/A
- [ x [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
=> Update vsix links to CRW built versions

.github/workflows/release.yml, make-release.sh
Change the logic of make-release.sh, so that it can be called from the release workflow.
=> Use make-release.sh in the release workflow

che-editors.yaml, make-release.sh
Add collocated machine-exec to che-theia editor
https://github.com/eclipse/che/issues/19215
Deploy Eclipse che-theia component and you should see two machine-exec components
Change-Id: Idef22f4e77d44cbb15ece4fd327cecafb3726104
=> feat(che-theia): Add collocated machine exec to che-theia editor

che-theia-plugins.yaml
Update the sonarlint plugin version from 1.16.0 to 1.20.1
fixes https://github.com/eclipse/che/issues/19156
=> Upgrade the sonarlint plugin to 1.20.1

che-editors.yaml, che-plugins.yaml
=> [release] Add 7.27.1 plugins in master

tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts, tools/build/src/meta-yaml/meta-yaml-writer.ts, tools/build/tests/_data/meta/che-theia-meta.yaml, tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Handle more than one container in meta.yaml with endpoint for devfile v2 export
fixes https://github.com/eclipse/che/issues/19301
Look at generated devfile.yaml for che-theia 
Change-Id: Ia34ea070f5a8ae8f94cb32b1566d0b4535690b58
=> fix(devfile): Handle more than one container in meta.yaml file for endpoints

make-release.sh
Remove `REGISTRY` and `ORGANIZATION` variables to unblock shellcheck PR check.
N/A
N/A
Shellcheck should pass on this PR.
=> Remove unused vars to fix shellcheck

che-theia-plugins.yaml
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>
Updates the che registry to the latest version of Didact 0.3.2. 
This update includes the change to fix (https://github.com/redhat-developer/vscode-didact/issues/415) for @sunix 
Open the Didact demo from the Didact Tutorials view and verify that there is no longer a footer at the bottom showing the didact version (easiest check to see if it's the correct version in this case)
=> updating didact to 0.3.2 in the che registry

tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts, tools/build/tests/_data/meta/container-minimal-endpoint.yaml, tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Provide command and args parameters as expected
https://github.com/eclipse/che/issues/19373
Look at generated devfile.yaml or new unit tests
Change-Id: I9cff7cd4e18e9e0cc73aab18792cbd050095f25c
=> fix(devfile): Provide command and args as expected

.github/workflows/release.yml
=> Fix release.yaml formatting

che-theia-plugins.yaml
to be tested
Update VS code Camel K to 0.0.22 
=> Update VS code Camel K to 0.0.22 eclipse/che#19360

che-editors.yaml, tools/build/tests/_data/meta/che-theia-meta.yaml, tools/build/tests/_data/meta/no-container.yaml, tools/build/tests/editor/che-editor-analyzer.spec.ts, tools/build/tests/editor/che-editor-meta-yaml-generator.spec.ts
Updates Che-Theia repository location.
https://github.com/eclipse/che/issues/19391
=> Update Che-Theia repository location

sidecars/vale/Dockerfile
Update the vale version in the sidecar image
https://github.com/eclipse/che/issues/19289
1. Go to `sidecars/vale` directory.
2. Run `docker build .` 
3. Run `docker run -it <image id from the previous command> sh`
4. Run `vale --v`
See: the vale version is updated to `v2.10.2`
=> Update the vale version in the sidecar image

sidecars/kubernetes-tooling/Dockerfile
Closes: https://github.com/eclipse/che/issues/19488
prior steps to upgrading the kubernetes tooling vsix and then the same with tekton.
=> upgrade minikube in kubernetes-tooling sidecar

che-theia-plugins.yaml
=> Upgrade VS Code Camel K to 0.0.23 eclipse/che#19531

sidecars/camelk/Dockerfile
=> Upgrade Camel K to 1.3.2 in sidecar for VS Code Camel K 0.0.3

sidecars/tekton/Dockerfile
Signed-off-by: Esteban Mañaricua<emanaricua@gmail.com>
Closes: https://github.com/eclipse/che/issues/19498
Signed-off-by: Esteban Mañaricua<emanaricua@gmail.com>
=> upgrade tekton sidecar

.github/workflows/release.yml, build/dev/publish-devfile-registry-to-gh-pages.sh
When releasing, publishing che-plugin-registry to github pages
Fix https://github.com/eclipse/che/issues/19268
I have tested this on my fork with a copy of release.yml without the release steps: https://github.com/sunix/che-plugin-registry/commit/f35cf908685aeebdb248ef10d922045c0f22d767
And triggered manually with versions as input:
the results:
- https://sunix.github.io/che-plugin-registry/7.27.0/v3/plugins/
- https://sunix.github.io/che-plugin-registry/7.28.1/v3/plugins/
- https://sunix.github.io/che-plugin-registry/7.28.2/v3/plugins/
Also how the git history would look like in the gh-pages branch: https://github.com/sunix/che-plugin-registry/commits/gh-pages
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-tem …
=> feat(publish-release): publishing releases to gh-pages

che-theia-plugins.yaml
New version of plugin: debugger-for-mainframe: 1.5.0
https://open-vsx.org/extension/BroadcomMFD/debugger-for-mainframe/1.5.0
=> debugger-for-mainframe 1.5.0

.github/workflows/happy-path.yaml
happy path are not working with minikube 1.19.0 which is installed by default on github actions runner
here it changes the default
https://github.com/eclipse/che/issues/19602
look if there is a green happy path test with github action
Change-Id: Ibc835c9e1120f1fd65a9b7544b9268f098d0d90c
=> chore(happy-path): stick minikube to a working version

CONTRIBUTE.md
Describe GitHub pages publishing as well as version specific publishing.
N/A
N/A
N/A
=> Update CONTRIBUTE.md with latest publishing info

sidecars/shellcheck/Dockerfile
Adds a proper home dir to the shellcheck sidecar
The "shellcheck" plugin doesn't work #19376
Repeate the scenario from the issue with this plugin version:
https://gist.githubusercontent.com/tsmaeder/5c49f48981d4f87ce38fc8d57174364a/raw/4c21f87ca7d7c3188467972f427e139b44ce7ad9/shellcheck.yml
=> Add home dir

README.md
fix the codecov badge
N/A
Click on the badge
Change-Id: I833cb0844c18707f136f9391613380d54095e660
=> chore(codecov): Fix link for README button

che-theia-plugins.yaml
Add VS Code commons extension
related to https://github.com/eclipse/che/issues/19361
check extension is published in the registry (today no extension is using it directly in the current plugin registry)
Change-Id: I068a10c6f0b006948fcacd2fd92750a5ef586be7
=> feat(redhat.commons): Add VS Code commons extension

che-theia-plugins.yaml
Upgrade VS Code Language Support for Camel to 0.0.32
=> Upgrade VS Code Language Support for Camel to 0.0.32 eclipse/che#19740

che-theia-plugins.yaml
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>
Updates the vscode-didact entry in the Che plugin registry to the 0.4.0 release
New functionality as described in https://github.com/redhat-developer/vscode-didact/releases/tag/0.4.0
Open a workspace with Didact installed and find the Didact Tutorials view in the Explorer activity. Look at the HelloWorld example and see if it has three steps when expanded.
=> update didact to 0.4.0 release

sidecars/camelk/Dockerfile
=> Upgrade Camel K Cli in sidecar to 1.4.0 eclipse/che#19745

tools/build/src/registry/registry-helper.ts
fix build of the images using docker.io
Error 406 was reported
Check that build is working
Change-Id: I91bb681187d5e5e53d6fdca28abf90a652ea3141
=> chore(build/registry): Use correct accept field for grabbing token on docker.io registry

tools/build/src/registry/registry-helper.ts
backport https://github.com/eclipse-che/che-plugin-registry/pull/947 in 7.29.x branch
Unable to grab docker.io token
build the registry
Change-Id: I91bb681187d5e5e53d6fdca28abf90a652ea3141
=> fix(registry): Use correct accept field for grabbing token on docker.io registry

che-theia-plugins.yaml
=> Upgrade VS Code Camel K to 0.0.24 eclipse/che#19745

che-editors.yaml
Limits CPU and memory usage for `che-machine-exec` and `remote-runtime-injector`.
https://github.com/eclipse/che/issues/16685
=> CPU and Memory limits for che-machine-exec and remote-runtime-injector

che-theia-plugins.yaml
Add vscode-xml's server binary as a trusted setting to avoid warnings about untrusted binaries.
Fixes eclipse/che#19662
Run vscode-xml with the meta.yaml from this PR and try it.
=> Add vscode-xml's server binary as a trusted setting

sidecars/ansible/Dockerfile, sidecars/ansible/PLATFORMS, sidecars/ansible/etc/entrypoint.sh
Introduce a sidecar image based on ansible image
related to https://github.com/eclipse/che/issues/11877
Look at the image being built and check that ansible is installed inside and that the linter is also installed
Change-Id: Ifc1af877a797fd1b0043ed3574a5adac0e204e1d
=> feat(ansible): Add a sidecar with Ansible tooling installed inside

che-theia-plugins.yaml
=> Upgrade VS Code Language support for Camel to 0.0.33 eclipse/che#19818

CONTRIBUTE.md, che-editors.yaml, tools/build/src/common/endpoints-helper.ts, tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts, tools/build/tests/common/endpoints-helper.spec.ts, tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Adapt devfile to endpoint type change https://github.com/devfile/devworkspace-operator/issues/399
:warning: it should be merged in sync with https://github.com/devfile/devworkspace-operator/pull/430
https://github.com/devfile/devworkspace-operator/issues/399
=> Adapt devfile to endpoint type change

che-theia-plugins.yaml
Enable Jupyter Notebook support by mounting the venv volume
- to be shared with dev containers
- this venv contains dependencies for jupyter see https://github.com/eclipse-che/che-plugin-registry/pull/958
https://youtu.be/FPZa5jc8sYE
https://github.com/eclipse/che/issues/16818
second PR following https://github.com/eclipse-che/che-plugin-registry/pull/958
```yaml
metadata:
generateName: python-jupyter-
projects:
- name: jupyter-hello-world1
source:
startPoint: master
location: 'https://github.com/chasbecker/TextAnalysis.git'
type: git
components:
- id: ms-python/python/latest
registryUrl: 'https://sunix-che-plugin-registry-dev-i1viq.surge.sh/v3'
- mountSources: true
memoryLimit: 512Mi
volumes:
- name: venv
containerPath: /home/user/.venv …
```
=> feat(python): Enable Jupyter Notebook support

che-theia-plugins.yaml
upgrade to new version
nota: a new menu for debugging is available on right-click on deployed Integration. it won't be working as VS Code Java debug is missing from the stack/dependencies.
=> Upgrade VS Code Camel K 0.0.25 eclipse/che#19811

che-theia-plugins.yaml
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
Update the version of Explorer for Endevor to the new version
=> Update Explorer for Endevor Version to 0.12.1

.github/workflows/typescript-publish.yml, package.json, tools/automation/package.json, tools/build/package.json
Publish as a library `@eclipse-che/plugin-registry-generator` to npmjs
https://github.com/eclipse/che/issues/19741
we must wait the trigger when PR is merged but you can try the commands of the script and append `--dry-run` on npm publish script
Change-Id: I1ca207a0a8256d702b906ac149b9517b250c590b
=> chore(publish): Publish to npmjs the generator library at every push to the main branch

.ci/openshift-ci/plugins-test-pod.yaml
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>
Change test image for the openshift-ci jobs
Issue: https://github.com/eclipse/che/issues/19899
=> test(nightly/pr-check): Change test image for the openshift-ci jobs

tools/build/src/meta-yaml/meta-yaml-writer.ts, tools/build/tests/meta-yaml/meta-yaml-writer.spec.ts
Applies fixup https://github.com/eclipse-che/che-plugin-registry/pull/968 to 7.30.x
https://github.com/eclipse/che/issues/19771
See original PR https://github.com/eclipse-che/che-plugin-registry/pull/968
=> fix: Icon path must be relative to plugin registry root folder

.ci/openshift-ci/plugins-test-pod.yaml
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>
Change used tag for the che-e2e image
Issue: https://github.com/eclipse/che/issues/19903
=> test(nightly): Change used tag for the che-e2e image

.ci/openshift-ci/common-functions.sh, .ci/openshift-ci/nightly-test.sh
… because of changed test name.
The "che-plugin-registry" nightly openshift-ci job fails because of changed test name
Issue: https://github.com/eclipse/che/issues/19940
=> test(nightly): The "che-plugin-registry" nightly openshift-ci job fails because of changed test name

che-editors.yaml, tools/build/src/common/container-helper.ts, tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts, tools/build/src/meta-yaml/meta-yaml-writer.ts, tools/build/tests/_data/meta/machine-exec-plugin-meta.yaml, tools/build/tests/meta-yaml/meta-yaml-writer.spec.ts
Add recommended kubernetes labels on che-theia editor components
it will allow to get more details on the source of components in kubernetes resources
https://github.com/eclipse/che/issues/19951
Look at the generated devfile.yaml for che-theia: should include the labels
meta.yaml shouldn't have those
Change-Id: I5c3b880465eef487712839416a13457be384853c
=> feat(metadata): Add recommended kubernetes labels on che-theia editor components

che-theia-plugins.yaml
=> fix(microprofile): fix the repository url of vscode-microprofile

tools/build/README.md, tools/build/package.json, tools/build/src/inversify-binding.ts, tools/build/tests/inversify-binding.spec.ts, yarn.lock
When publishing it as a npm package, some dependencies are not found because they're flagged as dev dependencies instead.
Also it introduce a new flag `--root-folder:<path>` to be able to provide the root folder instead of assuming root folder is at relative `../../` from the tools/build folder
https://github.com/eclipse/che/issues/19741
publish the package on a private repository and install it elsewhere.
You should be able to make it work with for example codeready workspaces repository
with a command like `node node_modules/..path-to-downloaded-npm-package/lib/entrypoint.js --root-folder:/projects/crw/dependencies/che-plugin-registry/ --output-folder:$(pwd)/output --skip-digest-generation:true` …
=> chore(npm): fix dependencies when using it as a published npm package

che-theia-plugins.yaml
Updates the version of Zowe Explorer to 1.15.1
N/A
=> Zowe Explorer update to 1.15.1

sidecars/java8/Dockerfile
Exactly similar to this  https://github.com/eclipse-che/che-plugin-registry/pull/871 but for java8
=> fix(java8-sidecar): Moving lombok.jar to a generic location

che-theia-plugins.yaml
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
Updates Zowe Explorer to its latest version v1.16.0
=> Update Zowe Explorer latest release

.ci/digest-validation-pr.sh, .github/workflows/build-jobs.yml, .github/workflows/next-build.yml, .github/workflows/pr-checks.yml, .github/workflows/publish-plugin-report.yaml, .github/workflows/sidecar-build-push.yaml, .github/workflows/typescript-publish.yml, CONTRIBUTE.md, make-release.sh, tools/automation/package.json, tools/build/package.json
Renames instances of master to main (where applicable).
Part of eclipse/che#19968
Ensure nothing is broken :laughing: 
=> chore(branches): rename master to main

che-theia-plugins.yaml
New version of plugin: cobol-language-support 0.19.0
[https://open-vsx.org/extension/BroadcomMFD/cobol-language-support/0.19.0](https://open-vsx.org/extension/BroadcomMFD/cobol-language-support/0.19.0)
New version of plugin: hlasm-language-support 0.13.0
[https://open-vsx.org/extension/BroadcomMFD/hlasm-language-support/0.13.0](https://open-vsx.org/extension/BroadcomMFD/hlasm-language-support/0.13.0)
Introduced new plugin: COBOL Control Flow 0.4.0
[https://open-vsx.org/extension/BroadcomMFD/ccf/0.4.0](https://open-vsx.org/extension/BroadcomMFD/ccf/0.4.0)
Devfile note: CCF will be included into Che4z devfile in a separate PR
Reviewers, …
=> Che4z plugins update: COBOL Language Support, HLASM Language Support, COBOL Control Flow

che-theia-plugins.yaml
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
Updates the version of Explorer for Endevor in the registry
=> docs: Update version of Explorer for Endevor in the registry

che-theia-plugins.yaml
Add Terraform vsocde extension: https://github.com/4ops/vscode-language-terraform
It's enhance
=> Add Terraform vscode extension

che-theia-plugins.yaml
Signed-off-by: disaster37 <linuxworkgroup@hotmail.com>
Add 2 Logstash vsocde plugins:
- https://open-vsx.org/extension/fbaligand/vscode-logstash-editor
- https://open-vsx.org/extension/RandomChance/logstash
It's an enhance
=> Add Logstash vscode plugins

.github/workflows/happy-path.yaml
Happy path tests are failing (stuck on ingress addon)
N/A
Look at happy path tests, before it's red and now it should be green
=> test(happy-path): Use a newer minikube version

.github/workflows/release.yml, make-release.sh
For now the module is only published on every commit to main branch.
We should publish it as well for all releases
https://github.com/eclipse/che/issues/20146
cut a new release
Change-Id: I7bd53aedf541445892fad1808837674880fdc626
=> chore(publish): Publish to npmjs the build module on each release as well

.ci/openshift-ci/test.sh
Disable the 'TypescriptPlugin' test in the PR-check suite.
Right now this test fails because of known bug https://github.com/eclipse/che/issues/20075 .
As far as failing of the PR-chek job means blocking of PRs merge we need temporarily disable this test.
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>
=> test(pr-check): Disable the 'TypescriptPlugin' test in the PR-check suite

devfile.yaml
Adds registry URL for `timonwong/shellcheck` plugin to make the devfile working on [workspaces.openshift.com](url)
https://github.com/eclipse/che/issues/20125
Create a workspace
https://workspaces.openshift.com/#https://github.com/eclipse-che/che-plugin-registry/tree/dogfooding-devfile
=> chore: Add registry URL for `timonwong/shellcheck` plugin

.github/workflows/release.yml
Add the missing setup of the npm registry for publishing npm artifact
Fixes https://github.com/eclipse/che/issues/20265
Need to cut a release (but this configuration is the one that we use for publishing on every commit and it's working fine)
Change-Id: I4d6229785d3fe2b75680843c467ff1bc6a9a6793
=> chore(release): Setup npm publication

che-editors.yaml
Adds missed cpuLimit and cpuRequest into che-theia/latest ediitor.
Backported changes from https://github.com/eclipse-che/che-plugin-registry/pull/1023
https://github.com/eclipse/che/issues/20270
Check if `theia-ide` component in`eclipse/che-theia/latest` plugin contains  
```yaml
memoryLimit: 512M
cpuLimit: 1500m
cpuRequest: 100m
```
=> fix: add missed resource limits/requests for che-theia/lates (#1023)

che-theia-plugins.yaml, sidecars/go/Dockerfile
Signed-off-by: disaster37 <linuxworkgroup@hotmail.com>
1. Upgrade golang sidecard to golang 1.16.6
2. Upgrade vscode-plugin to 0.26.0
=> feat: Upgrade golang container and vscode-go plugin

.github/workflows/release.yml
Backport https://github.com/eclipse-che/che-plugin-registry/pull/1021 to 7.34.x
https://github.com/eclipse/che/issues/20265
Change-Id: I4d6229785d3fe2b75680843c467ff1bc6a9a6793
=> chore(release): Setup npm publication (#1021)

che-theia-plugins.yaml
chore: bug: che-openshift-authentication-plugin-0.0.1.vsix is 404'd - move up to 0.0.2 release
Change-Id: I58771e485559960a39e488ee0bf2a8abcd249103
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: bug: che-openshift-authentication-plugin-0.0.1.vsix is 404'd - move up to 0.0.2 release

.ci/openshift-ci/build/Dockerfile, build/dockerfiles/entrypoint.sh, build/dockerfiles/test_entrypoint.sh
This is fixing https://github.com/eclipse-che/che-plugin-registry/pull/485 for devworkspace.
Devworkspaces not only include meta.yaml files but also devfile.yaml in the plugin registry.
N/A
Backported from https://github.com/redhat-developer/codeready-workspaces/pull/581
N/A
=> fix(entrypoint): Should replace image references in che-machine-exec-plugin devfile.yaml and theia-ide devfile.yaml with RELATED_IMAGE env vars

build/dockerfiles/entrypoint.sh, build/dockerfiles/test_entrypoint.sh
Check all che-theia-plugin.yaml files and replace tag with digest in the image description.
N/A
CRW issue https://issues.redhat.com/browse/CRW-2247
N/A
=> fix: replace tag with digest in che-theia-plugin.yaml files

.htaccess
When registry is private, e.g. behind oauth2-proxy, it requires cookies to access.
https://github.com/eclipse-che/che-dashboard/pull/333
Set spec.server.pluginRegistryImage to ghcr.io/mtsmfm/che-plugin-registry:d77b6899 (an image which contains this patch)
=> feat: Support CORS with credentials

che-editors.yaml
Apply urlRewriteSupported on stable version
It was applied only on next channel https://github.com/eclipse-che/che-plugin-registry/pull/1013
Fixes https://github.com/eclipse/che/issues/20451
https://github.com/eclipse/che/issues/20180
Deploy workspace with DevWorkspace engine should work
Change-Id: I0863148808315665d5edf80cc8984c1b77c07156
=> fix: apply urlRewriteSupported on stable version as well

che-theia-plugins.yaml
Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>
Updates the version of Explorer for Endevor in the registry
=> chore: Changed Zowe E4E version to 0.13.1

che-theia-plugins.yaml, sidecars/ruby/Dockerfile
1. Upgrade Ruby sidecar to the latest
2. Upgrade vscode Solargraph to the latest
=> feat: Bump Ruby and Solargraph version

.htaccess
Revert PR #1043 
See comments on https://github.com/eclipse-che/che-devfile-registry/pull/466
Change-Id: I4932956726188d20e2f750655efc43db3c3b264e
=> chore(revert): Revert PR #1043

sidecars/python/Dockerfile
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Fix problems with python plugin 
N/A
Fix https://github.com/eclipse/che/issues/20093
Try the new plugin with the default python devfile. Make sure there is no error popping up when opening a .py file and autocomplete is working and that.
=> fix(python-plugin): Fix errors when loading python plugin. Installing pylint and tools in the dedicated venv

che-editors.yaml
Part of https://github.com/eclipse-che/che-theia/pull/1222
Container `theia-endpoint-runtime-binary` now requires volume mount `/plugins`.
https://issues.redhat.com/browse/CRW-1731
See test section in: https://github.com/eclipse-che/che-theia/pull/1222
=> feat: Add volume mount to the runtime binary container

tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts, tools/build/tests/_data/meta/che-theia-meta-with-multiple-volumes.yaml, tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Back port of https://github.com/eclipse-che/che-plugin-registry/pull/1058
https://github.com/eclipse/che/issues/20545
=> Filter identical volume mounts in components list

che-theia-plugins.yaml
1. Set `spec.server.pluginRegistryImage` `ghcr.io/mtsmfm/che-plugin-registry:ac5fd314`
2. Add plugin
```yaml
...
components:
- id: stylelint/vscode-stylelint/latest
````
=> feat: Add vscode-stylelint

.github/workflows/publish-content-push-main.yml
Updates workflow for publishing content from main branch. 
The content should be published when **Next Build/Publish** workflow will be completed.
https://github.com/eclipse/che/issues/20473
=> fix: update workflow to publish content from main

.github/workflows/release.yml
Add option to republish the release
workaround for https://github.com/eclipse/che/issues/20526
=> fix: Add option to republish the release

.github/workflows/release.yml, make-release.sh
- mattermost release message will now properly append their completed steps
- use semantic message in commits
=> fix: fix messages in the release script

che-theia-plugins.yaml
Update openshift connector plugin to 0.2.9
https://issues.redhat.com/browse/CRW-1733
Check the updated version of the openshift plugin in the plugin-registry page.
=> Update openshift connector plugin to 0.2.9

che-editors.yaml
Add default idle timeout parameter to machine exec run command to shutdown workspace after 15 minutes of idling.
Part of https://github.com/eclipse-che/che-theia/pull/1239
fixes https://github.com/eclipse/che/issues/20460
Steps to reproduce provided in the following PR: https://github.com/eclipse-che/che-theia/pull/1239
=> Add idle timeout parameter to machine exec

che-theia-plugins.yaml
Switches to vscode-xml plugin to 0.17.0
https://github.com/eclipse/che/issues/20094
- build plugin registry by hands
- use built registry when deploying Che
```
chectl server:deploy \
--installer=operator \
--platform=minikube \
--che-operator-cr-patch-yaml="patch.yaml"
```
`patch.yaml` content
```
spec:
server:
pluginRegistryImage: quay.io/vgulyy/che-plugin-registry:vscode-xml
```
- create a workspace using the devfile
```
metadata:
name: xml-plugin-test
projects:
- name: nodejs-web-app
source:
location: 'https://github.com/che-samples/web-nodejs-sample.git'
branch: che-qe-tests
type: git
components:
- id: redhat/vscode-xml/latest
``` …
=> chore(vscode-xml): bump XML plugin to 0.17.0

che-theia-plugins.yaml
Update the openshift authentication tool to 0.0.3 for the openshift plugin sidecar.
https://issues.redhat.com/browse/CRW-2440
Start a workspace with openshift connector plugin.
=> fix: Update the openshift authentication tool to 0.0.3

che-theia-plugins.yaml
Signed-off-by: Nikolai Imbirev <nikolay.imbirev@broadcom.com>
Updates the version of Explorer for Endevor in the registry
=> Update che-theia plugin registry with e4e 0.13.2

che-theia-plugins.yaml
Update the GitHub Pull Request plugin to 0.21.1 which uses `registerFileDecorationProvider` instead of previous `registerDecorationProvider` plugin API method.
https://github.com/eclipse/che/issues/20689
Open a workspace with the GitHub PR plugin
See: no errors appear
=> chore: Update the GitHub PR plugin to 0.21.1

.github/CODEOWNERS
=> chore: remove @sunix from codeowners

che-theia-plugins.yaml
Signed-off-by: Roman Kupriyanov <roman.kupriyanov@broadcom.com>
=> Update VS Code extension che4z-explorer-for-endevor to v0.14.0

che-theia-plugins.yaml
Adds free-omnisharp-vscode vscode plugin https://open-vsx.org/extension/muhammad-sammy/csharp
https://github.com/eclipse/che/issues/19306
=> chore: add free-omnisharp-vscode-plugin

che-theia-plugins.yaml
Signed-off-by: sideeffffect ondra.pelech@gmail.com
/cc @svor 
=> chore: Upgrade VS Code Metals, the Scala language client, to version 1.10.15

che-editors.yaml
Introduce Code OSS / che-code with next channel
https://github.com/eclipse/che/issues/20505
N/A
Change-Id: Ib0adacac332e018700c1a9ee789e319a60b84b10
=> feat: introduce next/insiders channel for Code OSS

che-theia-plugins.yaml
=> Deprecate VS Code wsdl2rest

che-theia-plugins.yaml
=> Upgrade VS Code Language support for Camel to 0.1.1

sidecars/go/Dockerfile
=> (chore) Bump the golang sidecar to 1.17.4.

build/dockerfiles/rhel.Dockerfile
Signed-off-by: Mykhailo Kuznietsov mkuznets@redhat.com
=> chore: Update from ubi8/httpd-24:1-160 to ubi8/httpd-24:1-161

che-theia-plugins.yaml
Upgrade VS Code language support for Camel to v0.1.3
It fixes https://github.com/camel-tooling/camel-lsp-client-vscode/issues/836
https://github.com/camel-tooling/camel-lsp-client-vscode/issues/836
I've checked by using this version in the booster getting started example and it solved the issue
Change-Id: I42e1aad8f67ca75a5ce73b33d510f89caea39f6a
=> feat: Upgrade VS Code language support for Camel to v0.1.3

che-theia-plugins.yaml
Adds sidecar information for openshift-auth plugin. This fix is also needed to merge plugins in one sidecar.
https://github.com/eclipse/che/issues/20915
che-theia-openshift-auth should contain the information about sidecar.
=> feat: add sidecar for che-theia-openshift-auth plugin

che-theia-plugins.yaml
Increases limit value of cpu for java and quarkus sidecars
N/A
https://github.com/eclipse/che/issues/20769
Check the content of java and quarkus plugins, the value of cpuLimit should be 800m
=> feat: increase cpu limit for java and quarkus sidecars

sidecars/rust/Dockerfile
Uses Rust 1.57 as the sidecar base-image
eclipse/che#20952
- cd sidecars/rust
- docker build -t tmp .
- docker run --rm -it tmp /bin/bash
- cargo --version
And watch result `cargo 1.57.0 (b2e52d7ca 2021-10-21)`
=> chore(rust): Use Rust 1.57.

.github/dependabot.yml, .github/workflows/happy-path.yaml, .github/workflows/image-build-pr-check.yml, .github/workflows/next-build.yml, .github/workflows/pr-checks.yml, .github/workflows/publish-content-push-main.yml, .github/workflows/publish-plugin-report.yaml, .github/workflows/release.yml, .github/workflows/resource-limits-pr-check.yaml, .github/workflows/typescript-pr-check.yml, .github/workflows/typescript-publish.yml
Update some version of actions + add dependabot configuration to automate it
Fixes https://github.com/eclipse-che/che-plugin-registry/issues/1113
Fixes https://github.com/eclipse-che/che-plugin-registry/issues/1112
Check github actions
=> chore: update github actions and automate it with dependabot

deploy/kubernetes/che-plugin-registry/templates/deployment.yaml, deploy/kubernetes/che-plugin-registry/values.yaml
Enable to set `affinity:` via Helm.
No issue related.
- Modify values.yaml.
- helm lint
=> feat:[helm] Enable to set `affinity:`.

.github/workflows/dependabot-pr-workaround.yml
dependabot is not handling Yarn V2 directly, so need to amend the dependabot PR
https://github.com/dependabot/dependabot-core/issues/1297
Check dependabot PR
Change-Id: I861b169a7836bdcae8f37810a862fc7c91211472
=> chore: workaround to handle dependabot Yarn2 PR

che-theia-plugins.yaml
Signed-off-by: Roman Kupriyanov <roman.kupriyanov@broadcom.com>
=> feat: Update VS Code extension che4z-explorer-for-endevor to v0.14.1

.github/workflows/dependabot-pr-workaround.yml
Use che-bot identity to add extra commits to dependabot issue
https://github.com/eclipse-che/che-plugin-registry/actions/workflows/dependabot-pr-workaround.yml
I've checked it locally and was able to push https://github.com/eclipse-che/che-plugin-registry/tree/foo branch
Change-Id: Ic7111a0b892cd77b5127ac428a22cc527982d958
=> chore: use che-bot identity to commit fixes for dependabot

.github/workflows/dependabot-pr-workaround.yml
Change the logic as it's always failing when pushing changes for dependabot
Dependabot action
Manually it works but then inside github action it was failing
=> chore: fix github authentication when pushing fixes

.github/workflows/dependabot-pr-workaround.yml
Trying to fix dependabot PRs
https://github.com/eclipse-che/che-plugin-registry/actions/workflows/dependabot-pr-workaround.yml
=> chore: fix dependabot action

.github/workflows/dependabot-pr-workaround.yml
Trying to fix dependabot PRs
https://github.com/eclipse-che/che-plugin-registry/actions/workflows/dependabot-pr-workaround.yml
=> chore: try to fix dependabot PR check №2

.ci/openshift-ci/test.sh
disable openshift-ci test as it's not working with DevWorkspaces
https://github.com/eclipse/che/issues/20985
Check should be green (as it's disabled)
=> chore: disable unit tests using OpenShift CI

.github/workflows/dependabot-pr-workaround.yml
Amend the dependabot PR by reworking the yarn.lock file
All dependabot PRs are failing right now
I've tested it using a fork
https://github.com/benoitf/dpndbt/actions/runs/1667161247
Change-Id: I9091107e6d726075ead238fbe683064ce298bef9
=> chore: fix the workflow to amend dependabot PR

che-editors.yaml
This changes proposal provides updated editor configuration for `che-idea` and `che-pycharm` editors.
https://github.com/eclipse/che/issues/20863
For IntelliJ IDEA Community Edition create workspace from the following repository: https://github.com/vzhukovs/che-idea
For PyCharm Community Edition create workspace from the following repository: https://github.com/vzhukovs/che-pycharm
=> Update che-idea and che-pycharm editor configuration

che-theia-plugins.yaml
Since https://github.com/eclipse-che/che-dashboard/pull/431 is merged, the openshift authentication-plugin is redundant. 
https://github.com/eclipse/che/issues/20857
Check the openshift-connector plugin's meta.yaml, the extensions list mustn't contain the authentication plugin.
=> Exclude authentication-plugin from the openshift-connector extensions list

che-theia-plugins.yaml
Signed-off-by: sideeffffect ondra.pelech@gmail.com
=> chore: Upgrade VS Code Metals, the Scala language client, to version 1.11.1

che-editors.yaml
This changes proposal updates the editor configuration by bumping image tag, that contains `yq` utility.
N/A
fixes https://github.com/eclipse/che/issues/21003
Steps to check provided in https://github.com/che-incubator/jetbrains-editor-images/pull/75
=> Update image tag to include yq tool to runtime container

che-editors.yaml
Add extra ports to redirect user traffic
https://github.com/eclipse/che/issues/20500
Check that extra routes are added
Change-Id: I74628e3854f8eacaa5ed9ccff65bbccace1a1f55
=> feat: add redirect ports for che-code

che-theia-plugins.yaml
Signed-off-by: Nikolai Imbirev <nikolay.imbirev@broadcom.com>
=> Update e4e plugin to 0.14.2 version

build/dockerfiles/Dockerfile, build/dockerfiles/rhel.Dockerfile
This will aide in downstream projects to consume much easier and include their own plugins.
@nickboldt please review.
Updates Dockerfile to copy multiple plugins and images.
N/A
N/A
N/A
=> feat: An update to copy all plugins and images

che-editors.yaml
Current changes proposal provides adjusted limits for cpu and memory resources to get the best performance for JetBrains related editors according to the following docs https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#terms-of-service_che
N/A
https://github.com/eclipse/che/issues/21108
For testing there was used dogfooding instance and the following repository with the provided values in the current PR: https://github.com/vzhukovs/limits
=> Adjust cpu and memory limits for better performance of JetBrains editors

.ci/openshift-ci/test.sh
Uncomment test starting in test.sh.
https://github.com/eclipse/che/issues/20985
=> test: Start TS plugin tests as PR checker

che-theia-plugins.yaml
Signed-off-by: Nikolai Imbirev <nikolay.imbirev@broadcom.com>
=> Update Che4z explorer for endevor VS Code extension to v1.0.0

.ci/openshift-ci/nightly-test.sh
Fixed tests in PR: https://github.com/eclipse/che/pull/21269 are uncommented in nightly-test.sh file
=> tests: Added JavaPlugin and PythonPluign tests to nightly-tests

che-theia-plugins.yaml
Signed-off-by: Roman Kupriyanov <roman.kupriyanov@broadcom.com>
=> Upgrade che4z-explorer-for-endevor VS Code extension to v1.0.1

.ci/openshift-ci/nightly-test.sh
=> tests: fix shellcheck errors

che-editors.yaml
Use fresh UDI image which contains `e2fsprogs` with IntelliJ IDEA Community Edition 2022 and PyCharm Community Edition 2022.
https://github.com/eclipse/che/issues/21007
Create the workspace from the following repository: https://github.com/vzhukovs/demo-repository/tree/che-idea-latest
=> chore: use fresh udi image with jetbrains editor images

che-theia-plugins.yaml
Signed-off-by: Roman Kupriyanov <roman.kupriyanov@broadcom.com>
Updates the version Explorer for Endevor in the registry.
Explorer for Endevor v1.1.1 change log:
- Added the function that tests connections to Endevor services in the Endevor profiles creation step.
- Support for v1 Endevor REST API (Endevor version 18.0).
- Added the override signout capability for the signout feature.
- Fixed the issue that prevented you from using the default HTTPS port value in the Endevor profiles creation step.
=> Update VS Code extension che4z-explorer-for-endevor to v1.1.1

che-theia-plugins.yaml
the VS Code extension is deprecated. it was marked as deprecated in Che
in 7.41 version.
fixes eclipse/che#21457
=> Remove wsdl2rest

che-theia-plugins.yaml
=> Mark VS Code Didact as deprecated

deploy/kubernetes/che-plugin-registry/templates/ingress.yaml
Deploys `networking.k8s.io/v1` version of Ingress if the K8s cluster accepts.
None.
Checked by Kubeconform.
```
helm template deploy/kubernetes/che-plugin-registry | kubeconform -
```
My environment is:
```
$ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", …
```
=> chore: Enable to deploy 1.22 clusters with the Helm chart.

che-editors.yaml
Adds missed attributes into che-machine-exec component of che-theia:latest editor
=> chore: add missed attributes into che-machine-exec:latest of che-theia editor

che-editors.yaml
Increases idle timeout to 30 minutes in workspaces that use Theia editor
https://issues.redhat.com/browse/CRW-3154
A workspace should be stopped after 30 minutes of inactivity 
=> chore: increase idle timeout to 30 minutes

build/dockerfiles/import-vsix.sh
Clean some temporary files to avoid them to be stored in the image
N/A
Build and see the new size of the image
=> chore: perform cleanup at the end to get rid of space

README.md
fix readme so that command works when copy pasted
in minikube copy paste the command
=> fix (doc) : the namespace installed in minikube is eclipse-che

che-editors.yaml, make-release.sh
Add Stable version of Che Code to che-editors yaml (which will be updated with release cycles)
https://github.com/eclipse/che/issues/21552
=> Add stable Che Code to che editors

openvsx-sync.json
Add git-base extension to the local openvsx to fix the build
https://github.com/eclipse-che/che-plugin-registry/actions/runs/3131186609/jobs/5086753664
Check GH action image build result
=> chore: add git-base extension to the local openvsx

che-editors.yaml
chore: clean up description/attribute.title and displayName values for consistency and compliance with branding/trademark (#[21704](https://github.com/eclipse/che/issues/21704)) ([CRW-3098](https://issues.redhat.com//browse/CRW-3098));
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
* https://github.com/eclipse/che/issues/21704
* https://issues.redhat.com/browse/CRW-3098
N/A
=> chore: clean up description/attribute.title and displayName values for consistency and compliance with branding/trademark (#21704) (CRW-3098)

.github/workflows/next-build.yml, .github/workflows/try-in-web-ide.yaml, README.md
chore: #21790 add badges for some actions and a link to downstream 3.x job; clean up name shown in badge
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: #21790 add badges for some actions and a link to downstream 3.x job

README.md, build/dockerfiles/import-vsix.sh, openvsx-sync.json
- Extend list of VS Code extensions 
- Fix a problem with redhat.java vsix file for local registry
https://issues.redhat.com/browse/CRW-3507
Start che with local plugin registry and see the redhat.java plugin is available to be installed
=> chore: add a few extensions into local openvsx registry

README.md
Fixes a typo in the README.md in the deployment section with helm and minikube.
https://github.com/eclipse/che/issues/21821
Open the README.md to check the spelling
=> fix: typo in helm deployment description

che-plugins.yaml, tools/build/tests/_data/meta/che-theia-meta-with-multiple-volumes.yaml, tools/build/tests/_data/meta/che-theia-meta.yaml, tools/build/tests/_data/meta/no-container.yaml, tools/build/tests/build.spec.ts, tools/build/tests/common/containers-helper.spec.ts, tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts, tools/build/tests/editor/che-editor-meta-yaml-generator.spec.ts
chore: replace theia:next images with theia:latest images as we don't include :next in registries anymore
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
https://github.com/eclipse/che/issues/21814
N/A
=> chore: replace theia:next images with :latest

openvsx-sync.json
Add vscode.html-language-features extension into te local, it is required by latest redhat.vscode-quarkus extension
fix build
check GH PR actions
=> chore: add vscode.html-language-features extension into te local reg

.github/workflows/dependabot-pr-workaround.yml, .github/workflows/happy-path.yaml, .github/workflows/image-build-pr-check.yml, .github/workflows/next-build.yml, .github/workflows/pr-checks.yml, .github/workflows/publish-content-push-main.yml, .github/workflows/publish-plugin-report.yaml, .github/workflows/publish-pr-check-content.yml, .github/workflows/release.yml, .github/workflows/resource-limits-pr-check.yaml, .github/workflows/shellcheck-pr-check.yml, .github/workflows/sidecar-build-push.yaml, .github/workflows/sidecar-pr-checks.yaml, .github/workflows/sidecar-scripts-executable-pr-check.yaml, .github/workflows/try-in-web-ide.yaml, .github/workflows/typescript-pr-check.yml, .github/workflows/typescript-publish.yml, .github/workflows/vsix-definition-pr-check.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Update GitHub actions to use Node 16 and Ubuntu Latest
https://github.com/eclipse/che/issues/21763
Run GH Actions to make sure they still work properly.
=> chore: Update GitHub actions to use Node 16 and Ubuntu Latest

che-editors.yaml
Set urlRewriteSupported: false for redirect endpoints in editors definitions
https://issues.redhat.com/browse/CRW-3600
All the redirect endpoints should have `urlRewriteSupported` set to `false` except the main IDE endpoint that should have `urlRewriteSupported: true`
=> chore: set urlRewriteSupported: false for editor's endpoints

che-editors.yaml
It removes the unneeded security token for che-code main endpoint.
https://github.com/eclipse/che/issues/21772
I have tested using [this gist](https://gist.github.com/l0rd/b6045738e5158231bf780bd19cd0ddce#file-vscode-withouth-path-yaml).
=> Remove vscode main endpoint path

che-editors.yaml
1. Marks `che-idea-runtime-description` component as container contribution.
2. Replaces `app.kubernetes.io/component: che-idea-injector` on `app.kubernetes.io/component: che-idea-runtime` to be consistent with `che-code` where everything works without issues
https://github.com/eclipse/che/issues/21878
Depends on https://github.com/eclipse/che/issues/21738
=> fix: mark che-idea-runtime-description component as container-contribution

.ci/sidecar-build-publish.sh
Disable provenance for buildx builds
https://github.com/eclipse/che/issues/21954
=> Set provenance=false for buildx builds

che-editors.yaml
Use post-start event instead of command to start IntelliJ IDEA
https://github.com/eclipse/che/issues/22034
See https://github.com/eclipse-che/che-plugin-registry/pull/1623#issuecomment-1479539153
=> feat: Use post-start event to start JetBrains IDEs

.github/workflows/regen-yarn-lock-and-copy.yml
fix: do pull before pushing yarn.lock
=> fix: do pull before pushing yarn.lock

.github/workflows/regen-yarn-lock-and-copy.yml
=> feat: do pull before pushing

.github/workflows/regen-yarn-lock-and-copy.yml, tools/build/yarn.lock
Update regen yarn action to follow all branches
=> fix: update regen yarn action

.github/workflows/regen-yarn-lock-and-copy.yml
Don't do force push in copy yarn.lock file action
=> feat: update regen yarn GH action

.github/workflows/happy-path.yaml, .github/workflows/image-build-pr-check.yml, .github/workflows/next-build.yml, .github/workflows/release.yml, .github/workflows/typescript-pr-check.yml, .github/workflows/typescript-publish.yml
Replace deprecated set-output command
https://github.com/eclipse/che/issues/21993
=> chore: che-21993 replace deprecated set-output in actions

.ci/openshift-ci/test.sh
=> feat:disable os-ci setup

openvsx-sync.json
Removes redhat.project-initializer since it is deprecated.
https://open-vsx.org/extension/redhat/project-initializer
The same functionality is in quarkus and vscode-openshift-connector, both of which we already pull in, so project-initializer can be removed.
https://issues.redhat.com/browse/CRW-4558
=> CRW-4558, remove redhat.project-initializer since it is deprecated.

build/dockerfiles/Dockerfile, build/dockerfiles/entrypoint.sh, build/dockerfiles/import-vsix.sh, build/dockerfiles/start-services.sh
cherry-picking https://github.com/eclipse-che/che-plugin-registry/pull/1736 
The assumption is that Upgrade java to 17 version should fix 
```
.Exception in thread "main" java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
```
https://issues.redhat.com/browse/CRW-4792
=> chore:update openvsx image to use more recent version (#1736)

openvsx-sync.json
Removes built-in js-debug extension from the list of embedded extensions
https://issues.redhat.com/browse/CRW-4817
- Deploy che
- Update eclipse-che CR to use internal plugin registry with custom image:
deployment:
containers:
- image: 'quay.io/vsvydenk/che-plugin-registry:up'
openVSXURL: ''
- Start any workspace and check the list of available extensions, js-debug should not be there 
=> chore: remove js-debug extension

openvsx-sync.json
Adds ms-dotnettools.vscode-dotnet-runtime extension into the list of embedded extensions as it is required by the latest version of muhammad-sammy.csharp
https://github.com/eclipse/che/issues/22470
Build the registry
=> chore: add vscode-dotnet-runtime extension

.ci/openshift-ci/Dockerfile
chore:update Dockerfile to build in OS CI
https://github.com/eclipse/che/issues/22468
=> chore:update Dockerfile to build in OS CI

build/dockerfiles/Dockerfile, build/dockerfiles/import-vsix.sh, openvsx-sync.json
- Use latest openvsx-server image
- Use versions instead of allVersions
- Fix publisher name for extensions
https://issues.redhat.com/browse/CRW-4593
https://github.com/eclipse/che/issues/22405
Check PR check build
=> Use latest openvsx-server image; use versions instead of allVersions

.github/workflows/typescript-pr-check.yml
fix:revert codecov-action to v3
=> fix:revert codecov-action to v3

openvsx-sync.json
Fix build by changing order of extensions publishing
Check PR check
=> fix: publish camel before camelk

build/dockerfiles/import-vsix.sh
chore: update ovsx to 0.8.3
https://issues.redhat.com/browse/CRW-4585
Check the build, all extensions should be published to the embedded plugin registry
=> chore: update ovsx to 0.8.3

README.md
update README with correct node and yarn version
=> chore:update README with correct node and yarn version

build/dockerfiles/Dockerfile
Updates base openvsx-server image to v0.14.1
https://issues.redhat.com/browse/CRW-5313
Check PR check build action that all extensions are published
=> chore: update base openvsx-server image to v0.14.1

che-editors.yaml
Adds IntelliJ IDEA Ultimate dev server editor to use with the local JetBrains IDE.
closes https://github.com/eclipse/che/issues/22708
Start a Workspace with the test repository:
[![Dev](https://img.shields.io/static/v1?label=Open%20in&message=Che%20dogfooding%20server%20&logo=eclipseche&color=FDB940&labelColor=525C86)](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/f?url=https://github.com/azatsarynnyy/web-nodejs-sample/tree/idea-server&policies.create=peruser)
It contains an identical editor definition in `.che/che-editor.yaml`.
Once the IDE is started, the page with instructions should be shown.
Reviewers, please …
=> Add IDEA desktop editor

che-editors.yaml
All editor's endpoints should use https protocol
Idea
pycharm:
idea-server:
https://issues.redhat.com/browse/CRW-5380
1. Deploy che and patch CR to use quay.io/vsvydenk/che-plugin-registry:next plugin registry image
2. Try to start workspaces using (each link specifies the editor to be used in .che/che-editor.yaml file):
- idea-server: https://github.com/svor/web-nodejs-sample/tree/idea-server
- idea: https://github.com/svor/web-nodejs-sample/tree/idea
- pycharm: https://github.com/svor/web-nodejs-sample/tree/pycharm
3. Check that workspace is started
=> chore: use https protocol in editor's endpoints

.ci/openshift-ci/Dockerfile
Fixing "npm: command not found" error when run 'ci/prow/v14-plugins-test-pr-check' job.
https://issues.redhat.com/browse/CRW-5637
It's not possible to test till merge with main branch.
=> Install npm in OpenShift CI image

.github/workflows/publish-content-push-main.yml, .github/workflows/publish-pr-check-content.yml, CONTRIBUTE.md, che-editors.yaml
Trying to fix an action that publishes plugin registry content to surge.sh
https://github.com/eclipse/che/issues/22792
=> fix: publish content to surge.sh

che-editors.yaml
=> fix: fix typo on editor's definition

.ci/openshift-ci/Dockerfile, .github/workflows/smoke-test-pr-check.yaml
Fix URL where E2E tests is downloading chectl install script from.
https://github.com/eclipse-che/che/issues/22925
=> Download chectl install script from che-incubator.github.io in tests

.ci/openshift-ci/Dockerfile, build/dockerfiles/Dockerfile, build/dockerfiles/import-vsix.sh
- Upgrade openvsx-server to 0.16.0
- Fixes a problem with importing VS Code extensions with vscode engine version * 
https://issues.redhat.com/browse/CRW-6803
try build the registry
=> upgrade openvsx server to 0.16.0; fix import extensions with * vscode engine version

openvsx-sync.json, tools/build/package.json, tools/build/yarn.lock, yarn.lock
bump axios to ^1.7.4
https://issues.redhat.com/browse/CRW-6932
=> chore: bump axios

.github/workflows/shellcheck-pr-check.yml, build.sh
Update to the newest runner (ubuntu 24.04)
https://github.com/eclipse-che/che/issues/23344
=> upgrade deprecated ubuntu-20.04 runners

build/dockerfiles/Dockerfile
This PR enables support for building the Che Plugin Registry on the s390x architecture.
It updates and refines architecture compatibility logic and ensures successful builds on IBM Z running RHEL 9.4 (s390x).
This is part of internal enablement for Che on s390x (IBM Z).
-  Clone the repository and checkout this branch
-  Run: ./build.sh
-  Ensure BUILD SUCCESS is shown for all modules (as in the attached screenshot)
=> Enable Che Plugin Registry Build Support on s390x Architecture
