- index.sh
Add type of the object to the index file of che-plugin-registry
https://github.com/eclipse/che/issues/10781
> Add type of the object to the index file of che-plugin-registry

- plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
Rename the folder with Theia meta.yaml to its ID since Che master
build download path by ID/version and current location is
incorrect.
Also fixes mixed ID/Name fields content.
> Fix location of meta file of Theia editor

- index.sh
Field 'id' is needed because a client should add it along with
the version to Che workspace attributes.
> Add field 'id' to index

- README.md
- openshift/che-plugin-registry.yml
Added route and parameters to OpenShift template. Updated docs.
Reference https://github.com/eclipse/che/issues/10834
> Added route and parameters to OpenShift template. Updated docs.

- .htaccess
- Dockerfile
- Dockerfile.rhel
- plugins/.htaccess
Reference issue https://github.com/eclipse/che-plugin-registry/issues/26
1. Return readme on http://localhost:8080/ 
I didn't want to maintain two readme for now and it's quite hard to add md->html convertor for this image ```FROM quay.io/openshiftio/rhel-base-httpd:latest``` that is why it shows raw md.
2. Return index.json on  http://localhost:8080/plugins
3. Return meta.yaml for plugins requests
> Added Apache index files configuration

- .htaccess
Configure apache to disable caching.
Fixes https://github.com/eclipse/che-plugin-registry/issues/30
Before 
```
[ 9:51:32]sj:~#: curl -v  "http://localhost:8080/plugins/"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /plugins/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 24 Sep 2018 06:51:40 GMT
< Server: Apache/2.4.27 (Red Hat) OpenSSL/1.0.2k-fips
< Last-Modified: Mon, 24 Sep 2018 06:50:35 GMT
< ETag: "3e2-5769867f884c0"
< Accept-Ranges: bytes
< Content-Length: 994
< Access-Control-Allow-Origin: *
< Content-Type: application/json
```
after
```
[ 9:52:08]sj:~#: curl -v  "http://localhost:8080/plugins/"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET …
```
> Prevent caching of index file by browser

- plugins/org.eclipse.che.editor.jupyter/1.0.0/meta.yaml
Jupyter is not really IDE, so this PR removes usage of word ide in editor description
It is related to https://github.com/ws-skeleton/che-editor-jupyter/pull/1
> Do not use word 'IDE' for Jupyter Notebook description

- plugins/org.eclipse.che.editor.dirigible/1.0.0/meta.yaml
…ins/org.eclipse.che.editor.dirigible/1.0.0/meta.yaml
Adding Eclipse Dirigible Che Plugin
> Adding dirigible-che-editor-plugin

- README.md
- kubernetes/che-plugin-registry/Chart.yaml
- kubernetes/che-plugin-registry/README.md
- kubernetes/che-plugin-registry/templates/deployment.yaml
- kubernetes/che-plugin-registry/templates/ingress.yaml
- kubernetes/che-plugin-registry/templates/service.yaml
- kubernetes/che-plugin-registry/values.yaml
- openshift/che-plugin-registry.yml
Currently the README.md had only instructions to deploy the registry on Docker and OpenShift. This PR adds an Helm Chart and the instructions to use it to deploy the registry on Kubernetes.
> Added an Helm Chart

- plugins/org.eclipse.che.theia.dev/0.0.1/meta.yaml
This plug-in brings the theia development container used to build che/theia with required tools
So, create Che7 stack, pickup this plug-in and then a theia-dev container is brought 
this one: https://github.com/eclipse/che/tree/master/dockerfiles/theia-dev
It allows to work with the custom Che/Theia
Change-Id: I165d8934d82da045f2ababfc62275408d831bd50
> Introduce Che/Theia dev plug-in

- plugins/org.eclipse.che.editor.gwt/1.0.0/meta.yaml
Update url of che-editor-gwt-ide. Now it points to https://github.com/eclipse/che-editor-gwt-ide repository releases
related to https://github.com/eclipse/che/issues/12172
> Update url of che-editor-gwt-ide

- Dockerfile
- Dockerfile.rhel
- README.md
- check_plugins_viewer_mandatory_fields.sh
- cico_build.sh
- index.sh
- plugins/che-dummy-plugin/0.0.1/meta.yaml
- plugins/che-machine-exec-plugin/0.0.1/meta.yaml
- plugins/che-service-plugin/0.0.1/meta.yaml
- plugins/org.eclipse.che.editor.dirigible/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.eclipseide/0.0.1/meta.yaml
- plugins/org.eclipse.che.editor.gwt/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.jupyter/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
- plugins/org.eclipse.che.samples.container-fortune/0.0.1/meta.yaml
- plugins/org.eclipse.che.theia.dev/0.0.1/meta.yaml
- set_plugin_dates.sh
Adds more fields to plugin's YAML
| Property | YAML  |
|---|---|
| Title | title |
| Publisher | publisher |
| Category | category |
| Icon | icon |
| Short-Description | description |
| Preview | preview | 
| Repository | repository
| First Publication Date | firstPublicationDate | 
| Latest Updated | latestUpdateDate |
| Tags | tags
| Media-img | media-img
| Media-video | media-video
Added script to validate presense of mandatory fields (to not be null or empty):
`title, publisher, category, icon, description, repository, firstPublicationDate, latestUpdateDate`
Field `category` is also validated, as it must have the value of one of the following 
"Editor", "Debugger", "Formatter", "Language", "Linter", "Snippet", "Theme", "Other"
Non mandatory fields are not validated at all …
> Add & validate more fields for plugin viewer

- .travis.yml
- Dockerfile
- Dockerfile.rhel
- README.md
- check_plugins_viewer_mandatory_fields.sh
- cico_build.sh
- index.sh
- plugins/che-dummy-plugin/0.0.1/meta.yaml
- plugins/che-machine-exec-plugin/0.0.1/meta.yaml
- plugins/che-service-plugin/0.0.1/meta.yaml
- plugins/org.eclipse.che.editor.dirigible/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.eclipseide/0.0.1/meta.yaml
- plugins/org.eclipse.che.editor.gwt/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.jupyter/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
- plugins/org.eclipse.che.samples.container-fortune/0.0.1/meta.yaml
- plugins/org.eclipse.che.theia.dev/0.0.1/meta.yaml
- plugins/org.eclipse.che.vscode-sonarlint/0.0.1/meta.yaml
- set_plugin_dates.sh
Adding more fields for plugin meta YAML, for use by plugin-viewer
Added scripts for validation of mandatory fields, that are run during Dockerfile image building
Reworked Dockerfile to multistage image build
This PR must be merged ONLY after corresponding changes in model of Che:
https://github.com/eclipse/che/pull/12489
Issue https://github.com/eclipse/che-plugin-registry/issues/71
> Add & validate plugin meta for plugin viewer

- plugins/redhat.vscode-xml/0.3.0/meta.yaml
https://github.com/eclipse/che/issues/12437
This PR introduces Red Hat XML plugin [1]
[1] https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml
> Add Red Hat xml plugin

- kubernetes/che-plugin-registry/templates/ingress.yaml
- kubernetes/che-plugin-registry/values.yaml
Enable to customize the value of `kubernetes.io/ingress.class`.
This is related on eclipse/che#12645 and similar to eclipse/che#11820
> Parametarize `kubernetes.io/ingress.class`

- plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml
Related issue: https://github.com/eclipse/che/issues/12436
This PR introduces VS Code Java plugin [1]
[1] https://marketplace.visualstudio.com/items?itemName=redhat.java
> Introduce vscode-java plugin

- plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml
Changes the name and title in `org.eclipse.che.vscode-redhat.java` plugin.
Copied it from https://marketplace.visualstudio.com/items?itemName=redhat.java
> Change the name of Java LS plugin

- plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
- plugins/org.eclipse.che.editor.theia/next/meta.yaml
- Introduce 'next' Theia plugin version
- Use `latest` stable Theia version(0.4.0) for `1.0.0`
- Deprecate `master` version(should be removed in a few weeks)
Issue eclipse/che-theia#63
>  Introduce 'next' Theia plugin version

- kubernetes/che-plugin-registry/templates/ingress.yaml
- kubernetes/che-plugin-registry/values.yaml
Appends `tls:` object to the ingress if the secret name was specified.
> [Helm deployments] Enable TLS on the ingress.

- plugins/ms-python.python/2019.2.5433/meta.yaml
Python 3.7.3 is going to be used in a dev image for the Python stack [1]
It is logically to have the same Python version and in a sidecar container for the python plugin.
[1] https://github.com/eclipse/che/issues/12944
> Update Python sidecar image version

- plugins/redhat.vscode-xml/0.3.0/meta.yaml
Chaning url of vscode xml plugin from marketplace to git
https://github.com/redhat-developer/rh-che/issues/1300
> che #12840: Changing url of vscode xml plugin from marketplace to github release

- plugins/redhat.vscode-xml/0.5.1/meta.yaml
- plugins/redhat.vscode-yaml/0.4.0/meta.yaml
che #12840 Adding latest versions of yaml (0.4.0) and xml (0.5.1) vscode plugins
Also contains workaround for marketplace rate limmit error - https://github.com/eclipse/che/issues/12840
> che #12840 Adding latest versions of yaml (0.4.0) and xml (0.5.1) vscode plugins

- plugins/che-netcoredbg-plugin/0.0.1/meta.yaml
PR introduces Che remote plugin which allows to debug .NET apps under .NET Core runtime.
Related issue https://github.com/eclipse/che/issues/12793
> Introduce Che NetcoreDBG Plugin 

- plugins/redhat.vscode-openshift-connector/0.0.19/meta.yaml
Adding latest version of openshift-connector plugin. Switching plugin download url from marketplace to github release
workaround for https://github.com/eclipse/che/issues/12840
> che #12840 Adding latest version of openshift-connector plugin. Switching plugin download url from marketplace to github release

- plugins/org.eclipse.che.vscode-sonarlint/0.0.1/meta.yaml
Workaround for https://github.com/eclipse/che/issues/12840
There is an inconsistency between version of extention in registry (0.0.1) and actual release (1.6.0), but we could probably treat it as a minor issue that should be tackled for the upcoming releases of the extention in the plugin registry future.
> che #12840 Downloading sonarlint extention directly from the github release page

- plugins/ms-kubernetes-tools.vscode-kubernetes-tools/0.1.17/meta.yaml
Downloading `vsix` for kubernetes tools extention from GH release in order to avoid marketplace rate limit error - https://github.com/eclipse/che/issues/12840
> Downloading `vsix` for kubernetes tools extention from GH release in order to avoid marketplace rate limit error

- plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml
Adds [vscode-java-debug](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) into Che remote java plugin.
Unfortunately https://github.com/Microsoft/vscode-java-debug doesn't have `vsx` files in releases, so, we have to download it from VS Marketplace.
> Add Java Debugger into Java plugin

- plugins/org.eclipse.che.vscode-redhat.java/0.43.0/meta.yaml
- v2/plugins/redhat/java/0.43.0/meta.yaml
Adding latest 0.43.0 java vscode extention. Using 'vsix' from GH releases to avoid marketplace rate limit error - https://github.com/eclipse/che/issues/12840
> che #12840 Adding latest 0.43.0 java vscode extention. Using 'vsix' from GH releases to avoid marketplace rate limit error

- plugins/ms-vscode.go/0.9.2/meta.yaml
- v2/plugins/ms-vscode/go/0.9.2/meta.yaml
Related issue - https://github.com/eclipse/che/issues/12840
> Using GH release instead of marketplace for go extension to avoid marketplace rate limit issues

- Dockerfile.rhel
- README.md
Adding build status of the main CI job https://ci.centos.org/job/devtools-che-plugin-registry-build-master 
Currently failing with:
> [91m/bin/sh: ./check_plugins_location_v1.sh: not found
> [0mThe command '/bin/sh -c cd plugins && ./check_plugins_location_v1.sh' returned a non-zero code: 127
>  Fixing build for promototion to dsaas-stg. Adding build status of the main CI job https://ci.centos.org/job/devtools-che-plugin-registry-build-master

- plugins/camel-tooling.vscode-apache-camel/0.0.14/meta.yaml
- v2/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml
create Pull request to check if tests are passing.
How and where to create automated test checking that the plugin is working correctly in Che?
this PR is adding Language Support for Camel to the list of extension
> Add Apache Camel VS Code Extension (#109)

- v3/plugins/dirigiblelabs/dirigible/3.4.0/meta.yaml
Set 3.4.0 tag version of Dirigible instead of latest docker image. This can help to improve reproducibility/stability.
> Set 3.4.0 tag version of Dirigible

- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/README.md
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml
Adds Kubernetes Tooling Che Plugin which is based on the latest [VS Code Kubernetes extension](https://github.com/Azure/vscode-kubernetes-tools/) - 1.0.0. Also, the plugin is running in a sidecar from `eclipse/che-remote-plugin-kubernetes-tooling-1.0.0:next` image that allows using [Buildah](https://github.com/containers/buildah) as an image builder instead of Docker daemon.
The PR should be merged once https://github.com/eclipse/che-theia/pull/220 is merged.
> Add Kubernetes Tooling Che Plugin based on the latest VS Code Kubernetes extension - 1.0.0

- v3/plugins/eclipse/che-theia/next/meta.yaml
This PR decreases default memory for Che Theia IDE to 512M.
512M is a value suggested in [https://github.com/eclipse/che/issues/12620](https://github.com/eclipse/che/issues/12620)#`Memory_settings`.
> Decrease default memory for Che Theia IDE to 512M

- v3/plugins/redhat/php/1.0.13/meta.yaml
- v3/plugins/redhat/php/latest/meta.yaml
Add PHP Intelephense v.1.0.13 for PHP Landuage Support
From https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>
This PR adds a Che7 plugin for PHP Language support based on PHPIntelephense VSCode extension: https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
Fixes eclipse/che#12797
> Che 7 plugin: PHP Language Server #12797

- v3/plugins/redhat/php-debugger/1.13.0/meta.yaml
- v3/plugins/redhat/php-debugger/latest/meta.yaml
Add PHP Debug v.1.13.0 for PHP Debugger
From https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>
This PR adds a Che7 plugin for PHP Debugger based on PHP-Debug VSCode extension from Felix Backer: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug
Fixes https://github.com/eclipse/che/issues/12795
> Che 7 plugin: PHP Debugger #12795

- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml
Increases memory limit for a Kubernetes Che Plugin sidecar to 1G.
The amount of memory has been determined experimentally. Less memory causes unstable work of Helm Repos tree.
> Increase mem. limit for a Kubernetes Che Plugin sidecar to 1G

- v3/plugins/redhat/php/1.0.13/meta.yaml
- v3/plugins/redhat/php/latest/meta.yaml
Set 1000Mi  as memory limit for php-intelephense plugin
https://github.com/eclipse/che/issues/13307
> Set memory limit for php-intelephense plugin

- README.md
Updates the documentation around what we expect for `meta.yaml`s in the registry, to clarify issues around latest changes.
@l0rd Please double check I got the current spec correct.
> Update plugin meta.yaml spec documentation

- v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml
- v3/plugins/camel-tooling/vscode-apache-camel/latest/meta.yaml
- v3/plugins/redhat/java/0.38.0/meta.yaml
- v3/plugins/redhat/java/0.43.0/meta.yaml
- v3/plugins/redhat/java/0.45.0/meta.yaml
- v3/plugins/redhat/java/latest/meta.yaml
- v3/plugins/redhat/vscode-xml/0.3.0/meta.yaml
- v3/plugins/redhat/vscode-xml/0.5.1/meta.yaml
- v3/plugins/redhat/vscode-xml/latest/meta.yaml
- v3/plugins/sonarsource/sonarlint-vscode/0.0.1/meta.yaml
- v3/plugins/sonarsource/sonarlint-vscode/latest/meta.yaml
Changes container image in java based plugins to use Java11
Updated plugins:
- redhat-java
- redhat-xml
- apache-camel
https://github.com/eclipse/che/issues/13225
> Use eclipse/che-remote-plugin-runner-java11 image for java based plugins

- v3/plugins/ms-vscode/go/0.9.2/meta.yaml
- v3/plugins/ms-vscode/go/latest/meta.yaml
This allows for the projects location to be dynamically discovered and be always in line with the location `mountSources` puts the volume to.
https://github.com/eclipse/che/issues/13529
> Base the GOPATH on the projects location injected by Che.

- v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.1/meta.yaml
- v3/plugins/redhat-developer/che-omnisharp-plugin/latest/meta.yaml
- v3/plugins/redhat-developer/netcoredbg-theia-plugin/0.0.1/meta.yaml
- v3/plugins/redhat-developer/netcoredbg-theia-plugin/latest/meta.yaml
In previous versions of plugin registry if plugin is **Theia plugin** not **VSCode extension**, it should contain information about container image not in **meta.yaml**. For **v3** need to have this information in meta.yaml. So this PR provides the information about the image which should be used in  **netcoredb** and **omnisharp** plugins.
> Add containers section into omnisharp and netcoredbg plugins

- v3/plugins/redhat/vscode-xml/0.3.0/meta.yaml
- v3/plugins/redhat/vscode-xml/0.7.0/meta.yaml
- v3/plugins/redhat/vscode-xml/latest/meta.yaml
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
This PR sets the memory limit for vscode-xml and adds in the newest version of vscode-xml (0.7.0).
Part of: eclipse/che#13521
Tested on kubernetes.
> Set vscode-xml memory limit to 768. Update vscode-xml to 0.7.0

- v3/plugins/redhat/vscode-yaml/0.3.0/meta.yaml
- v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml
- v3/plugins/redhat/vscode-yaml/latest/meta.yaml
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
This PR sets the memory limit for vscode-yaml.
Fixes: https://github.com/eclipse/che/issues/13465
Part of: https://github.com/eclipse/che/issues/13521
Tested on both kubernetes and openshift.
> Set memory to 256 for YAML

- v3/plugins/redhat/java/0.46.0/meta.yaml
- v3/plugins/redhat/java/latest/meta.yaml
- Adds new version of java plugin 0.46.0
- Updates latest version of java plugin to use 0.46.0
> Update redhat-java plugin to 0.46.0

- v3/plugins/che-incubator/typescript/1.30.2/meta.yaml
- v3/plugins/ms-python/python/2019.2.5433/meta.yaml
- v3/plugins/ms-python/python/2019.3.6558/meta.yaml
- v3/plugins/ms-vscode/go/0.9.2/meta.yaml
- v3/plugins/ms-vscode/node-debug/1.32.1/meta.yaml
- v3/plugins/ms-vscode/node-debug2/1.31.6/meta.yaml
Set memory limits for old versions of plugins
https://github.com/eclipse/che/issues/13512
> Set memory limits for old versions of plugins

- v3/plugins/ms-vscode/vscode-github-pullrequest/0.8.0/meta.yaml
- v3/plugins/ms-vscode/vscode-github-pullrequest/latest/meta.yaml
https://github.com/eclipse/che/issues/11867
> Add Vscode Github plugin

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/where-to-report-issues.md
Provide template to create issues in main Eclipse Che repository
https://github.com/eclipse/che/issues/13637
Change-Id: If366437d5df5a6a6cf337c1121114f368f1dca13
> chore(github): Update issue template to use external main che repository

- README.md
Replacing dockerhub image (depracated) with quay.io one in the README file and other fixes.
There is no particular endgame issue about that but it's part of the cleanup needed to "Update release process to include new repositories (theia, broker, registries, chectl, operator) "
> Use quay.io images in README and other small fixes

- v3/plugins/redhat/java/0.38.0/meta.yaml
- v3/plugins/redhat/java/0.43.0/meta.yaml
- v3/plugins/redhat/java/0.45.0/meta.yaml
- v3/plugins/redhat/java/0.46.0/meta.yaml
- v3/plugins/redhat/java11/0.46.0/meta.yaml
- v3/plugins/redhat/java11/latest/meta.yaml
- v3/plugins/redhat/java8/0.46.0/meta.yaml
- v3/plugins/redhat/java8/latest/meta.yaml
This PR creates next structure of Java plug-ins:
* **java**
* 0.38.0
* 0.43.0
* 0.45.0
* 0.46.0
* latest
* **java8**
* 0.46.0
*  latest
* **java11**
* 0.46.0
*  latest
The plug-ins from **java** folder (default) use container image with Java 8. That means that all existing devfiles will use Java8 instead of Java11 in jdt.ls base image.
from **java** is **Language Support for Java(TM)**
from **java8** is **Language Support for Java 8**
from **java11** is **Language Support for Java 11**
https://github.com/eclipse/che/issues/13547
> Add java, java8 and java11 plugins 

- README.md
- build.sh
- cico_build_nightly.sh
- kubernetes/che-plugin-registry/values.yaml
- openshift/che-plugin-registry.yml
These are che-plugin-registry modifications to:
- publish nightly builds ([openshiftio-cico-jobs PR](https://github.com/openshiftio/openshiftio-cico-jobs/pull/1043))
- push images to quay.io/eclipse 
That correspond to what has been done che-devfile-registry side with https://github.com/eclipse/che-devfile-registry/pull/33 and https://github.com/eclipse/che-devfile-registry/pull/35
Related to issue https://github.com/eclipse/che/issues/13915 and to the "Update release process to include new repositories" enhancement of [Che 7 endgame](https://github.com/eclipse/che/issues/13637)
> CI updates: eclipse org and nightly builds

- kubernetes/che-plugin-registry/templates/deployment.yaml
Signed-off-by: Michal Vala <mvala@redhat.com>
`/plugins/` is deprecated now. Use `/v3/plugins/` instead
> update helm chart probes to current URL

- v3/plugins/eclipse/che-theia/next/meta.yaml
Change next version of `che-theia` to `next` 
This one should always be `next` and never updated I suppose
> Change next version of `che-theia` to `next`

- v3/plugins/redhat/dependency-analytics/0.0.12/meta.yaml
- v3/plugins/redhat/dependency-analytics/latest/meta.yaml
Adds meta information for [Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics) Che Plugin v0.0.12/latest
What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1045
- https://github.com/eclipse/che-theia/pull/297
> Adds Dependency Analytics Plugin v3

- cico_build_ci.sh
- cico_functions.sh
similar PR has been already applied in devfile registry - https://github.com/eclipse/che-devfile-registry/pull/86
> Always tag images based on the git commit hash as part of every CI ('master', 'nightly', 'release')

- README.md
Updates badges to refer to the CI jobs they're monitoring, rather than just "build":
Old:
New:
> Update badges to refer to their respective CI jobs.

- v3/plugins/joaompinto/vscode-asciidoctor/2.7.6/meta.yaml
- v3/plugins/joaompinto/vscode-asciidoctor/latest/meta.yaml
Add AsciiDoc plugin to this registry
https://github.com/eclipse/che/issues/14196
> Add AsciiDoc plugin

- v3/plugins/joaompinto/vscode-asciidoctor/2.7.6/meta.yaml
- v3/plugins/joaompinto/vscode-asciidoctor/latest/meta.yaml
fix master. The provided meta.yaml was missing the mandatory category attribute
> Fix missing category for AsciiDoctor plugin eclipse/che#14483

- scripts/check_plugins_location.sh
- scripts/check_plugins_viewer_mandatory_fields.sh
to make it easier to run the check*.sh scripts locally, use $(dirname "$0")/util.sh instead of just ./util.sh
Change-Id: I08ac3380ba9f2a8ea3489a4dc77befe052f0cf84
> to make it easier to run the check*.sh locally

- v3/plugins/ms-python/python/2019.2.5558/meta.yaml
- v3/plugins/ms-python/python/2019.3.6558/meta.yaml
switch to vscode-python/releases/download/2019.2.5558 (in GH releases) vs. ms-python/vsextensions/python/2019.2.5433/vspackage (only in marketplace) (#14573)
Change-Id: I678ba2eb95ba2b2d1529b8d46d8b5aa0b9a10698
> use vscode-python 2019.2.5558 instead of 2019.2.5433

- README.md
Update plugin meta yaml structure definition: defined commands and arguments for plugin container, defined initContainers field, defined persistVolume field.
https://github.com/eclipse/che/issues/13387
**Depends on** https://github.com/eclipse/che-plugin-broker/pull/74 and https://github.com/eclipse/che/pull/14539
> Update plugin meta yaml structure definition.

- Dockerfile
- Dockerfile.rhel
- README.md
- build.sh
- cico_functions.sh
- scripts/cache_artifacts.sh
Add `cache_artifacts.sh` and some optional build stages in the Dockerfile / Dockerfile.rhel which can be used to build a plugin registry that includes .vsix and .theia files, to support running Che in an air-gapped scenario.
PR is ready to merge.
> Add option to cache .vsix and .theia artifacts during build

- v3/plugins/joaompinto/vscode-asciidoctor/2.7.6/meta.yaml
- v3/plugins/joaompinto/vscode-asciidoctor/latest/meta.yaml
Adds `firstPublishedDate` for the AsciiDoctor plugin.
> Add firstPublishedDate for ASCIIDoctor plugin

- v3/plugins/ms-vscode/go/0.11.4/meta.yaml
It updates go plugin to 0.11.4 and uses docker images with go 1.12.9
https://github.com/eclipse/che/issues/13803
https://github.com/eclipse/che-devfile-registry/pull/96
https://github.com/eclipse/che-theia/pull/443
> Update go plugin to 0.11.4 and uses docker images with go 1.12.9

- v3/plugins/redhat/java/0.50.0/meta.yaml
- v3/plugins/redhat/java/latest/meta.yaml
- v3/plugins/redhat/java11/0.50.0/meta.yaml
- v3/plugins/redhat/java11/latest/meta.yaml
- v3/plugins/redhat/java8/0.50.0/meta.yaml
- v3/plugins/redhat/java8/latest/meta.yaml
- Adds java plugin v0.50.0
- Updates latest java plugin
- Updates java-debug plugin to v0.20.0
- Adds `/home/theia/.m2` volume for java plugin
Related issue:
https://github.com/eclipse/che/issues/14649
https://github.com/eclipse/che/issues/13603
> Update java support

- .circleci/config.yml
Update CircleCI config to build default registry instead of offline version.
> Fix CircleCI build to not make offline registry

- v3/plugins/redhat/vscode-openshift-connector/0.1.0/meta.yaml
- v3/plugins/redhat/vscode-openshift-connector/latest/meta.yaml
- adds descriptor file for OpenShift Connector Che Plugin 0.1.0.
- points latest version to 0.1.0
Should be merged once `eclipse/che-remote-plugin-openshift-connector-0.1.0:next` image is published.
See https://github.com/eclipse/che-theia/pull/465
> Add OpenShift Connector Che Plugin 0.1.0

- v3/plugins/redhat/dependency-analytics/0.0.13/meta.yaml
Adds meta information for Dependency Analytics Che Plugin v0.0.13/latest
Dependent PR :
eclipse/che-theia#469
> Add dependency analytics extension v0.0.13 to plugin registry

- v3/plugins/redhat/vscode-apache-camel/0.0.18/meta.yaml
eclipse/che#14837
it allows to have Camel K Yaml file support
implement eclipse/che#14837
> feat(core): Add support for Tooling for Apache Camel 0.0.18

- v3/plugins/redhat/vscode-camelk/0.0.9/meta.yaml
- v3/plugins/redhat/vscode-camelk/README.md
- v3/plugins/redhat/vscode-camelk/latest/meta.yaml
- requires a specific dockerfile with Kubectl and Kamel on cli.
- Add Kubernetes extension which is a required dependency of VS Code
Camel K tooling
Add VS Code Tooling for Apache Camel in Che Plugin registry
~~/!\ it requires this other PR to be merged with Dockerfile published: https://github.com/eclipse/che-theia/pull/476~~ Dockerfile published
> feat(core): Add VS Camel K extension eclipse/che#14806

- build/scripts/check_plugins_viewer_mandatory_fields.sh
allow check_plugins_viewer_mandatory_fields.sh to be run locally
Change-Id: I9ae20399c599912d4f73a22d8c23a588d45d0bca
> allow check_plugins_viewer_mandatory_fields.sh to be run locally

- README.md
- v3/plugins/dirigiblelabs/dirigible/3.4.0/meta.yaml
- v3/plugins/dirigiblelabs/dirigible/latest/meta.yaml
- v3/plugins/eclipse/che-theia/7.0.0-next/meta.yaml
- v3/plugins/eclipse/che-theia/7.0.0-rc-3.0/meta.yaml
- v3/plugins/eclipse/che-theia/7.0.0-rc-4.0/meta.yaml
- v3/plugins/eclipse/che-theia/7.0.0/meta.yaml
- v3/plugins/eclipse/che-theia/7.1.0/meta.yaml
- v3/plugins/eclipse/che-theia/7.2.0/meta.yaml
- v3/plugins/eclipse/che-theia/latest/meta.yaml
- v3/plugins/eclipse/che-theia/next/meta.yaml
Fixes to use string value.
All values in `*.env.value` should be typed to string.
Since it is obvious that runtimes treat it as string.
It's not good to use implicit type cast, IMO.
> Use string value at `env.value` instead of boolean or integer.

- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/README.md
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/latest/meta.yaml
Adds Kubernetes Tooling Che Plugin based on the latest VS Code Kubernetes extension 1.0.4 that includes [support of Buildah tool](https://github.com/Azure/vscode-kubernetes-tools/pull/559).
Depends on https://github.com/eclipse/che-theia/pull/493
https://github.com/eclipse/che/issues/13316
> Add Kubernetes Che Plugin based on the VS Code Kubernetes extension 1.0.4

- openshift/che-plugin-registry.yml
Adding openshift template for backwards compatibility required for the Hosted Che deployment (release-preview branch)
Alternative for https://github.com/openshiftio/saas-openshiftio/pull/1338
Deployment path has been changed in the https://github.com/eclipse/che-plugin-registry/pull/245
> Adding openshift template for backwards compatibility required for the Hosted Che deployment

- build/dockerfiles/Dockerfile
- build/dockerfiles/rhel.Dockerfile
- build/scripts/list_referenced_images.sh
Adds building a list of externally-referenced images to the offline build to make it easier for users to know which images need to be pulled into a private registry.
Required for https://github.com/eclipse/che/issues/14866
> Add list of external images to server when offline registry is built

- .htaccess
Add redirect `/resources -> /v3/resources` to match the redirect for plugins.
> Add redirect for resources to match one for plugins

- build/dockerfiles/entrypoint.sh
Fixes the image regex we use to break an image reference into `repo/org/image:tag`. Currently it fails to match if registry hostname contains a port, since it does not match the colon.
https://github.com/eclipse/che/issues/14990
> Fix regex used for processing image references

- v3/plugins/che-incubator/typescript/1.30.2/meta.yaml
- v3/plugins/che-incubator/typescript/1.35.1/meta.yaml
- v3/plugins/ms-vscode/node-debug/1.32.1/meta.yaml
- v3/plugins/ms-vscode/node-debug/1.35.2/meta.yaml
- v3/plugins/ms-vscode/node-debug2/1.31.6/meta.yaml
- v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
- v3/plugins/redhat/vscode-yaml/0.3.0/meta.yaml
- v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml
Replace `eclipse/che-theia-endpoint-runtime` image with `eclipse/che-remote-plugin-node` image
`eclipse/che-theia-endpoint-runtime` - is deprecated, see [che-theia PR](https://github.com/eclipse/che-theia/pull/521 )
> Replace 'eclipse/che-theia-endpoint-runtime' image

- build/scripts/list_referenced_images.sh
- v3/plugins/eclipse/che-theia/next/meta.yaml
- v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.4/meta.yaml
Make sure that init container added for remote runtime injection is included in existing airgap functionality.
- Update scripts to handle updated devfile structure (initcontainers)
- Update metas to all have registry in image references.
> Make sure theia-remote-runtime-binary image is included in airgap

- .github/CODEOWNERS
Add @ibuziuk as codeowner, to help with pushing through smaller changes that still require codeowner approval.
> Add ibuziuk to codeowners

- v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
Use nightly version che-machine-exec from centos Ci. Remove next tag from Codenvy CI.
https://github.com/eclipse/che/issues/14887
> Use nightly version che-machine-exec from centos Ci.

- v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
* Use nightly version che-machine-exec from centos Ci.
Use nightly version che-machine-exec from centos Ci.
https://github.com/eclipse/che/issues/14887
> Use nightly version che-machine-exec from centos Ci. (#290)

- build/scripts/index.sh
- add trailing slash in the self link to avoid unnecessary redirects
- Workaround for https://github.com/eclipse/che/issues/15189
> add trailing slash in the self link to avoid unnecessary redirects

- v3/plugins/eclipse/che-theia/7.3.1/meta.yaml
- v3/plugins/eclipse/che-theia/7.4.0/meta.yaml
- v3/plugins/eclipse/che-theia/next/meta.yaml
- v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.4/meta.yaml
Makes sure all images have a registry included (i.e. replace `eclipse/image` with `docker.io/eclipse/image`. This is required for various scripts, including airgap (so that registry can be overridden).
> Ensure all image references have registry part

- v3/plugins/ms-vscode/node-debug2/1.31.6/meta.yaml
- v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
- deprecate old node-debug2 version 1.31.6 
- update newest node-debu2 version 1.33.0 to replace link from vscode marketplace with dl.jboss.org link
> Update reference for node-debug2 extension

- v3/plugins/eclipse/che-machine-exec-plugin/7.3.2/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.3.3/meta.yaml
- v3/plugins/eclipse/che-theia/7.3.2/meta.yaml
- v3/plugins/eclipse/che-theia/7.3.3/meta.yaml
Add the 7.3.2 and 7.3.3 bugfix version of che-machine-exec and che-theia to master branch to ensure compatibility when updating Che.
Metas are copied from 7.3.3 tag.
Fixes https://github.com/eclipse/che/issues/15444 for future releases.
> Add 7.3.2 and 7.3.3 versions of che-theia/che-machine-exec

- README.md
Update the custom plugin registry build instructions to refer to `build.sh` as they are out of date.
> Update README.md to refer to build.sh in custom registry instructions

- v3/plugins/broadcommfd/cobol-language-support/0.9.1/meta.yaml
- v3/plugins/broadcommfd/debugger-for-mainframe/1.0.0/meta.yaml
Cherry-pick of the https://github.com/eclipse/che-plugin-registry/pull/327/commits/6295a7130aed666720dc9761f7aa53213dc999b2 
Should be merged to master before we start the 7.7.0 release - https://github.com/eclipse/che/issues/15609
> Setting correct versions of the container runtime images for broadcommfd plugins

- v3/plugins/ms-python/python/2019.5.18875/meta.yaml
Fix vscode-python plugin with providing the correctly built .vsix extension
https://github.com/eclipse/che/issues/15779
> Fix Python plugin

- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.9/meta.yaml
- v3/plugins/redhat/vscode-camelk/0.0.10-4/meta.yaml
- v3/plugins/redhat/vscode-camelk/0.0.10/meta.yaml
- v3/plugins/redhat/vscode-camelk/0.0.11/meta.yaml
- v3/plugins/redhat/vscode-camelk/0.0.9/meta.yaml
- v3/plugins/redhat/vscode-openshift-connector/0.0.17/meta.yaml
- v3/plugins/redhat/vscode-openshift-connector/0.0.19/meta.yaml
- v3/plugins/redhat/vscode-openshift-connector/0.1.1/meta.yaml
- v3/plugins/redhat/vscode-openshift-connector/0.1.2/meta.yaml
Updates plugin metas to include all extensions and extensions dependencies. 
Fixes https://github.com/eclipse/che/issues/15795
Fixes https://github.com/eclipse/che/issues/15730
Plugin dependencies were computed by 
1. Downloading each vsix file
2. Extracting it
3. Checking the extracted plugin's `package.json` for `extensionDependencies`
using the script [here](https://gist.github.com/amisevsk/11e0aaf0ed461a1dfb2bc214c59060fd), which produces the output shown below.
<details><summary>Plugin dependences</summary>
<p>
```yaml
ms-kubernetes-tools/vscode-kubernetes-tools/1.0.9:
extensions:
https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/vscode-kubernetes-tools-1.0.9.vsix
https://github.com/redhat-developer/vscode-yaml/releases/download/0.4.0/redhat.vscode-yaml-0.4 …
```
> Explicitly include plugins' dependencies in their meta.yaml

- RELEASE.MD
Adding release instructions for che-plugin-registry (major/minor/service/bug-fix)
Issue - https://github.com/eclipse/che/issues/15506
> che #15506 Adding release instructions for che-plugin-registry

- .github/CODEOWNERS
Based on last che SOS and based on repositories scope:
https://docs.google.com/document/d/1h6t4novpcRHjxe8DrEhTamDmit9VviOqcMQNtahM9uE/edit#heading=h.nh4qax6oermn
owners of che-plugin-registry is Eric with plugins team
Change-Id: I286e83ced5a996974095b07e85ff2c5229dd9a26
> chore(github): Code Owners should match the team

- v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
- v3/plugins/eclipse/che-theia/next/meta.yaml
Modify the che-machine-exec and che-theia plugins to only bind to 127.0.0.1.
This is in support eclipse/che#15651 and depends on eclipse/che#15890 and https://github.com/eclipse/che-theia/pull/626 both being merged.
> Secure the che-machine-exec and che-theia plugins

- build.sh
- build/dockerfiles/Dockerfile
- build/dockerfiles/content_sets_centos8_appstream.repo
- build/dockerfiles/content_sets_epel7.repo
- build/dockerfiles/entrypoint.sh
- build/dockerfiles/rhel.Dockerfile
- build/dockerfiles/rhel.entrypoint.sh
- build/dockerfiles/rhel.install.sh
- build/scripts/write_image_digests.sh
- cico_build_ci.sh
- cico_build_nightly.sh
- cico_build_release.sh
- cico_functions.sh
- deploy/kubernetes/che-plugin-registry/Chart.yaml
- deploy/kubernetes/che-plugin-registry/templates/configmap.yaml
- deploy/kubernetes/che-plugin-registry/templates/deployment.yaml
- deploy/kubernetes/che-plugin-registry/templates/ingress.yaml
- deploy/kubernetes/che-plugin-registry/templates/service.yaml
- deploy/kubernetes/che-plugin-registry/values.yaml
- deploy/openshift/che-plugin-registry.yml
Add script /build/scripts/write_image_digests.sh, which will rewrite all image references in registry to use the current digest for each image tag. E.g.
```
containers:
- image: "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
```
is replaced with
```
containers:
- image: "quay.io/eclipse/che-sidecar-java@sha256:4fb35b4e112a05c82353ad0e1f5eb35d1ba204be475b72f3c753b0e26c9e668d" # tag: quay.io/eclipse/che-sidecar-java:8-0cfbacb
```
To enable this functionality, it is necessary to install `skopeo` in the builder images, which required changing adding the CentOS8-AppStream repo for the rhel build.
Digest-rewriting functionality is disabled by default and can be enabled by using the `./build.sh` option `--use-digests`, or by passing docker build arg `USE_DIGESTS=true`. 
Existing airgap options are …
> Add option to use digests for images referenced in registry

- v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
- v3/plugins/eclipse/che-theia/next/meta.yaml
Revert "Modify the che-machine-exec and che-theia plugins to only bind to 127.0.0.1. (#378)"
This reverts commit 35e2f3c9a8d8ceeb75b13ebf3c3d8a17be5427ba.
Tested on 
Related to https://github.com/eclipse/che/issues/16053
> Revert "Modify the che-machine-exec and che-theia plugins to only bind to 127.0.0.1. (#378)"

- build/scripts/write_image_digests.sh
Don't overwrite image references with nonsense when we can't access the image being used.
Fixes https://github.com/eclipse/che/issues/16281
> Don't rewrite image digests for images we can't read

- v3/plugins/eclipse/che-machine-exec-plugin/0.0.1/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.0.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.1.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.3.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.3.1/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.3.2/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.3.3/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.4.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.5.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.5.1/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.6.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.7.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.7.1/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.8.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.9.0/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
`s/CHE/Che/` to clean up the workspace startup log.
> Replace CHE with Che in machine exec descriptions

- README.md
- build/scripts/meta.yaml.schema
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml
- v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.9/meta.yaml
- Allows to use PNG images for plugins
- Sets proper images for Kubernetes plugin
Solves issue https://github.com/eclipse/che/issues/14502
> Use PNG icons for Kubernetes plugin

- deploy/kubernetes/che-plugin-registry/templates/configmap.yaml
- deploy/kubernetes/che-plugin-registry/values.yaml
Refactors the template for ConfigMap. I have two motivations.
1. Some Helm chart parser (like Argo-CD) reject empty values in `values.yaml`. They recognize empty value as `<nil>` (not `""`)
2. It's better to reduce exported environment variables as possible.
> Refactor the template for ConfigMap.

- v3/plugins/eclipse/che-machine-exec-plugin/7.9.1/meta.yaml
- v3/plugins/eclipse/che-machine-exec-plugin/7.9.2/meta.yaml
- v3/plugins/eclipse/che-theia/7.9.1/meta.yaml
- v3/plugins/eclipse/che-theia/7.9.2/meta.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
master is missing `7.9.1` and `7.9.2` versions of `che-theia` and `machine-exec` plugins
separate PR to `7.10.x` branch - https://github.com/eclipse/che-plugin-registry/pull/433
> Adding 7.9.1 and 7.9.2 version of che-theia and machine-exec plugins

- build/scripts/meta.yaml.schema
- build/scripts/util.sh
- v3/plugins/che-incubator/cpptools/0.1/meta.yaml
Changes the validation performed on meta.yaml version numbers to only accept string values. Accepting number and string as types at the same time can cause subtle issues due to how json parsing works: if a value can be interpreted as a number, it will be; otherwise it is a string. This means: 
- Version `3.2.1` will parse as a string, `3.2` will parse as a number
- Git commit short hashes can *occasionally* be exclusively digits, which results in parsing as a number, e.g. https://github.com/eclipse/che-plugin-registry/commit/946650187395af0a5e13eb91e4b743a3f25a59bb. 
This can trip up implementations that assume they're getting a version string. 
From a design perspective, versions should never be specified as a number, as standard number logic does not apply to versions (1.10 is after …
> Validate meta.yaml versions to be strings, not numbers

- build/scripts/write_image_digests.sh
CRW-653 support optional extra processing to check backup registries; tweak console output to report digest and source image if successful, and which image failed if skipping
Change-Id: Ieee4cca1344b2dd4f86c10b9e4ceae2eb02dcdd8
> CRW-653 support optional extra processing to check backup registries

- v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
Re-enables NodeJS debugging, fixes eclipse/che#16728
> Add vscode-node-debug 1.44.5 to the plugin registry

- v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
:warning: It should not influence anything but still I would postpone the merge of this PR until 7.13.0 release is done but if there are other opinions - I'm OK with merging it as well.
Do not serve CloudShell resources by che-machine-exec plugin.
At some point, che-machine-exec was designed to optionally serve static resources to have an ability to reuse it for cloud-shell. And then probably by mistake cloud-shell came to che-machine-exec-plugin that is supposed to be used only as WebSocket API frontend for Theia Extension. So, now we have an ability to open CloudShell in a dedicated tab when we start Theia based workspace, and it's more easter egg than expected feature ( which honestly does not work stable ).
So, this PR removes serving cloud-shell static resources by che-machine-exec. …
> Do not serve CloudShell resources by che-machine-exec plugin

- v3/plugins/testthedocs/vale/0.9.1/meta.yaml
See che-dockerfiles/che-sidecar-vale/pull/12
> Update vale sidecar to use sidecar image with Alpine 3.11.6

- .ci/che-cert_generation.sh
- .ci/cico-happy-path-pr-test.sh
- .ci/cico_common.sh
Resolves the shellcheck errors that have been causing [failed CI jobs](https://app.circleci.com/pipelines/github/eclipse/che-plugin-registry). It'll also stop the email I get on every merged commit :)
There should be no functional changes, but failing this CI step means errors are easier to include in other scripts in the repo.
> Fix shellcheck errors in .ci directory

- v3/plugins/redhat/java/0.50.0/meta.yaml
- v3/plugins/redhat/java11/0.50.0/meta.yaml
- v3/plugins/redhat/java8/0.50.0/meta.yaml
- v3/plugins/redhat/quarkus-java8/1.2.0b/meta.yaml
Deprecates older version of Java related plugins where appropriate in the context of https://github.com/eclipse/che/issues/17025
> Deprecate older java related plugins

- CONTRIBUTE.md
- vscode-extensions.json
This file lists all extensions in the che-plugin-registry. By extension, I mean those Che plugins that use VS Code extensions.
The fields are basic (for now) but are as follows:
* revision: the tag or SHA1 ID of the upstream repository, capturing a certain version of the extension
* vsixDirectory (optional): the sub-directory where the extension is located (some repositories have multiple extensions in multiple folders)
* repository: the location of the upstream repository
This file is needed for eclipse/che#17014, which is part of a greater epic eclipse/che#15819.
> Contribute a vscode-extensions.json file

- build/dockerfiles/Dockerfile
upstream tag image has been updated https://github.com/docker-library/httpd/commit/ea20f356a6f7d5b22793d0a51d82d6fccd08a6aa
it removes build dependencies but we were using bash transitively and it fails
add bash
good news: the image is A LOT smaller !
related issue: https://github.com/eclipse/che/issues/17345
Change-Id: Id69a992a971414b6d64416ab9aaf9741b17dcca1
> fix(entrypoint): fix image error

- v3/plugins/eclipse/che-async-pv-plugin/latest.txt
- v3/plugins/eclipse/che-async-pv-plugin/nightly/meta.yaml
Add new plugin for support asynchronous storage. 
Will work with:
> Add plugin for support asynchronous storage

- v3/plugins/redhat/vscode-openshift-connector/0.1.5/meta.yaml
Add a volume mount which stores `oc` config, so the authentication state of the `openshift-connector` plugin is saved between workspace restarts.
fixes https://github.com/eclipse/che/issues/15270
TODO
> Add oc config volume mount to the openshift-connector plugin

- v3/plugins/redhat/rhamt/0.0.23/meta.yaml
Signed-off-by: John Steele <programjsteele@gmail.com>
TODO
> WINDUP-2691 - deprecate rhamt. rhamt has been rebranded to mta.

- v3/plugins/redhat/vscode-openshift-connector/0.1.5/meta.yaml
Adds helm to the sidecar as well. 
Closes eclipse/che#16130
> Use che-container-tools based sidecar image for vscode-openshift-connector

- .ci/digest-validation-pr.sh
- .github/workflows/main.yml
Signed-off-by: flacatus <flacatus@redhat.com>
This PR create a new ci script which basically check all new container images created/changed in the main.yaml files. This CI scripts will run using github actions. The job name is digest-validation.
I tested this job in one of my repo: flacatus/github-actions#4
What issues does this PR fix or reference?
Reference issue: eclipse/che#17368
> Add ci scripts to check digest images in PR

- CONTRIBUTE.md
- vscode-extensions.json
Initial step to add sidecar update checking for the [che-plugin-registry report](https://eclipse.github.io/che-plugin-registry/). Summary of fields:
* **dockerfile**: repository for the Dockerfile that builds the sidecar
* **dockerfileRevision**: (optional) checkout tag/SHA1-ID for the repository to build the sidecar image, in the event the sidecar repo is structured that way
> Add preliminary sidecar fields to vscode-extensions.json

- tools/automation/src/check-plugin-update-template.md
- tools/automation/src/check-plugin-updates.ts
- vscode-extensions.json
This PR adds support for checking of sidecar update status to the nightly che-plugin-registry report.
* New columns for registry sidecar, and upstream sidecar images
* Sidecar images are clickable links, which will take you to the image's repository
* Sidecar images that have a newer upstream version are bolded in the `Upstream Sidecar Image` column
* If a plugin has no sidecar, the sidecar related columns in the report are left blank
> Sidecar update checking

- vscode-extensions.json
Currently the report looks like this:
This is caused by cdt-vscode having the wrong revision.
> Fix cdt-vscode revision field

- v3/plugins/redhat/vscode-openshift-connector/0.1.5/meta.yaml
- vscode-extensions.json
New image has:
* Removed wget, used curl instead
* Fixed issue with oc missing from the container
See eclipse/che#17633
> Update vscode-openshift-connector sidecar image

- v3/plugins/ms-vscode/node-debug2/1.42.3/meta.yaml
- v3/plugins/redhat/dependency-analytics/0.1.0/meta.yaml
- v3/plugins/redhat/php-debugger/1.13.0/meta.yaml
- v3/plugins/redhat/php/1.3.11/meta.yaml
- v3/plugins/redhat/vscode-yaml/0.8.0/meta.yaml
- v3/plugins/zowe/vscode-extension-for-zowe/1.5.1/meta.yaml
- vscode-extensions.json
Use node 12 as a base image, or in the case of che-sidecar-node, the main image.
> Use node 12 images

- .ci/cico-happy-path-pr-test.sh
Signed-off-by: Radim Hopp <rhopp@redhat.com>
Disables OAuth. this is a quick fix to unblock PR check in this repo.
> Disable Openshift OAuth in prcheck.

- tools/automation/src/check-plugin-updates.ts
Avoid https://github.com/eclipse/che/issues/17763 to happen again when invalid metadata are there
Change-Id: Ic0f9a4a1444ae2580d713023201a2f51b69f1cee
> Do not break automated report formatting when error messages have carriage returns

- .github/workflows/icons-extensions-pr-check.yaml
Currently the PR check isn't running to due a preceding slash in the path field.
> Remove preceding slash to icons/extensions PR check

- .github/workflows/shellcheck-pr-check.yml
Use shellcheck from github action
Related to https://github.com/eclipse/che/issues/17830
Change-Id: Ia8b30ca287a9c91711136c67282522ff57a728d0
> chore(shellcheck): Introduce shellcheck as a github action (to remove circle-ci)

- .github/workflows/image-build-pr-check.yml
Use github action PR check (build both for alpine and rhel)
Related to https://github.com/eclipse/che/issues/17830
Change-Id: Ifca420d20b391bc86819ff2215e1d18bd1bfa0fe
> chore(image-build): Add a new GH action to build docker images

- .ci/vscode-extensions-field-validation.sh
- .github/workflows/vscode-extensions-pr-check.yaml
- tools/pr-check/src/pr-check.ts
Checks:
* extension git repo is cloneable
* revision field for the extension's git repo is valid
* sidecar git repo is cloneable
See eclipse/che#17027
> PR check for vscode-extensions.json fields

- v3/plugins/golang/go/0.14.4/meta.yaml
- v3/plugins/golang/go/0.16.1/meta.yaml
- vscode-extensions.json
> golang sidecar gopls fix

- v3/plugins/haskell/vscode-haskell/8.10.1/meta.yaml
- v3/plugins/haskell/vscode-haskell/8.10.2/meta.yaml
- v3/plugins/haskell/vscode-haskell/8.8.4/meta.yaml
preparing devfiles for devfile-registry I get "out of memory" errors and it seems like it can be solved using some extra arguments in the project's stack.yaml, BUT even so I think 1.5gb of ram is too small amount for a c-like build system. Thus giving it more resources may allow to work with bigger projects even in the free tier of che osio.
> haskell needs more than 1.5gb of mem

- sidecars/scala/Dockerfile
> fix cachedirs ownership

- sidecars/scala/Dockerfile
Install only
* JRE
* wrapper script for sbt and mill
* coursier
* ammonite
Anything else, the VS Code Metals extension installs itself
closes https://github.com/che-dockerfiles/che-sidecar-scala/pull/9
closes https://github.com/che-dockerfiles/che-sidecar-scala/pull/11
/cc @ericwill
> Scala: simplify the sidecar image

- v3/plugins/bitlang/cobol/6.0.19/meta.yaml
- v3/plugins/haskell/vscode-haskell/8.10.2/meta.yaml
- vscode-extensions.json
avoid using haskell-debug-adapter and use phoityne-vscode instead
HDA doesn't accept breakpoints yet. 
> fix debug extension breakpoints

- che-theia-plugins.yaml
Adds the volume, endpoint, env, and resource limit entries to the `che-theia-plugins.yaml` file.
N/A
Part of eclipse/che#18215
N/A
> Add volumes, resource limits, endpoints, and envs

- tools/pr-check/__mocks__/axios.ts
- tools/pr-check/src/pr-check.ts
- tools/pr-check/src/pr-icon-check.ts
- tools/pr-check/tests/pr-icon-check.spec.ts
Today PR check icon will only verify icon by using fetch on the icon but the icon can be in relative format like `/images` 
Use relative icons in the meta.yaml
I also added some unit tests
Change-Id: Ia7e7446ba2a2f27023c955b018ebe5eb2a712486
> fix(pr-icon-check): Handle the case with relative icon images

- che-theia-plugins.yaml
These plug-ins have theia as publisher so it should be fixed in their package.json
https://github.com/redhat-developer/omnisharp-theia-plugin/pull/13
https://github.com/redhat-developer/netcoredbg-theia-plugin/pull/13
As workaround, specify the id
N/A
Automatically generating meta.yaml from the current information is not enough as the id in the vsix/repository is not correct.
Compare package.json publisher/name with what is expected in meta.yaml for these plugins
Change-Id: I739ffd5758520fadbf085f610dd1c9cada0b8ebd
> fix(id): These plug-ins have theia as publisher so it should be fixed in their package.json

- sidecars/clang/Dockerfile
Cleanups clang sidecar by removing node from it.
Run CPP workspace with this sidecar
> Remove node from clang sidecar

- .github/workflows/build-jobs.yml
Without the full history, latest changes for sidecars is the last sha1 then it references invalid sha1 of che-plugin-sidecar
It references invalid sidecar images by analyzing `sidecars` folder
example:
```
$ docker run --rm -it --entrypoint=bash quay.io/eclipse/che-plugin-registry:nightly -c "cat /var/www/html/v3/plugins/redhat/java/latest/meta.yaml"
apiVersion: v2
publisher: redhat
name: java
version: latest
type: VS Code extension
displayName: Language Support for Java(TM) by Red Hat
title: Language Support for Java(TM) by Red Hat
description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support
and more...
icon: /v3/images/redhat-java-icon.png
category: Programming Languages
repository: https://github.com/redhat-developer/vscode-java
firstPublicationDate: …
```
> fix(sidecars): Use full history to grab sidecars hashes

- .github/workflows/image-build-pr-check.yml
- .github/workflows/publish-pr-check-content.yml
Once images are built, grab the v3 folder, store it as artifacts of the PR
Then, in a workflow_run flow, grab artifacts and publish them on surge.sh
This way, there is no problem on accessing secrets
It adds two extra checks with links on each PR (one with content from alpine, one with content from rhel)
https://github.com/eclipse/che/issues/15819
You may create a PR on my fork branch https://github.com/benoitf/che-plugin-registry/tree/publish-content but I'm not sure it works if it's not in main branch
So you can play on https://github.com/benoitf/surge-test
Change-Id: …
> chore(surge): Publish on surge.sh the content of each repository on each PR and add link in status check

- che-editors.yaml
Add some missing information to generate meta.yaml
For che-theia-plugins.yaml we were not adding some information as it's available from inside the vsix files but with editors there is no other source, so need to add the details.
Fix volumeMount name to match che-theia-plugins.yaml volumeMount declaration
Also some ids were not matchings the ids of the current plug-ins
che-editors.yaml was introduced as part of https://github.com/eclipse/che/issues/18214
For now this `che-editors.yaml` file is not used but an upcoming PR will process this file.
Change-Id: …
> fix(che-editors): Add missing entries in che-editors.yaml and fix couple of issues on volumes/exposedPort/id

- tools/build/src/sidecar/sidecar-docker-image.ts
- tools/build/tests/sidecar/sidecar-docker-image.spec.ts
1 out of 10 builds are failing on rhel build with 'null' LogResult
It turns out that simpleGit may not handle well child_process/parallel stuff so avoid to use too many spawn execution
Also I added test-case for null value on LogResult
Some PR builds are randomly failing
Check that PR check are green (as it means we're able to build images)
Change-Id: I3cf15da66ea837e52ed7fd53bd86fe9c602ca6d5
> fix(build): simpleGit is not handling well parallel git executions

- tools/build/src/sidecar/sidecar-docker-image.ts
- tools/build/tests/sidecar/sidecar-docker-image.spec.ts
Sets 'manually' the short hash length as it may vary across different runtime environments
on some env (@sunix env), `%h` is returning 8 characters instead of 7 but it may vary as well
PR checks passed (also there is a new test-case)
Change-Id: I7e63ed0c73b39dd47fc590e76d488a3facbd7f85
> fix(sidecar-hash): On some environments, default short hash may not be 7 characters

- che-theia-plugins.yaml
Flag some plug-ins as default plug-ins for selected languages
https://github.com/eclipse/che/issues/18274
Look at /v3/che-theia/featured.json file generated
it should contain plug-ins that are selected in che-theia-plugins.yaml
Change-Id: Idab40e254c4709e5ed0c849ead1d9e5e826f4ddb
> feat(featured): Add featured list of CheTheia plug-ins to enable by default

- sidecars/asciidoc/Dockerfile
- sidecars/asciidoc/PLATFORMS
- sidecars/asciidoc/etc/entrypoint.sh
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Provide a sidecar for the existing asciidoc plugin so task to export to PDF works well.
The sidecar contains asciidoc-topdf
https://github.com/eclipse/che/issues/16370
- Use this devfile (that uses the sidecar built and pushed to my quay.io repo):
```yaml
metadata:
generateName: ascii-doc-
projects:
- name: asciidoctor-che
source:
location: 'https://github.com/sunix/asciidoctor-che'
type: git
branch: master
components:
- id: joaompinto/asciidoctor-vscode/latest
registryUrl: 'https://sunix-che-plugin-registry-dev-asciidoc.surge.sh/v3'
- mountSources: true
args:
- sleep
- infinity
memoryLimit: 768Mi
image: quay.io/sunix/asciidoctor
alias: asciidoctor
commands:
- name: asciidoctor …
```
> feat(sidecar): Sidecar for asciidoc plugins that contains tools like asciidoc

- che-theia-plugins.yaml
Add a sidecar with asciidoc-pdf to the asciidoc plugin, fixing the task `Asciidoc: Export document to pdf` that is currently failing to execute.
Fix https://github.com/eclipse/che/issues/16370
requires https://github.com/eclipse/che-plugin-registry/pull/780
The provided registry has been updated, using `quay.io/eclipse/che-plugin-sidecar:asciidoc-5337f80`
See https://sunix-che-plugin-registry-dev-asciidoc.surge.sh/v3/plugins/joaompinto/asciidoctor-vscode/latest/meta.yaml
```yaml
apiVersion: v2
publisher: joaompinto
name: asciidoctor-vscode
version: latest
type: VS Code extension
displayName: AsciiDoc
title: AsciiDoc
description: Provides rich language support for AsciiDoc.
icon: /v3/images/joaompinto-asciidoctor-vscode-icon.png
category: Programming Languages
repository: …
```
> fix(plugins): add a sidecar with asciidoc-pdf to the asciidoc plugin

- che-theia-plugins.yaml
- sidecars/vale/Dockerfile
Updates vale sidecar to 2.8.0 and extensions to the one from "errata.ai" v 0.12.0
https://github.com/eclipse/che/issues/18755
1. Open a che docs workspace (using https://github.com/eclipse/che-docs/blob/master/devfile.yaml) and change the devfile to point to the version of the plugin referenced in this PR. 
2. Set the "Use CLI" preference in the "Vale" section to true. (unfortunately, we can't do this in a meta.yml).
3. Open various .adoc files: many of them should have errors and warnings coming from vale.
> Update vale to "official" version 0.12.0

- che-editors.yaml
Add a workspace storage volume mount for che-theia editor. The GitHub authentication session is saved in this directory, so the GitHub authentication will be restored after workspace restart.
fixes https://github.com/eclipse/che/issues/18664
Open the che-theia's editor `meta.yaml` (< plugin registry url >/v3/plugins/eclipse/che-theia/next/) and see the workspace storage volume mount:
```
volumes:
- name: plugins
mountPath: /plugins
- name: workspaceStorage
mountPath: /home/theia/.theia/workspace-storage
```
> Add a workspace storage volume mount for che-theia editor

- .github/workflows/happy-path.yaml
Check with each change on the plug-in registry
And check with both Alpine and UBI8 images
https://github.com/eclipse/che/issues/18747
Check PR check result. Should be green
Change-Id: I1b3a01712e45dfd35cc5a8ee94b2ac4ba51e22d5
> Run Happy Path tests using github actions

- che-editors.yaml
Configure default values for `cpuLimit: 1500m` and `cpuRequest: 500m` for next tag image.
N/A
https://github.com/eclipse/che/issues/18565
Create a workspace from the [provided](https://gist.github.com/vzhukovs/b84da9a20b60386bc2145e25d8df88ad/raw/b57af34a6c6418d698f24babe2d62da6f0bf7592/workspace-2.yaml) devfile, workspace should be able to start.
> Configure default cpuLimit and cpuRequest

- .che-didact-guide.md
In the didact guide of the dogfooding workspace:
- Add a link to open `che-editors.yaml`
- Add a link to open `CONTRIBUTE.md` in preview
- Add a link to open the generated `index.json`
> chore(devfile): Add useful links to the didact guide

- CONTRIBUTE.md
- README.md
Documents our publishing of the plugin registry on surge.sh for both nightly and PR builds.
N/A
Fixes eclipse/che#18731
Fixes eclipse/che#18510
Observe and behold, the updated README and CONTRIBUTE files.
> Document surge.sh publishing

- .github/workflows/happy-path.yaml
- che-editors.yaml
Add home folder volume mount for che-theia editor. The GitHub authentication session is saved in this directory, so the GitHub authentication will be restored after workspace restart.
fixes https://github.com/eclipse/che/issues/18782
Open the che-theia's editor `meta.yaml` (< plugin registry url >/v3/plugins/eclipse/che-theia/next/) and see the workspace storage volume mount:
```
volumes:
- name: plugins
mountPath: /plugins
- name: home
mountPath: /home/theia/.theia
```
> Add home volume mount for che-theia editor

- sidecars/ruby/Dockerfile
- sidecars/ruby/etc/entrypoint.sh
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Fixing settings needed for ruby plugin to work.
Using hack as mentioned in https://github.com/eclipse/che/issues/17975#issuecomment-759481640
Settings needed: https://github.com/eclipse/che/issues/18871#issuecomment-766375376
Fix https://github.com/eclipse/che/issues/18871
1. Start this devfile:
```yaml
metadata:
generateName: ruby-test-fix-settings-
projects:
- name: rails-mister-cocktail
source:
type: github
location: https://github.com/omontigny/rails-mister-cocktail
components:
- id: castwide/solargraph/latest
registryUrl: 'https://sunix-che-plugin-registry-fix-ruby-yjb3d.surge.sh/v3'
```
2. edit any `.rb` file
3. see code completion is working
the provided registry refers to this manually built …
> fix(ruby): Fix ruby plugin setting default settings to be used

- make-release.sh
Fixes hardcoded 7.25.0 value in https://github.com/eclipse/che-plugin-registry/blob/master/make-release.sh#L110
> Remove hardcoded 7.25.0 typo in make-release.sh

- .github/workflows/typescript-pr-check.yml
- README.md
Signed-off-by: Sun Tan <sutan@redhat.com>
Publish code coverage for typescript plugin
N/A
Part of https://github.com/eclipse/che/issues/18851
TODO
> chore(coverage): publish test code coverage

- che-theia-plugins.yaml
Temporarily remove plugins that have dead vsix links, until we can replace the links and enable offline builds by default.
Part of eclipse/che#18933
> Temporarily remove some plugins where vsix files are missing

- che-theia-plugins.yaml
Signed-off-by: Vitaliy Gulyy vgulyy@redhat.com
Adds CPU requests/limits to all the plugin sidecars.
https://github.com/eclipse/che/issues/16685
Build plugin registry by hands and deploy local Che.
Steps to do:
- build the plugin registry from this branch
```
$ ./build.sh
```
- upload the plugin registry image to your account at `quay.io`
```
$ docker tag quay.io/eclipse/che-plugin-registry:nightly quay.io/vgulyy/che-plugin-registry:resource-limit
$ docker push quay.io/vgulyy/che-plugin-registry:resource-limit
```
- deploy local Che with applying following `patch.yaml` to replace the default plugin registry
```
$ chectl server:start --platform=minikube --che-operator-cr-patch-yaml patch.yaml
```
`path.yaml` content
```
spec:
server:
pluginRegistryImage: …
```
> CPU limitations

- .ci/sidecar-check-script-permissions.sh
- .github/workflows/sidecar-scripts-executable-pr-check.yaml
If a sidecar adds any .sh files, check that they are executable to prevent entrypoint errors.
Fixes eclipse/che#18737
Locally, add a non-executable .sh file in `sidecars/*` and run `.ci/sidecar-check-script-permissions.sh`. The script should fail until the file gets executable permissions.
> Add a PR check to ensure that sidecar executable files have executable permissions

- tools/build/src/registry/registry-helper.ts
- tools/build/tests/registry/registry-helper.spec.ts
Digests should be used on 'static' tags not on 'on purpose floating tags' so as soon as next images are updated they're used
https://github.com/eclipse/che/issues/18931
check that in external_images.txt file or in che-theia and machine-exec, the digests are not used for next and nightly tag
Change-Id: I53c0be81b4f063306a809f54fdb60ec64349c94e
> feat(digest): Do not use digest on next or nightly tags

- che-editors.yaml
This change proposal lowers the value for the cpuLimit and cpuRequest to allow workspace to run on minikube, which is run with default CPU configuration. By default the value for the CPU is set to 2. After merging the following PR, the general cpuRequest value is more than minikube is available to provide for normal workspace startup. The new values for the cpuLimit is set from 1.5 to 1 and for the cpuRequest is set from 0.5 to 0.1.
Tested on OSIO, RHPDS, Dogfooding and minikube.
N/A
fixes https://github.com/eclipse/che/issues/18955
Start minikube with the following configuration:
```
$ minikube start --addons=ingress --vm=true --memory=8192
```
Deploy Che:
```
$ chectl update next && \
chectl server:deploy -p minikube
```
Create …
> Decrease cpu limits to allow run a workspace on minikube with default cpu configuration

- cico_functions.sh
Hotfix for `7.26.0` rollout of Hosted Che - https://ci.centos.org/job/devtools-che-plugin-registry-release-preview/
This is planned to be the last rollout update
> Hotfix for `7.26.0` rollout of Hosted Che

- che-theia-plugins.yaml
Ruby plugin was disabled  https://github.com/eclipse/che-plugin-registry/pull/829/files 
Re enabling ruby plugin now that it is available: https://github.com/castwide/vscode-solargraph/issues/204#issuecomment-779458141
try the devfile:
```
metadata:
generateName: ruby-test-reenabling-
projects:
- name: rails-mister-cocktail
source:
location: 'https://github.com/omontigny/rails-mister-cocktail'
type: github
components:
- id: castwide/solargraph/latest
registryUrl: 'https://sunix-plugin-registry-ruby-z6b4p.surge.sh/v3/'
```
open a .rb file and try auto complete.
Reviewers, please comment how you tested …
> fix(ruby): Re enabling ruby plugin

- .github/workflows/image-build-pr-check.yml
Do not build image if modified files are in sidecar/** folder.
So it won't try to fetch images that are not yet published
https://github.com/eclipse/che-plugin-registry/pull/849#issuecomment-783696324
this workflow should only happen if we do not modify sidecar folder
Change-Id: I09a09849c885256e1fba2c5c3c2f2632edd2e4f0
> chore(build): Do not build plugin-registry image PR check when only sidecar files are modified

- sidecars/java/Dockerfile
- sidecars/java8/Dockerfile
Making the lombok.jar available to Java.
So user would just need to configure in the devfile:
```
- id: redhat/java/latest
preferences:
java.jdt.ls.vmargs: -javaagent:/home/theia/lombok.jar
```
https://github.com/eclipse/che/issues/17483
Use this devfile: it is using a custom registry that has the java plugin patched to use the image of the sidecar i have built locally.
1. start a workspace with the following devfile
2. open one of the java file `ModelLombokValue.java`, wait for java plugin to be activated
3. open the outline, see the getters and setters that are not defined in the class.
```yaml
metadata:
generateName: java-lombok-
projects:
- name: lombok-project-example
source:
location: 'https://github.com/chuucks/LOMBOK-PROJECT-EXAMPLE'
type: git …
```
> feat(lombok): making lombok.jar available to java sidecar

- tools/build/src/devfile/devfile-module.ts
- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/src/inversify-binding.ts
- tools/build/src/meta-yaml/index-writer.ts
- tools/build/src/meta-yaml/meta-yaml-writer.ts
- tools/build/tests/_data/meta/che-theia-meta.yaml
- tools/build/tests/_data/meta/container-minimal-endpoint.yaml
- tools/build/tests/_data/meta/container-no-endpoints.yaml
- tools/build/tests/_data/meta/machine-exec-plugin-meta.yaml
- tools/build/tests/_data/meta/no-container.yaml
- tools/build/tests/_data/meta/vscode-extension.yaml
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
- tools/build/tests/inversify-binding.spec.ts
- tools/build/tests/meta-yaml/index-writer.spec.ts
- tools/build/tests/meta-yaml/meta-yaml-writer.spec.ts
Write devfile.yaml in addition to meta.yaml for che-plugins and che-editors
Fixes https://github.com/eclipse/che/issues/19060
Look at generated results in `latest` folder for example, it should include both meta.yaml and devfile.yaml
Change-Id: Ibefbb93bc1eab00cdbfc1fe1e2ed2caac87166ce
> feat(devfile): Generates devfile.yaml in addition to meta.yaml for che-editors and che-plugins

- sidecars/java/Dockerfile
Moving lombok.jar to a more generic location: `/lombok.jar` instead of `/home/theia/lombok.jar`.
$HOME env variable could not be used when settings lombok location in 
```yaml
- id: redhat/java/latest
preferences:
java.jdt.ls.vmargs: '-javaagent:${HOME}/lombok.jar'
```
With this PR:
```yaml
- id: redhat/java/latest
preferences:
java.jdt.ls.vmargs: '-javaagent:/lombok.jar'
```
N/A
https://github.com/eclipse/che/issues/17483
with this devfile:
```yaml
metadata:
generateName: java-lombok-
projects:
- name: lombok-project-example
source:
location: 'https://github.com/chuucks/LOMBOK-PROJECT-EXAMPLE'
type: git
branch: master
components:
- id: redhat/java/latest
preferences:
java.jdt.ls.vmargs: '-javaagent:/lombok.jar'
java.server.launchMode: Standard
registryUrl: …
```
> fix(java-sidecar): Moving lombok.jar to a generic location

- che-theia-plugins.yaml
Update vscode-java (jdt-ls) and vscode-java-test to the latest.
Fix https://github.com/eclipse/che/issues/19099
This is a devfile using java plugin from the updated registry. Make sure Java feature all works fine, as well as unit tests.
```yaml
metadata:
generateName: test-java-extension-update-
attributes:
multiRoot: 'on'
projects:
- name: java-web-spring
source:
location: 'https://github.com/spring-projects/spring-petclinic.git'
type: git
commitId: 4953f87917b449a404a7f1f4e2457836b9eafbbc
- name: event-publisher
source:
location: 'https://github.com/parisjug/event-publisher'
type: git
components:
- id: redhat/java/latest
preferences:
java.server.launchMode: Standard
registryUrl: 'https://sunix-plugin-registry-update-java-gbjp9.surge.sh/v3'
- …
```
> feat(java-plugins): update vscode-java and vscode-java-test for all java11 related plugins

- deploy/openshift/che-plugin-registry.yml
Use tls for external plugin registry deployment on the Openshift. User dashboard doesn't work with plugin registry without tls...
none
none. I played with external registry options and this quick fix.
Deploy external plugin registry to the namespace `che-registries`:
```
$ oc new-project che-registries
$ oc new-app -f deploy/openshift/che-plugin-registry.yml -p IMAGE="quay.io/eclipse/che-plugin-registry" -p IMAGE_TAG="nightly" -p PULL_POLICY="Always" -n che-registries
```
Deploy Che using external registry:
```
$ chectl server:start -p openshift -n moon40 --plugin-registry-url=https://che-plugin-registry-che-registries.apps-crc.testing/v3
```
Create new workspace using user dashboard and go to plugins tab. List plugins should appear. …
> Use tls for external plugin registry deployment on the Openshift.

- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/tests/_data/meta/machine-exec-plugin-meta.yaml
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Use secure protocol but not secured flag
https://github.com/eclipse/che/issues/19347
Check generated devfile.yaml (s suffix on protocol for secure endpoints)or look at the unit test
Change-Id: Idd394f18a38da681ae55975e266a2f4374fb4309
> feat(devfile2): Use secure:false + s on protocol for secured devfile2 items

- CONTRIBUTE.md
- tools/build/src/build.ts
- tools/build/src/che-theia-plugin/che-theia-plugin-analyzer-meta-info.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-meta-yaml-generator.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-yaml.ts
- tools/build/src/meta-yaml/meta-yaml-plugin-info.ts
- tools/build/tests/che-plugin/che-plugin-analyzer.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-meta-yaml-generator.spec.ts
Allow to specify plugin preferences in che-theia-plugins.yaml file.
note: it will work only for plug-ins with sidecar for Devfile v1 (but anyway it was already the case as the only way was to patch entrypoint.sh)
preferences are at the same level than sidecar
```yaml
preferences:
asciidoc.use_asciidoctorpdf: true
sidecar:
...
```
Here is how a generated meta.yaml looks like:
https://gist.github.com/benoitf/ba757696b6591f792487b7a006f21d15
https://github.com/eclipse/che/issues/17975
1. Look at unit tests
or
1. you can modify che-theia-plugins.yaml and see generated meta.yaml output
2. it depends on https://github.com/eclipse/che-theia/pull/1047
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-chec …
> feat(preferences): Allow to define preferences in che-theia-plugins.yaml

- che-theia-plugins.yaml
- sidecars/asciidoc/etc/entrypoint.sh
- sidecars/ruby/etc/entrypoint.sh
Once https://github.com/eclipse/che-plugin-registry/pull/904 is merged, we can define preferences in che-theia-plugins.yaml file
This PR remove sidecar entrypoint.sh patches that will not work with multi-root workspaces being enabled
https://github.com/eclipse/che/issues/17975
and https://github.com/eclipse/che-plugin-registry/pull/904
Check preferences are added as expected even if devfile use is not specifying these preferences
Change-Id: I8784568c91f4744d7413a719492df86d53a2a873
> feat(preferences): Store preferences in che-theia-plugins.yaml file

- .gitignore
- tools/automation/.ci/publish-report.sh
Update report site publishing so it doesn't override other sites that may be published in the same gh-pages branch but sub-directories.
N/A
Part of https://github.com/eclipse/che/issues/19268: registries for each version would be published in sub-directories and should not be overriden.
1. fork the che-plugin-registry github (including gh-pages branch)
2. clone the original che-plugin-registry and checkout this `report-gh-pages-keep-history` branch
3. set the env variables (adapt it to use your fork/credentials):
```
export GITHUB_TOKEN=xxx
export GITHUB_ACTOR=sunix
export GITHUB_REPOSITORY=sunix/che-plugin-registry
```
4. build and publish:
```
cd che-plugin-registry
./tools/automation/.ci/publish-report.sh
```
5. check the history in your fork gh-pages branch for instance: …
> chore(report): only overide folders and files of the report site

- tools/build/src/build.ts
- tools/build/src/che-theia-plugin/che-theia-plugin-module.ts
- tools/build/src/che-theia-plugin/che-theia-plugin-yaml-info.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-yaml-generator.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-yaml-writer.ts
- tools/build/src/common/container-helper.ts
- tools/build/src/meta-yaml/index-writer.ts
- tools/build/tests/build.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-yaml-generator.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-yaml-writer.spec.ts
- tools/build/tests/meta-yaml/index-writer.spec.ts
meta.yaml has no field to describe preferences, it's not compliant with devfile 2.0 definition of containers, etc.
so, when generating yaml files from che-theia-plugins.yaml , here it generates `che-theia-plugin.yaml` file in addition to meta.yaml
https://github.com/eclipse/che/issues/19545
Launch the build or look at the PR result and browse index.json, you will see plugin entries for VS Code extensions and it will contain links to `che-theia-plugin.yaml` fragment that you can also look
example: https://pr-check-933-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/java11/latest/che-theia-plugin.yaml
Reviewers, please comment how …
> feat(plugins): generate che-theia-plugin.yaml fragment in addition to meta.yaml for VS Code extensions

- .pnp.js
- CONTRIBUTE.md
- che-theia-plugins.yaml
- package.json
- tools/build/src/build.ts
- tools/build/src/che-theia-plugin/che-theia-plugin-analyzer-meta-info.ts
- tools/build/src/che-theia-plugin/che-theia-plugin-yaml-info.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-meta-yaml-generator.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-yaml-generator.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-yaml-writer.ts
- tools/build/src/che-theia-plugin/che-theia-plugins-yaml.ts
- tools/build/src/extensions/vsix-info.ts
- tools/build/src/meta-yaml/index-writer.ts
- tools/build/src/meta-yaml/meta-yaml-plugin-info.ts
- tools/build/src/meta-yaml/meta-yaml-writer.ts
- tools/build/tests/build.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugin-analyzer.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-meta-yaml-generator.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-yaml-generator.spec.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-yaml-writer.spec.ts
- tools/build/tests/extensions/vsix-info-mock.ts
- tools/build/tests/meta-yaml/meta-yaml-writer.spec.ts
- tools/build/tests/packages/che-theia-plugins-generator.ts
- yarn.lock
Parse extensionDependencies field of vsix to detect plugin dependencies
rename extensions field in `che-theia-plugins.yaml` to  `extension` as only one vsix is defined per vsix anyway.
meta.yaml will contain all vsix of dependencies and che-theia-plugin.yaml will contain the dependencies to other plug-ins
also make sure all generated yaml are not multiline
It'll simplify devWorkspace plugins dependencies as we'll have graph of dependencies and avoid duplicates
https://github.com/eclipse/che/issues/15376
Check meta.yaml, they should contain the same data than before …
> feat(plugins): Use extensionDependencies field of package.json to get dependencies

- build.sh
- build/dockerfiles/Dockerfile
- build/dockerfiles/entrypoint.sh
- build/dockerfiles/test_entrypoint.sh
- devfile.yaml
1. Fix problems with image regexp:
- single quotes not supported
- multiline not supported
- multiple occurence
2. Adding unit tests script
N/A
https://github.com/eclipse/che/issues/19405 and https://github.com/eclipse/che/issues/19492
1. Build the registry from this branch:
```
./build.sh
```
3. run the built container and check that  meta.yaml generated are OK, for instance `/var/www/html/v3/plugins/ms-python/python/latest/meta.yaml`
```
podman run -t quay.io/eclipse/che-plugin-registry:nightly cat /var/www/html/v3/plugins/ms-python/python/latest/meta.yaml
```
should contain these lines
```yaml
- image: 'quay.io/eclipse/che-plugin-sidecar@sha256:64311210e710ca1614839f897285fc1d39b2ca17215d56c165d091aafd19a14b'
```
4. check that meta.yaml works well with the env variable …
> fix(entrypoint): Fix image regexp when using CHE_SIDECAR_CONTAINERS_REGISTRY_URL

- .ci/sidecar-build-publish.sh
Ensure short sha1 for sidecar is 7 digits long
last time it was 8 digits (camelk-2eb28e46 instead of camelk-2eb28e4)
PR checks were failing
```bash
$  git rev-parse --short HEAD
12e5943e
```
```bash
$ git rev-parse --short=7 HEAD
12e5943
```
Change-Id: I79ceba176120a87801bb4a1d12e9d1e217927448
> chore(sidecar): Ensure short sha1 for sidecar is 7 digits long

- che-editors.yaml
- make-release.sh
Currently the release script is not bumping the `name` field for the versioned eclipse/che-theia entry (it is currently stuck on 7.29.0). This PR adjusts the `make-release.sh` script to correctly bump the `name` field as well.
N/A
N/A
Run the `make-release.sh` script and observe that the metadata -> name field is updated correctly.
> Bump che-editors.yaml metadata -> name field on release

- tools/build/src/che-theia-plugin/che-theia-plugins-meta-yaml-generator.ts
- tools/build/tests/che-theia-plugin/che-theia-plugins-meta-yaml-generator.spec.ts
Due to missing metadata in dependencies, generated links were missing the relative part for dependencies
https://github.com/eclipse/che/issues/19746
build with `--offline` flag or use `yarn node lib/entrypoint.js --embed-vsix:true`
generated `v3/plugins/redhat/java/latest/meta.yaml` should contain `relative:extension` on all extensions
```yaml
- 'relative:extension/resources/download_jboss_org/jbosstools/static/jdt_ls/stable/java-0.75.0-60.vsix'
- 'relative:extension/resources/download_jboss_org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix'
- 'relative:extension/resources/open-vsx_org/api/vscjava/vscode-java-test/0_28_1/file/vscjava.vscode-java-test-0.28.1.vsix'
``` …
> fix(build): offline links were not added on dependencies of an extension

- che-theia-plugins.yaml
Updates the vscode-xml extension to 0.16.0
Fixes eclipse/che#19494
> Update vscode-xml to 0.16.1

- sidecars/python/Dockerfile
- sidecars/python/etc/entrypoint.sh
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Sidecar part, using the same venv folder for:
- jupyter notebook from the python plugin
- projects with dependencies in `requirements.txt`
https://youtu.be/FPZa5jc8sYE
https://github.com/eclipse/che/issues/16818
will come with the plugin part (in a second PR once this is merged) but could be tested with:
```yaml
metadata:
generateName: python-jupyter-
projects:
- name: jupyter-hello-world1
source:
startPoint: master
location: 'https://github.com/chasbecker/TextAnalysis.git'
type: git
components:
- id: ms-python/python/latest
registryUrl: 'https://sunix-che-plugin-registry-dev-i1viq.surge.sh/v3'
- mountSources: true
memoryLimit: 512Mi
volumes:
- name: venv
containerPath: …
```
> feat(python-jupyter): Setting up venv in a dedicated volume

- .che-didact-guide.md
When using the dogfooding devfile, the links to open files in the didact guide are broken because of the multi root workspace enabled (before we had 1 project `/projects` whereas now 1 project `/projects/che-plugin-registry`
This PR is fixing the paths.
N/A
N/A
Run the new devfile, try to open the files from the didact guide.
> fix(dogfooding devfile): fix path of files to open from the didact guide that has changed after switch to multiroot.

- tools/build/src/meta-yaml/meta-yaml-writer.ts
- tools/build/tests/meta-yaml/meta-yaml-writer.spec.ts
Removes `/v3...` at the beginning of the icon path.
Having `/v3` gives wrong icon path for single root Che deployment.
It must work for both
- `https://plugin-registry-eclipse-che.apps-crc.testing/v3`
and
- `https://che-eclipse-che.apps-crc.testing/plugin-registry/v3`
If the icon without `/v3`, to show the icon Theia will just concatenate plugin registry root and icon path.
It needs to merge this PR together with https://github.com/eclipse-che/che-theia/pull/1118.
https://github.com/eclipse/che/issues/19771
> Icon path must be relative to plugin registry root folder

- tools/build/package.json
Make package public so it can be published
Else we have the following error:
```
npm ERR! code EPRIVATE
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```
https://github.com/eclipse/che/issues/19741
you can look at https://github.com/eclipse-che/che-plugin-registry/runs/2715989741 that says
`Remove the 'private' field from the package.json to publish it.`
Change-Id: I08d876d24a8555e8168c0263f7c97d0af8130478
> chore(npm): Make package not private so it can be published on npm registry

- .github/workflows/typescript-publish.yml
Setup the registry URL to publish
Else we have the following error:
```
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@eclipse-che%2fplugin-registry-generator - Not found
npm ERR! 404 
npm ERR! 404  '@eclipse-che/plugin-registry-generator@7.32.0-dev-a23d694' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```
https://github.com/eclipse/che/issues/19741
you can look at https://github.com/eclipse-che/che-plugin-registry/runs/2718717324?check_suite_focus=true
Change-Id: …
> chore(publish): Rename the action to publish to 'publish' and also configure the registry to publish with node action

- build/dev/publish-plugin-registry-to-gh-pages.sh
- devfile.yaml
for the plugin registries published in gh-pages, serving meta.yaml content when the full path is omitted.
For instance https://eclipse-che.github.io/che-plugin-registry/7.30.1/v3/plugins/eclipse/che-theia/latest should display the content of the https://eclipse-che.github.io/che-plugin-registry/7.30.1/v3/plugins/eclipse/che-theia/latest/meta.yaml
N/A
Fix https://github.com/eclipse/che/issues/19820
Either trust me and try https://sunix.github.io/che-plugin-registry/nightly/v3/plugins/
or
1. start the devfile out of this branch,
2. build the registry with the predifine command
3. in a terminal of the builder:
export GITHUB_ACTOR=yourgithubusername; 
export GITHUB_TOKEN=yourgithubtoken;
./build/dev/publish-plugin-registry-to-gh-pages.sh …
> fix(push-ghpages): serving meta.yaml content when the full path is omitted

- README.md
Use github.io as default link instead of surge.sh
N/A
[Look at rendered README file](https://github.com/benoitf/che-plugin-registry/blob/a06acbd8f56113c26c3c1c6a511f6284e5595ef0/README.md)
Change-Id: Icb895acab9b90d5eda1b258ed53afd1d01d84569
> docs: use github.io link instead of surge

- che-theia-plugins.yaml
Use same publication name for quarkus extension than on VS Code marketplace (or in package.json of the extension)
https://github.com/eclipse/che/issues/20013
There is an alias, so previous name should be still there in the published registry.
And new name should be there as well
Change-Id: Ia438acdd5c7ead199f4eb7e59bee191fff715c10
> fix(name): Use redhat.vscode-quarkus as default id

- che-theia-plugins.yaml
- sidecars/camelk/Dockerfile
Upgrade to the newer version of VS Code Camel K 0.0.26. it provides kamel cli 1.5.0 by default.
#19818
https://issues.redhat.com/browse/CRW-609?focusedCommentId=13990929&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13990929
https://developers.redhat.com/blog/2020/01/24/apache-camel-k-development-inside-eclipse-che-iteration-1
> Upgrade to VS Code Camel K 0.0.26 #19818

- che-editors.yaml
Adds missed cpuLimit and cpuRequest into che-theia/latest ediitor.
https://github.com/eclipse/che/issues/20270
Check if `theia-ide` component in`eclipse/che-theia/latest` plugin contains  
```yaml
memoryLimit: 512M
cpuLimit: 1500m
cpuRequest: 100m
```
> fix: add missed resource limits/requests for che-theia/lates

- che-theia-plugins.yaml
Add a plugin for js-debug, the default debugger in VS Code.
https://github.com/eclipse/che/issues/19952
Create a workspace referencing the meta.yml generated by this PR
> feat: Add jsdebug VS Code Extension v1.52.2

- .github/workflows/try-in-web-ide.yaml
https://github.com/marketplace/actions/try-in-web-ide
adding 'try-in-web-ide' GitHub action - https://github.com/marketplace/actions/try-in-web-ide 
Related to https://github.com/eclipse/che/issues/20155
> feat: adding 'try-in-web-ide' GitHub action

- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Signed-off-by: Michal Vala <mvala@redhat.com>
Don't replace 127.0.0.1. It is not secure to listen on all interfaces. After merging https://github.com/eclipse-che/che-operator/pull/1045 it is no longer needed.
https://github.com/eclipse/che/issues/20482
image `quay.io/mvala/che-plugin-registry:theiaSec`
1. deploy che with devworkspaces and plugin-registry ^
2. start a workspace
3. check theia really listens on 127.0.0.1 
> fix: don't rewrite 127 to 0.0.0.0

- build/dockerfiles/rhel.Dockerfile
This will deny access to security sensitive .ht files and increase the default encryption level for SSL.
https://issues.redhat.com/browse/CRW-2118
We use these settings downstream in IBM Wazi Developer for Workspaces.
> fix: CRW-2118: Contributing security updates for httpd

- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/tests/_data/meta/che-theia-meta-with-multiple-volumes.yaml
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
This changes proposal filter volume mounts that have identical names and leave only one volume configuration in components list.
The problem occurs after merging: https://github.com/eclipse-che/che-plugin-registry/pull/1055
So, the `remote-runtime-injector` and `theia-ide` components have two identical volume mounts, and devfile generator created two identical volume components, which prevented workspace startup. The solution for that issue is to filter identical components and leave only one configuration.
https://github.com/eclipse/che/issues/20545
Reviewers, please comment how …
> Filter identical volume mounts in components list

- .github/workflows/happy-path.yaml
- .github/workflows/image-build-pr-check.yml
- .github/workflows/next-build.yml
- .github/workflows/publish-content-push-main.yml
- .github/workflows/publish-plugin-report.yaml
- .github/workflows/publish-pr-check-content.yml
- .github/workflows/release.yml
- .github/workflows/resource-limits-pr-check.yaml
- .github/workflows/typescript-pr-check.yml
- .github/workflows/typescript-publish.yml
- tools/build/tests/build.spec.ts
Use nodejs 16 during the builds
Fixes https://github.com/eclipse/che/issues/20795
PR check jobs should handle it
Change-Id: I0d7b2cd14a395b052e3e21ff2219d558e808eabd
> chore: switch to nodejs 16

- tools/build/src/editor/che-editors-meta-yaml-generator.ts
- tools/build/src/meta-yaml/index-writer.ts
- tools/build/src/meta-yaml/meta-yaml-plugin-info.ts
- tools/build/src/meta-yaml/meta-yaml-writer.ts
- tools/build/src/registry/registry-helper.ts
- tools/build/tests/meta-yaml/index-writer.spec.ts
- tools/build/tests/meta-yaml/meta-yaml-writer.spec.ts
For example for VS Code we want to support only for DevWorkspaces (so no meta.yaml should be generated)
so this PR allow to bypass meta.yaml generation
https://github.com/eclipse/che/issues/20505
There are tests checking this behavior
Change-Id: I5094de43d74102f1fbaeebbdcee0de602b6ef29c
> chore: Allow to skip the generation of meta.yaml

- che-editors.yaml
- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/tests/_data/meta/container-minimal-endpoint.yaml
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
move path attribute to the upper endpoint field as path is a known keyword in Devfile v2 scope
https://github.com/eclipse/che/issues/20505
Look at generated devfile.yaml, path should be a field of the endpoint
or look at unit tests
Change-Id: I6e1a9c660911ebe037930f60b4f4a410e2d3f4c0
> feat: DevWorkspaces endpoint path is a field, not an atttribute

- che-theia-plugins.yaml
Updates vscode-java to the latest version (0.8.2) 
https://github.com/eclipse/che/issues/20134
> Update vscode-java to 0.82

- .github/workflows/dependabot-pr-workaround.yml
By default in CI, yarn is not allowed to override yarn.lock file so this dependabot-pr-fix was failing
failures in fixing jobs created by dependabot
Check actions of dependabot-fix
> chore: allow to override yarn.lock in CI jobs to update dependabot

- .github/workflows/dependabot-pr-workaround.yml
In dependabot fix job, do not add .pnp / cache folder as it's in .gitignore
Fix dependabot PR
Check github action
Change-Id: I890fdee555c486ff221eeea5021bfd7fea49b8ac
> chore: do not add .pnp / cache folder as it's in .gitignore

- .github/workflows/dependabot-pr-workaround.yml
Allow to override the author of the PR when amending the dependabot PR
It allows to trigger current workflows.
Else, when using the dependabot identity, there is no workflow action triggered to avoid infinite loop
This is now possible as Github released this night github dependabot secrets API
`https://github.com/dependabot/dependabot-core/issues/3297#issuecomment-1009308206`
So all our PR checks will be run on the dependabot PR
I've tested on a forked repository
> chore: use secrets for dependabot

- .github/CODEOWNERS
Remove tsmaeder from codeowners
> chore: remove tsmaeder from codeowners

- che-editors.yaml
This changes proposal adds volume mount for storing Projector configuration between workspace restarts. This allows to restore IDE state after workspace start.
This PR should be merged only after merge https://github.com/che-incubator/jetbrains-editor-images/pull/74
N/A
fixes https://github.com/eclipse/che/issues/21011
Create workspace from the following link on minikube:
```
https://<your-che-host>/dashboard/#https://github.com/che-incubator/jetbrains-editor-images?che-editor=https://gist.github.com/vzhukovs/55caad47363e1b4f3d4a6ab3fe85a03a/raw/4ca14714fb4da371596cef2aa9aa6afbcbe4c2a1/devfile.yaml
```
Go to File - Save All and then restart the workspace. Editor state should be restored.
[As the author of this Pull Request I made …
> Add volume for storing Projector configuration between workspace restarts

- che-editors.yaml
This changes proposal updates existed version of `che-idea` and `che-pycharm` editors to `next` ones and adds two version of latest released version after release tagged images: https://github.com/che-incubator/jetbrains-editor-images/releases/tag/20220117.828e6c5 which supports sidecar-less model.
N/A
https://github.com/eclipse/che/issues/20863
- che-idea:latest
```
https://<your-che-host>/dashboard/#https://github.com/che-incubator/jetbrains-editor-images?che-editor=https://gist.githubusercontent.com/vzhukovs/55caad47363e1b4f3d4a6ab3fe85a03a/raw/508747d502a557cd3e14ea352b35ed8798b98977/devfile.yaml
```
- che-idea:next
``` …
```
> Add next and latest versions of che-idea and che-pycharm editors

- che-editors.yaml
This changes proposal adds additional volume mount to persist `/home/user/.java` folder which is responsible for storing system Java preferences.
N/A
https://github.com/eclipse/che/issues/21116
Create the workspace from the following editor configurations and see in a console that folder is mounted.
> Persist Java preferences folder

- che-editors.yaml
Use published `next` tags instead of `<version>-next` to avoid missing manifest in case if `<version>-next` is updated.
N/A
https://github.com/eclipse/che/issues/21031
For che-idea it is enough to create the workspace from the following repository:
```
https://github.com/vzhukovs/demo-repository/tree/che-21031-idea
```
For che-pycharm:
```
https://github.com/vzhukovs/demo-repository/tree/che-21031-pycharm
```
in both cases the `next` tag should be fetched and the workspace should be opened.
> Use next image tag instead of <version>-next

- .ci/openshift-ci/nightly-test.sh
Don't start not adapted plugins tests on openshift-ci nightly job. For now only 2 plugins test updated.
This issue is a part of https://github.com/eclipse/che/issues/21210.
> test: Don't start not adapted plugins tests on openshift-ci nightly job

- .ci/openshift-ci/nightly-test.sh
- .ci/openshift-ci/test.sh
Disable openshift-ci tests as it's not passing right now
Change-Id: I646602b0b09a311f87ef2b876152f59f28eb06bd
> tests: disable tests for now

- che-editors.yaml
Signed-off-by: David Kwon <dakwon@redhat.com>
Removes the `--idle-timeout` from `che-theia:next` and `che-theia:latest` editors.
The idle timeout is now being [read as an environment variable](https://github.com/eclipse-che/che-machine-exec/pull/208) set by [Che + DWO](https://github.com/eclipse-che/che-operator/pull/1443).
Removing `--idle-timeout` from editors: https://github.com/eclipse/che/issues/21390
> chore: remove --idle-timeout for che-theia editor since timeout is read from environment variable

- build/dockerfiles/entrypoint.sh
- build/dockerfiles/test_entrypoint.sh
In case when the plugin registry was built on offline mode, all vsx files are located inside the image.
che-theia-plugin.yaml should use CHE_PLUGIN_REGISTRY_INTERNAL_URL to reference to vsx files
This PR replaces `relative:extension` with CHE_PLUGIN_REGISTRY_INTERNAL_URL in che-theia-plugin.yaml files
https://github.com/eclipse/che/issues/21585
1. Build plugin registry with --offline attribute
2. Use resulted image in your cluster by pointing it in the CRD:
```
deployment:
containers:
- image: 'vsvydenko/che-plugin-registry:next'
```
Reviewers, please comment how you …
> fix: replace relative:extension with internal URL of plugin registry

- .ci/openshift-ci/common-functions.sh
Remove `installer=operator` parameter form the chectl command, it's needed to fix tests on OS
> fix: update chectl deploy command

- che-theia-plugins.yaml
Updates fabric8-analytics-vscode extension to 0.3.6
[screencast-nimbus-capture-2022.08.10-22_31_27.webm](https://user-images.githubusercontent.com/1271546/184678930-e284d50f-dff9-46d0-9d6e-372f460869a0.webm)
https://github.com/eclipse/che/issues/21372
1. deploy che
`chectl server:deploy --che-operator-cr-patch-yaml=custom-resources.yaml --platform=openshift`
where the content of **custom-resources.yaml** is:
```
apiVersion: org.eclipse.che/v2
spec:
components:
deployment:
containers:
- image: vsvydenko/che-plugin-registry:next
```
2. Start a Python workspace and install fabric8-analytics plugin:
3. Test fabric8-analytics plugin
**_NOTES_**:
_The plugin has a problem in Che-Theia when generate the report by using project …
> feat: update fabric8-analytics to 0.3.6

- build/dockerfiles/Dockerfile
There is a need to apply sed operations on files https://github.com/eclipse-che/che-plugin-registry/pull/1351
for INTERNAL_URL so we require write permissions on these files
fixes https://github.com/eclipse/che/issues/21641
Create a file named `/tmp/patch.yaml`
```yaml
spec:
components:
deployment:
containers:
- image: 'quay.io/fbenoit/che-plugin-registry:21641-2022-19-08'
```
deploy with
```bash
chectl server:deploy --platform=openshift --che-operator-cr-patch-yaml=/tmp/patch.yaml
```
Change-Id: I0c534daec82111a63a2346fa40d34726908f8d16
Signed-off-by: …
> fix: update file permissions

- build/dockerfiles/start-services.sh
postgresql requires a bit more time to start. 
The value was increased for 5 seconds to 15 seconds.
https://github.com/eclipse/che/issues/21621
1. Build the image:  ./build.sh --tag next
2. Run docker run -it --rm --env START_OPENVSX=true --entrypoint /entrypoint.sh quay.io/eclipse/che-plugin-registry:next
https://user-images.githubusercontent.com/1271546/186768129-4764d4ef-6509-4ede-b2d9-2b2adef427c1.mp4
> fix: increase timeout for starting postgresql

- build/dockerfiles/start-services.sh
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
* remove 15s timeout to wait until PostgreSQL is ready
* remove 200s timeout to wait until VSX registry is ready
Is save enough to remove those timeout since plugin-registry container will be automatically restarted once liveness probe failed (300s).
N/A
https://github.com/eclipse/che/issues/21666
N/A
> chore: Wait until PostgreSQL and VSX registry is ready

- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/tests/_data/meta/che-theia-meta.yaml
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Use `metadata.name` instead of `metadata.displayName` to generate devfile.yaml.
https://github.com/eclipse/che/issues/21704
> chore: use name instead of displayName in generated editor devfile

- che-editors.yaml
Adds container-contribution attribute for VS Code and Theia editors.
**_NOTE_: The IDEA editor wasn't changed**
Resulted editors devfiles:
<details>
<summary>VS Code</summary>
```yaml
schemaVersion: 2.1.0
metadata:
name: che-code
commands:
- id: init-container-command
apply:
component: che-code-injector
events:
preStart:
- init-container-command
components:
- name: che-code-runtime-description
container:
image: quay.io/devfile/universal-developer-image:ubi8-13008af
command:
- /checode/entrypoint-volume.sh
volumeMounts:
- name: checode
path: /checode
memoryLimit: 1024Mi
memoryRequest: 256Mi
cpuLimit: 500m
cpuRequest: 30m
endpoints:
- name: che-code
attributes:
type: main
cookiesAuthEnabled: true
discoverable: false
urlRewriteSupported: …
```
> chore: add container-contribution attribute for editors

- build/dockerfiles/Dockerfile
Apache HTTP Server restricts the size of the HTTP request header allowed from the client. Default value is set to 8192 (8 KB). In order to avoid request blocking by this limitation, `httpd.conf` has been adjusted to set 32768 (32 KB).
The size of the HTTP request header allowed from the client is limited to 32 KB (not to 8 KB by default) after this change.
You can sum cookie size on screenshot below - about 16 KB. And we got success response.
https://github.com/eclipse/che/issues/21917
1. Deploy Che with `docker.io/karatkep/che-plugin-registry:hs-32kb` as plugin-registry image.
2. Call any plugin-registry URL, for example: GET /plugin-registry/v3/plugins/che-incubator/che-code/insiders/devfile.yaml. Please see screenshot above. …
> Increase the size of the HTTP request header allowed from the client to 32 KB

- .github/workflows/image-build-pr-check.yml
- che-editors.yaml
- Increase memoryLimit for che-code-injector component to 256Mi
- Fix an action to publish PR content to surge
https://github.com/eclipse/che/issues/21719
Start a workspace by using factory:
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#/https://github.com/che-samples/web-nodejs-sample/tree/devfilev2?che-editor=https://gist.githubusercontent.com/svor/55d4b83ee3a2f1df5555b8a44c4a539a/raw/43ebe852bdd2338edcce683c63437613cf2ede20/code.yaml
Check that the che-code-injector init container was not restarted:
Reviewers, please comment how you tested the PR when approving …
> chore: increase memoryLimit for che-code-injector component

- che-editors.yaml
1. Marks `che-pycharm-runtime-description` component as container contribution.
2. Replaces `app.kubernetes.io/component: che-pycharm-injector` on `app.kubernetes.io/component: che-pycharm-runtime` to be consistent with `che-code` where everything works without issues
https://github.com/eclipse/che/issues/21878
Depends on https://github.com/eclipse/che/issues/21738
> fix: mark che-pycharm-runtime-description component as container-contribution

- build/dockerfiles/import-vsix.sh
- openvsx-sync.json
- Upgrade redhat.java extension to 1.14.0 version fro local registry
- Most of the VS Code extensions provide only one link for downloading, for example [ms-python.python](https://open-vsx.org/api/ms-python/python/). 
But there are extensions with several links for downloading (depending on a target platform), for example [redhat.java](https://open-vsx.org/api/redhat/java/1.14.0):
```json
"downloads": {
"linux-x64": "https://open-vsx.org/api/redhat/java/linux-x64/1.14.0/file/redhat.java-1.14.0@linux-x64.vsix",
"win32-x64": "https://open-vsx.org/api/redhat/java/win32-x64/1.14.0/file/redhat.java-1.14.0@win32-x64.vsix",
"darwin-x64": "https://open-vsx.org/api/redhat/java/darwin-x64/1.14.0/file/redhat.java-1.14.0@darwin-x64.vsix",
"darwin-arm64": …
```
> chore: download vsix by an universal link

- che-editors.yaml
depends on: https://github.com/eclipse-che/che-plugin-registry/pull/1613
Use post-start event instead of command to start VS Code
https://github.com/eclipse/che/issues/21879
We should check that VS Code starts successfully after resolving https://github.com/devfile/devworkspace-operator/issues/1029 
I tested it like:
- go to the dashboard => `Create Workspace` page
- put https://github.com/RomanNikitenko/devfile-stacks-nodejs-react/tree/post-start to the `Git Repo URL`
- click `Create & Open` button
[The sample](https://github.com/RomanNikitenko/devfile-stacks-nodejs-react/tree/post-start) contains [the corresponding changes](https://github.com/RomanNikitenko/devfile-stacks-nodejs-react/commit/1a5d1ab1eb84e988727cd8df4d10afc10db080a4) for the editor description.
[As the author of this …
> feat: Use post-start event to start VS Code

- .github/workflows/regen-yarn-lock-and-copy.yml
Copy yarn.lock into tools/build/ in PR branch
> fix: do copy yarn.lock in PR branch

- build/dockerfiles/Dockerfile
- build/dockerfiles/import-vsix.sh
- openvsx-sync.json
Finds latest and stable version for each extension that is going to be included into the embedded plugin registry.
Also it checks that vscode engine version in the extension is compatible with Che Code version.
https://issues.redhat.com/browse/CRW-4165
https://issues.redhat.com/browse/CRW-4336
- Run che with current version of plugin registry
- Activate embedded plugin registry
- Check that latest stable version of vscode-java extension (redhat.java-1.18.0) is available and it's possible to install it
> chore: find a first stable and compatible version of the extension to include it into the embedded plugin registry

- build/dockerfiles/Dockerfile
- build/dockerfiles/entrypoint.sh
- build/dockerfiles/import-vsix.sh
- build/dockerfiles/start-services.sh
- Updates openvsx image to use more freshest openvsx-server in the embedded plugin registry;
- Upgrades postgresql to 15 version
- Upgrade java to 17 version
- Upgrades ovsx to 0.8.2 version
https://github.com/eclipse/che/issues/22247
- Deploy che
- Update eclipse-che CR to use internal plugin registry with custom image:
```
deployment:
containers:
- image: 'quay.io/vsvydenk/che-plugin-registry:13'
openVSXURL: ''
```
- Start any workspace and check that plugins are available in the Plugins view and it's possible to install them:
> chore: upgrade ghcr.io/eclipse/openvsx-server image and depended tools

- build/dockerfiles/import-vsix.sh
Add retry loop for getting versions since the internet is unreliable.
Fixes problem like https://github.com/eclipse-che/che-plugin-registry/actions/runs/6169274637/job/16743208406#step:7:2335
> chore: add retry loop to get versions

- deploy/openshift/che-plugin-registry.yml
Update deployment configuration for Open Shift
https://github.com/eclipse/che/issues/20133
1. Login to OS cluster
2. Execute command from README to deploy che plugin registry:
```bash
oc new-app -f deploy/openshift/che-plugin-registry.yml \
-p IMAGE="quay.io/eclipse/che-plugin-registry" \
-p IMAGE_TAG="next" \
-p PULL_POLICY="Always"
```
3. Plugin registry should be deployed and available. In the output you should see a message:
```
--> Success
Access your application via route 'che-plugin-registry-pr.apps.rosa.dzhix-cyddx-yrv.1697.p3.openshiftapps.com' 
Run 'oc status' to view your app.
```
4. Try to open route URL from the message and add **/v3/plugins** at the end
5. You should see: …
> chore: update Deployments on OpenShift

- che-editors.yaml
- tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
- tools/build/tests/_data/meta/che-code-meta.yaml
- tools/build/tests/common/endpoints-helper.spec.ts
- tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
use https protocol in the 'che-incubator/che-code/insiders' editor
Note that it only changes protocol for `che-incubator/che-code/insiders`, not sure if we should update it for the rest of the editors (some of which look obsolete now and should probably be removed).
https://issues.redhat.com/browse/CRW-4869
Tested with custom che-editor.yaml - https://github.com/ibuziuk/quarkus-api-example/blob/main/.che/che-editor.yaml
> fix: use https protocol in the 'che-incubator/che-code/insiders' editor

- make-release.sh
Updates make-release.sh to use gh instead of hub
https://github.com/eclipse/che/issues/22646
> Fix: use gh instead of hub for Che #22646

- .ci/openshift-ci/Dockerfile
Gets rid of faulty "curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.8/openshift-client-linux.tar.gz" command in OpenShift CI jobs (it was an idea of @artaleks9).
Fixing error example: https://storage.googleapis.com/test-platform-results/pr-logs/pull/eclipse-che_che-plugin-registry/1870/pull-ci-eclipse-che-che-plugin-registry-main-v14-plugins-test-pr-check/1747174582978088960/build-log.txt
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: …
```
> Get rid of failing curl in OpenShift CI jobs

- CONTRIBUTE.md
Add a part about **Adding a Che Editor to Che** into CONTRIBUTE.md file
https://github.com/eclipse/che/issues/22854
> chore: update contribution part about editor definition

- CONTRIBUTE.md
- che-editors.yaml
- tools/build/src/devfle-yaml/index-writer.ts
- tools/build/tests/devfile-yaml/index-writer.spec.ts
Adds Tech-Preview tag for all editors except **che-code/latest**
<details>
<summary>index.json content:</summary>
```json
[
{
"id": "cdr/code-server/latest",
"description": "An open source distribution of Visual Studio Code (code-server) for Eclipse Che",
"displayName": "VS Code via code-server",
"links": {
"devfile": "/v3/plugins/cdr/code-server/latest/devfile.yaml"
},
"tags": [
"Tech-Preview"
],
"name": "code-server",
"publisher": "cdr",
"type": "Che Editor",
"version": "latest",
"icon": "/v3/images/vscode.svg"
},
{
"id": "che-incubator/che-code/insiders",
"description": "Microsoft Visual Studio Code - Open Source IDE for Eclipse Che - Insiders build",
"displayName": "VS Code - Open Source",
"links": {
"devfile": "/v3/plugins/che-incubator/che-code/insiders/devfile.yaml"
},
"tags": [ …
```
> chore: add Tech-Preview tag into editors' definitions
